#!/usr/bin/env python3
"""CART — Instacart (Maplebear) (NASDAQ) mature-company memo spec. Emits data/_intake/cart.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1579091; company legal name Maplebear Inc; IPO Sep 2023 @ $30)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="CART", company="Instacart (Maplebear)", exch="NASDAQ", spot=41.25, cap=9.92, sh=240.6, cash=0.69, net_debt=0.0, rev_b=3.742,
 wl="fcf-plus-plus-growth", tier="Med", themes=["platform-marketplace-tech"],
 extras=[
   "Net cash +$0.69B, no debt; ~241M shares held ~flat as a $3.5B buyback (~35% of the market cap) offsets SBC dilution",
   "Revenue $3.74B FY25 (+11%); GAAP op margin 13.3% (12.3->17.9% latest quarter); reported FCF ~$0.9B includes a heavy SBC add-back",
   "Down ~5% YTD/TTM at ~$41 (52-wk $32.73-$53.50); screens ~11x reported FCF, ~2.7x EV/sales"],
 cq="Does Instacart's high-margin advertising flywheel keep compounding on a $10B+ GTV base, or does a deep-pocketed delivery field and a structurally low take rate cap the marketplace?",
 thesis="Instacart trades at ~$9.9B (~$41.25, ~-5% YTD) — ~11x reported FCF and ~2.7x EV/sales on $3.74B revenue (+11%), net cash, GAAP operating margin scaling 12.3->17.9%. The engine is ~80%-margin advertising compounding on a $10B+ GTV base, with a $3.5B buyback (~35% of the cap) offsetting SBC dilution so shares stay flat. The DCF asks whether high-margin ad revenue keeps scaling against DoorDash/Uber/Amazon/Walmart and a ~7% take rate. The finding: even pricing the competitive bear (ultra-bear -28%), the modal flywheel case lands +57%, with reported FCF discounted to ~15-19% ex-SBC owner margin.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[1.8,2.6,3.0,3.4,3.74]),
   ("history_op_margin",[-4.7,2.4,-70.4,14.5,13.3]),
   ("history_fcf",[-0.2,0.3,0.5,0.6,0.9]),
   ("history_ev_rev",[4,3,3.5,3,2.7])],
 p3cfg=[("segment_a","Transaction"),("segment_b","Advertising & other"),
   ("hist_ent_split",[0.78,0.76,0.74,0.73,0.72]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  Q1-2026 (May'26) results",
 sources="Sources: SEC XBRL company facts (CIK 1579091, Maplebear Inc; revenue, GAAP operating income/margin, cash flow, debt), Instacart Q1-2026 release (May 6: GTV $10.29B +13% first >$10B, revenue $1.02B +14% with transaction $733M / advertising & other $286M +16%, orders 91M +10%, GAAP op margin 17.9%, FCF $253M, SBC ~$93M, $3.5B buyback). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin (ex-SBC owner FCF ~15-19%); Gordon terminal at scenario WACC. EV/sales & EV/FCF vs DoorDash/Uber/Amazon/Walmart.",
 ipo="IPO Sep '23", xmin=-2.7,
 points=[[-2.7,30],[-2.3,24],[-1.8,35],[-1.2,48],[-0.8,53],[-0.4,40],[-0.1,33],[-0.05,41.25]],
 scn={
  "ultra_bear":dict(p=0.13,g=[0.02,0.03,0.03,0.03,0.03],fcfm=[0.11,0.12,0.13,0.13,0.14],opm=[0.11,0.12,0.13,0.13,0.14],wacc=0.105,tg=0.025,fs=244,evr=[2,1.8,1.6,1.5,1.4],evf=[13,13,13,13,13],
    hl="Ad growth stalls; delivery field wins.",
    narr=["The competitive bear bites: DoorDash, Uber Eats, Amazon and Walmart pull GTV and the ~7% take rate compresses, while advertising growth fades from its decelerating guide toward low-single-digit. Orders are already trailing GTV (+10% vs +13%), signalling a maturing, low-frequency marketplace; the ~80%-margin ad flywheel stops scaling and operating margin stalls in the low-teens.","A marketplace whose high-margin engine stops compounding earns a low terminal multiple -> DCF ~$29.71 (-28%). Net cash and the buyback set a floor but cannot offset a stalled flywheel."],
    pr="The genuine bear: the FY ad guide of 11-14% is a sharp deceleration from the 27% (2023) / 34% (2022) era, the field is deep-pocketed, and orders trail GTV. 13% weight on the flywheel failing on a contested base."),
  "bear":dict(p=0.27,g=[0.06,0.06,0.05,0.05,0.05],fcfm=[0.14,0.15,0.15,0.16,0.16],opm=[0.14,0.15,0.16,0.17,0.18],wacc=0.100,tg=0.030,fs=242,evr=[2.5,2.3,2.2,2.1,2],evf=[15,15,15,15,15],
    hl="GTV grows; ad take-rate caps the upside.",
    narr=["GTV keeps growing low-to-mid-single-digit but advertising decelerates as guided and the take rate stays structurally low, so the margin flywheel turns slowly: revenue compounds ~5% to ~$4.7B at a mid-teens ex-SBC FCF margin. The category lead holds, but the deep competitive set and a ~7% take rate cap the marketplace economics.","DCF ~$42.64 (+3%) - roughly fair. A leader whose high-margin engine grinds rather than compounds is worth about today's price; the cheap multiple is warranted if advertising only decelerates."],
    pr="Share holds but the guided ad deceleration plus take-rate pressure cap the re-rate. 27% as the plausible 'leads but doesn't compound' path, given the 11-14% ad guide and orders trailing GTV."),
  "base":dict(p=0.34,g=[0.12,0.11,0.10,0.09,0.08],fcfm=[0.15,0.16,0.17,0.18,0.19],opm=[0.16,0.18,0.20,0.22,0.24],wacc=0.095,tg=0.030,fs=240,evr=[3,2.8,2.7,2.6,2.5],evf=[17,16,16,16,16],
    hl="Ad flywheel scales; FCF margin to ~19%.",
    narr=["The modal path: GTV compounds low-double-digit off the first >$10B quarter, advertising re-accelerates above its conservative guide as enterprise (Carrot, Caper smart carts) and retail-media density build, and the ~80%-margin ad mix lifts operating margin from ~13% toward the mid-20s. Ex-SBC owner FCF margin grinds from ~15% toward ~19% while the $3.5B buyback offsets SBC dilution and shares stay flat. Revenue compounds ~10% to ~$5.7B.","DCF ~$64.58 (+57%) - the high-margin advertising engine compounding on a durable GTV base re-rates the franchise off ~11x reported FCF; the core of the thesis. The cash bridge adds net cash and the modal terminal multiple does the rest."],
    pr="Requires advertising to keep scaling (and modestly re-accelerate) on a growing GTV base while operating leverage continues - consistent with Q1's +16% ad growth and the 12.3->17.9% margin move, but ahead of the 11-14% guide. 34% as the central outcome."),
  "bull":dict(p=0.18,g=[0.16,0.14,0.13,0.11,0.10],fcfm=[0.17,0.18,0.20,0.21,0.22],opm=[0.18,0.21,0.24,0.26,0.28],wacc=0.090,tg=0.035,fs=238,evr=[3.5,3.3,3.2,3.1,3],evf=[20,19,19,19,19],
    hl="Retail-media platform; margin inflects.",
    narr=["Advertising re-accelerates decisively: Instacart becomes a retail-media platform where ~80%-margin ad dollars compound faster than GTV, enterprise tech (Carrot, Caper, ALDI-type partnerships) widens the moat, and operating margin inflects toward ~28% with ex-SBC FCF margin toward ~22%. Revenue compounds ~13% to ~$6.6B.","DCF ~$97.69 (+137%) - if the flywheel converts the GTV base into a durable high-margin ad annuity, the de-rated entry re-rates with the fundamentals; this is the core of the bull."],
    pr="The purchase-data ad engine plus enterprise integrations make a genuine advertising re-acceleration credible. ~18% weight on the retail-media inflection landing."),
  "ultra_bull":dict(p=0.08,g=[0.20,0.18,0.16,0.14,0.12],fcfm=[0.18,0.20,0.22,0.23,0.24],opm=[0.20,0.23,0.26,0.29,0.31],wacc=0.088,tg=0.035,fs=236,evr=[4,3.8,3.7,3.6,3.5],evf=[22,20,20,20,20],
    hl="Ad annuity compounds; FCF machine.",
    narr=["The full second act: advertising scales into a dominant retail-media network, enterprise/Carrot tech becomes a category standard, and the ~80%-margin ad annuity compounds GTV into a true FCF machine at a ~24% ex-SBC margin and ~31% operating margin. The buyback keeps shrinking the float against flat SBC. Revenue compounds ~15% to ~$7.5B.","DCF ~$126.65 (+207%) - the franchise reclaims a platform compounder multiple; ~8% probability, the asymmetric upside the depressed entry is buying."],
    pr="Everything works - GTV AND ad re-acceleration AND enterprise AND a multiple re-rate, the retail-media-platform outcome. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 13%","Ad growth stalls; delivery field wins; ~$29.71 (-28%)."),
     ("Bear 27%","GTV grows but take-rate caps upside; ~$42.64 (+3%)."),
     ("Base 34%","Ad flywheel scales; FCF margin to ~19%; ~$64.58 (+57%)."),
     ("Bull 18%","Retail-media platform; margin inflects; ~$97.69 (+137%)."),
     ("Ultra Bull 8%","Ad annuity compounds; FCF machine; ~$126.65 (+207%).")],
 pb=[("~11x FCF for an 80%-margin ad engine compounding on a $10B+ GTV base.","Net-cash, GAAP op margin scaling 12.3->17.9%, advertising +16% - priced like a contested delivery app, not a retail-media platform; the modal DCF is +57%."),
     ("The buyback is worth ~35% of the market cap.","$3.5B authorized (raised from $2.5B), $349M repurchased in Q1; it offsets SBC dilution so shares stay flat - the ex-SBC owner FCF accrues per-share rather than leaking to issuance."),
     ("Reported FCF flatters the picture.","~$0.9B reported FCF includes a heavy SBC add-back (~$93M/qtr); the base models ex-SBC owner FCF at ~15-19%, the honest cash the buyback must offset - not the headline ~11x."),
     ("Advertising is the whole thesis - and it is decelerating.","~80%-margin ad revenue grew +16% in Q1 but is guided to 11-14%, well below the 27%/34% era; whether it re-accelerates on a $10B+ GTV base is the bull/bear fork."),
     ("Cornered purchase data feeds the ad engine.","First-party grocery purchase data across the retailer network is the hardest input for the delivery field to replicate - a nascent cornered resource the retail-media platform monetizes.")],
 tr=[("Bull validation","advertising re-accelerates above the 11-14% guide  ·  ad revenue compounds faster than GTV  ·  GAAP op margin holds >=18%  ·  enterprise (Carrot/Caper) wins named retailers  ·  buyback keeps shares flat-to-down"),
     ("Bear validation","advertising decelerates into single digits  ·  the ~7% take rate compresses  ·  orders keep trailing GTV (frequency stalls)  ·  GTV growth slows as DoorDash/Amazon/Walmart take share  ·  op margin stalls in the low-teens"),
     ("Reframe needed","if advertising growth converges to GTV growth (no high-margin premium) or the take rate erodes structurally, the flywheel is gone - re-rate the terminal toward a low-margin, contested delivery marketplace multiple")],
 gloss=[("GTV","Gross transaction value - total spend across the platform (groceries + fees + tips), $10.29B in Q1 (+13%, first >$10B); the base the ~7% take rate and the ad engine monetize."),
        ("Take rate","Transaction revenue / GTV (~7.1%); structurally low for grocery delivery and a key bear lever - the marketplace's cut of each order before advertising."),
        ("Advertising & other","High-margin (~80%) retail-media revenue ($286M in Q1, +16%) from brands paying for placement against purchase data - the flywheel and the swing factor; guided to decelerate to 11-14%."),
        ("Enterprise (Carrot / Caper)","Instacart's technology sold to retailers - the Carrot e-commerce stack and Caper AI smart carts - extending the platform beyond delivery and feeding the data/ad engine; the switching-cost lever."),
        ("FCF margin","Free cash flow / revenue; the mature-DCF swing factor - the base models ex-SBC owner FCF (~15-19%), below the ~24% reported, with the $3.5B buyback offsetting SBC dilution.")],
 arena="Online grocery delivery + retail media - Instacart (category leader, $10B+ GTV, ~80%-margin advertising, enterprise/Carrot tech) vs DoorDash, Uber Eats, Amazon and Walmart; auditing a two-sided network Power and a nascent ad-data cornered resource against a deep-pocketed field and a low take rate.",
 powers=[("scale_economies",3,"Largest pure-play grocery-delivery GTV ($10B+/qtr) gives sourcing/logistics density and retail-media reach, but Amazon/Walmart/Uber operate at far greater corporate scale."),
         ("network_economies",4,"The dominant Power: a two-sided retailer/shopper marketplace - more retailers and selection pull more consumers, whose orders pull more retailers and brand ad dollars; a genuine, if contestable, flywheel."),
         ("counter_positioning",1,"Was the asset-light shopper-network disruptor; now the incumbent the delivery field is attacking, not counter-positioning."),
         ("switching_costs",2,"Enterprise integrations (Carrot e-commerce, Caper carts) embed Instacart in retailer operations; consumer switching is low, but the B2B tech is sticky."),
         ("branding",2,"Strong category association ('Instacart' = grocery delivery) but not pricing power; convenience, not brand, drives the order."),
         ("cornered_resource",3,"A nascent cornered resource: first-party grocery purchase data across the retailer network feeds the ~80%-margin ad engine - the hardest input for rivals to replicate, but early and contestable."),
         ("process_power",2,"Shopper-routing, fulfilment and ad-targeting systems are real operating know-how; meaningful but not a decisive, hard-to-copy edge.")],
 dom="network_economies", dur="medium",
 rivals=[("DoorDash (DASH)","public","Larger logistics network expanding aggressively into grocery + retail media; the primary delivery-field threat to GTV and ad share.",0.20,0.04,"~33x EV/FCF"),
         ("Uber Eats (UBER)","public","Global delivery scale + advertising push; Uber Eats grocery directly contests Instacart's lane.",0.18,0.08,"~14x EV/FCF"),
         ("Amazon","public","Whole Foods + Amazon Fresh + Prime + a dominant retail-media machine; the deepest-pocketed structural threat to both legs.",0.10,0.11,"~30x EV/FCF"),
         ("Walmart","public","Walmart+ delivery + the fastest-growing rival retail-media network (Walmart Connect); scale and grocery primacy pressure the take rate.",0.05,0.04,"~30x P/E")],
 threats=[("network_economies","DoorDash / Uber Eats / Amazon / Walmart","GTV growth slows and orders keep trailing GTV as the deep-pocketed field pulls shoppers and retailers off the platform."),
          ("cornered_resource","Amazon / Walmart retail media","Advertising decelerates into single digits as brand ad dollars flow to larger first-party retail-media networks."),
          ("scale_economies","Grocer DTC + delivery-field take-rate pressure","The ~7% take rate compresses as retailers build their own fulfilment or the field undercuts the marketplace cut.")],
 take="Instacart's network Power is genuine - the largest pure-play grocery-delivery GTV ($10B+/qtr) running a two-sided retailer/shopper marketplace that feeds a nascent cornered resource (first-party purchase data -> an ~80%-margin ad engine) and is stickied by enterprise integrations (Carrot, Caper). But the field is the deepest-pocketed in retail - DoorDash, Uber, Amazon, Walmart - and the ~7% take rate plus a guided ad deceleration (11-14% vs the 27%/34% era) are the live threats. The Audit: network_economies is durable but contestable (medium), the ad-data cornered resource is the real prize if it compounds, and the swing factor is whether high-margin advertising keeps scaling on the GTV base. The DCF tests exactly that - and even the competitive ultra-bear is -28% while the modal flywheel lands +57%, with reported FCF honestly discounted to ~15-19% ex-SBC owner margin and the $3.5B buyback offsetting dilution.",
)

if __name__ == "__main__":
    build(SPEC)
