#!/usr/bin/env python3
"""ALGN — Align Technology (NASDAQ) mature-company memo spec. Emits data/_intake/algn.yml
via the reusable Batch-B builder (gen_b1.build). Numerics LOCKED in model_mature;
op-margin history is GAAP (us-gaap:OperatingIncomeLoss / revenue) from SEC XBRL (CIK 1097149)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="ALGN", company="Align Technology", exch="NASDAQ", spot=174.84, cap=12.46, sh=71.3, cash=1.10, net_debt=0.0, rev_b=4.035,
 wl="fcf-plus-plus-growth", tier="Low", themes=["medical-devices"],
 extras=[
   "$1.10B cash, no debt (net cash, p_fail ~0); ~71.3M shares; ~$200M buyback active",
   "Revenue $4.035B FY25 (+1%, flat-lining); GAAP op margin compressed to 13.5% (non-GAAP ~21%); FCF ~$0.5B; ~70% gross margin",
   "~$175, YTD ~+7-8%, 52-wk $122-$208 - deeply de-rated from the 2021 ~$700 peak (fwd P/E ~15)"],
 cq="Does clear-aligner category growth and Invisalign share retention outrun ASP/share erosion from Angelalign and at-home commoditization in a discretionary big-ticket product?",
 thesis="Align trades at ~$12.5B (~$174.84, deeply de-rated from the 2021 ~$700 peak to a ~+7-8% YTD ~$175) - ~25x FCF on $4.04B revenue growing low-single-digit, ~70% gross margin, net cash and a buyback. It is the category-defining clear-aligner brand (Invisalign + iTero) in a market still only ~15-20% penetrated, but growth has flat-lined (+1%) as discretionary demand softens and Angelalign/at-home rivals pressure ASPs (-1 to -2% guided). The mature DCF asks whether category penetration plus the teen/Palatal-Expander TAM outrun price/share erosion. The weighted finding lands ~fair (-1.5%): the modal case is +1%, essentially at spot - de-rated, but not cheap.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[4.0,3.7,3.9,4.0,4.04]),
   ("history_op_margin",[24.7,17.2,16.7,15.2,13.5]),
   ("history_fcf",[0.8,0.3,0.6,0.6,0.5]),
   ("history_ev_rev",[13,6,5,4,3.1])],
 p3cfg=[("segment_a","Clear Aligner"),("segment_b","Systems & Services (iTero)"),
   ("hist_ent_split",[0.83,0.82,0.82,0.82,0.85]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  Q1 FY2026 (Apr 2026) results",
 sources="Sources: SEC XBRL company facts (CIK 1097149; revenue, GAAP operating income/margin, cash flow, debt), Align Q1 FY2026 release (revenue $1,040M/+6.2%, Clear Aligner $856M, iTero/Systems $184M, record 686,000 Invisalign cases/+6.7%, gross margin 70.8%, FCF $120M, FY26 ASPs guided -1 to -2%). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/FCF & EV/sales vs medtech/dental peers (SmileDirect [defunct], Dentsply, Straumann, Angelalign).",
 ipo="IPO Jan '01", xmin=-5.5,
 points=[[-5.5,300],[-5.0,550],[-4.2,650],[-3.3,200],[-2.5,300],[-1.5,250],[-0.8,200],[-0.3,170],[-0.05,174.84]],
 scn={
  "ultra_bear":dict(p=0.14,g=[0.00,0.01,0.02,0.02,0.02],fcfm=[0.10,0.10,0.11,0.11,0.11],opm=[0.11,0.11,0.12,0.12,0.12],wacc=0.100,tg=0.020,fs=71,evr=[2,1.8,1.7,1.6,1.5],evf=[13,13,13,13,13],
    hl="Demand stalls; ASP/share erode.",
    narr=["The discretionary big-ticket consumer stays soft and Angelalign/at-home commoditization wins on price: case volume flat-lines, ASPs keep falling beyond the guided -1 to -2%, and a richer low-cost mix de-levers a ~70% gross margin into low-double-digit operating margins. Revenue is essentially flat; the category-penetration story stalls while share leaks.","A category leader whose volume and price are both pressured earns a low-growth ~13x terminal multiple -> DCF ~$92 (-47%). Net cash sets a floor but can't offset a stalled top line and a margin that keeps grinding lower."],
    pr="The genuine bear: revenue is already flat (+1% FY25), op margin has slid four straight years (24.7%->13.5%), ASPs are guided down, and Angelalign is suing on patents while taking China share. 14% weight on price/share erosion beating category growth."),
  "bear":dict(p=0.27,g=[0.03,0.04,0.04,0.04,0.04],fcfm=[0.11,0.12,0.12,0.13,0.13],opm=[0.13,0.14,0.14,0.15,0.15],wacc=0.095,tg=0.025,fs=70,evr=[2.5,2.4,2.3,2.2,2.1],evf=[15,15,15,15,15],
    hl="Low-single-digit grind; ASP pressure caps it.",
    narr=["Category penetration keeps volume rising but ASP/mix erosion and a competitive market hold growth to ~4% and margins below the historical peak. Invisalign defends its lead without re-accelerating; teen/IPE helps at the edges but doesn't change the trajectory. Revenue compounds ~4% at a low-teens FCF margin.","DCF ~$129 (-26%) - a defended-but-decelerating franchise at ~15x FCF is worth below today's price; the market's discount is warranted if growth stays mid-single-digit and ASPs keep slipping."],
    pr="Share retention continues but the discretionary backdrop + ASP pressure + Chinese competition cap the multiple. 27% as the plausible 'holds the lead but doesn't convert to growth' path, consistent with the flat top line and guided ASP declines."),
  "base":dict(p=0.34,g=[0.06,0.07,0.07,0.07,0.06],fcfm=[0.12,0.13,0.14,0.14,0.15],opm=[0.14,0.15,0.16,0.17,0.18],wacc=0.090,tg=0.025,fs=69,evr=[3,2.9,2.8,2.7,2.6],evf=[17,16,16,16,16],
    hl="Category penetration resumes; margin firms.",
    narr=["The modal path: clear-aligner penetration of the ~15-20%-penetrated ortho market resumes mid-single-digit case growth, the teen/Palatal-Expander TAM adds incremental volume, and iTero Lumina anchors the installed base - blending to ~7% revenue growth at a firming ~16-18% operating margin as ASP pressure is offset by volume. Revenue compounds ~7% toward ~$5.5B.","DCF ~$177 (+1%) - essentially at spot. A category-defining brand with a long penetration runway is genuinely valuable, but at ~16x FCF and mid-single-digit growth the modal case only recovers to about today's price; the de-rate corrected the 2021 excess to fair, not to a bargain."],
    pr="Requires penetration-led case growth + the teen/IPE TAM to offset ASP erosion - consistent with the record Q1 case volume (686,000/+6.7%) and reaffirmed guidance, but not a step-change re-acceleration. 34% as the central, near-fair outcome."),
  "bull":dict(p=0.17,g=[0.08,0.09,0.09,0.08,0.08],fcfm=[0.13,0.14,0.15,0.16,0.16],opm=[0.16,0.17,0.18,0.19,0.20],wacc=0.085,tg=0.030,fs=68,evr=[3.5,3.4,3.3,3.2,3.1],evf=[20,19,19,19,19],
    hl="Teen/IPE TAM expands; share holds.",
    narr=["Clear-aligner category penetration accelerates and the teen/Palatal-Expander launch opens the larger teen ortho TAM (the majority of global case-starts), while Invisalign holds share through patents + the iTero installed base. Volume growth and operating leverage push margins back toward 20%. Revenue compounds ~8-9%.","DCF ~$237 (+35%) - if the penetration + teen-TAM engine re-accelerates and ASPs stabilize, the de-rated entry re-rates with the fundamentals; this is the core of the bull."],
    pr="The IPE clearance + record teen case volume + a still-underpenetrated category make a genuine re-acceleration credible. ~17% weight on the TAM expansion landing while share holds."),
  "ultra_bull":dict(p=0.08,g=[0.10,0.11,0.10,0.10,0.09],fcfm=[0.14,0.15,0.16,0.17,0.18],opm=[0.17,0.18,0.20,0.21,0.22],wacc=0.082,tg=0.030,fs=67,evr=[4,3.9,3.7,3.6,3.5],evf=[22,21,20,20,20],
    hl="Category compounds; Invisalign re-rates.",
    narr=["The full second act: clear aligners take a decisive share of the global ortho market, teen/IPE becomes a durable growth leg, iTero scan-data + AI deepen the cornered resource, and Align re-rates to a high-quality medtech compounder at ~70% gross margin. Revenue compounds ~10% to peak margins.","DCF ~$301 (+72%) - the brand reclaims a premium medtech multiple as category growth + share defense + margin recovery all land; ~8% probability, the asymmetric upside the depressed entry is buying."],
    pr="Everything works - penetration AND the teen/IPE TAM AND share defense AND a margin/multiple re-rate, the high-quality-compounder outcome. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 14%","Demand stalls; ASP/share erode; ~$92 (-47%)."),
     ("Bear 27%","Low-single-digit grind; ASP pressure caps it; ~$129 (-26%)."),
     ("Base 34%","Category penetration resumes; margin firms; ~$177 (+1%)."),
     ("Bull 17%","Teen/IPE TAM expands; share holds; ~$237 (+35%)."),
     ("Ultra Bull 8%","Category compounds; Invisalign re-rates; ~$301 (+72%).")],
 pb=[("The de-rate corrected an excess, it didn't create a bargain.","Down ~75% from the 2021 ~$700 peak looks cheap, but at ~25x FCF and low-single-digit growth the modal DCF is +1% - decelerating growth, not the multiple alone, is the constraint."),
     ("The category is still only ~15-20% penetrated.","Clear aligners are early in displacing wires/brackets; teen/IPE opens the larger teen ortho TAM - a long runway the flat recent top line masks."),
     ("Brand + installed base are the moat.","Invisalign is the category-defining brand; iTero (>125,000 scanners) + accumulated scan-data + the patent estate are the hardest things for Angelalign/at-home to replicate."),
     ("ASP/share erosion is the whole question.","ASPs guided -1 to -2%, Angelalign taking China share and litigating patents, at-home/DIY at the low end - the gap between 'category grows' and 'Align's revenue grows' is the bull/bear fork."),
     ("Net cash, p_fail ~0.","$1.10B cash, no debt, ~$200M buyback active - no solvency risk; the downside is growth/multiple, not survival.")],
 tr=[("Bull validation","Invisalign case volume re-accelerates above ~+7%  ·  teen/IPE case-starts scale materially  ·  ASPs stabilize (not down)  ·  operating margin recovers back toward ~20%"),
     ("Bear validation","case volume flat-lines or declines for 2+ quarters  ·  ASPs fall faster than the guided -1 to -2%  ·  Angelalign/at-home take visible share  ·  op margin grinds below ~13%"),
     ("Reframe needed","if clear aligners commoditize (Angelalign wins on price + the ITC/patent actions fail), the branding + cornered-resource Powers erode - re-rate the terminal toward a low-growth, price-taking dental-device multiple")],
 gloss=[("Clear Aligner","Align's largest segment (~82-85% of revenue) - Invisalign removable aligners that displace traditional wires/brackets; case volume x ASP is the swing factor."),
        ("iTero / Systems & Services","Intraoral scanners (iTero Lumina, installed base >125,000) + software/services - the cornered-resource installed base that feeds Invisalign workflow and scan-data."),
        ("ASP","Average selling price per case; guided -1 to -2% in FY26 on country/product mix and competition - the price half of the volume-vs-price erosion question."),
        ("IPE (Invisalign Palatal Expander)","US-FDA-cleared device targeting teen/kids case-starts (the majority of global ortho) - the TAM-expansion lever in the bull."),
        ("FCF margin","Free cash flow / revenue (~12-13% FY25); the mature-DCF lever - whether category growth converts the ~70% gross margin to free cash flow as ASP pressure bites.")],
 arena="Clear-aligner orthodontics / dental devices - Align Technology (Invisalign, the category-defining brand, + iTero scanners) vs Angelalign, SmileDirect-style at-home/DIY, Dentsply Sirona, Straumann/ClearCorrect, and traditional wires/brackets; auditing a brand + cornered-resource Power against commoditization and a discretionary-demand market.",
 powers=[("scale_economies",3,"Largest clear-aligner manufacturer; manufacturing/R&D/sales leverage at $4B revenue and ~70% gross margin - real, but Angelalign is scaling fast in China."),
         ("network_economies",2,"Invisalign-trained doctor base + iTero/exocad workflow create two-sided pull (more doctors -> more patients), but not a hard network effect."),
         ("counter_positioning",1,"Was the disruptor of wires/brackets; now the incumbent being counter-positioned by lower-cost Angelalign and at-home/DIY models."),
         ("switching_costs",2,"Doctors invested in iTero hardware + Invisalign training face friction switching systems; patient-side switching is low (a single discretionary purchase)."),
         ("branding",4,"The dominant Power: Invisalign is the category-defining consumer brand with pricing power and direct-to-consumer demand pull - but eroding at the ASP line under competition."),
         ("cornered_resource",3,"iTero installed base (>125,000), accumulated scan-data, and a deep patent estate (the basis of the Angelalign suits/ITC action) - durable, the hardest piece to replicate."),
         ("process_power",2,"Mass-customization manufacturing + the digital treatment-planning stack; a real learning curve, modest as a standalone Power.")],
 dom="branding", dur="medium",
 rivals=[("Angelalign","public","Fast-growing Chinese clear-aligner challenger; competes on price, taking China share - the live patent/ITC threat.",0.30,0.25,"HK-listed"),
         ("Dentsply Sirona","public","Diversified dental incumbent (incl. SureSmile aligners + imaging); the legacy-dental comp.",0.0,0.10,"~12x EV/EBITDA"),
         ("Straumann / ClearCorrect","public","Premium dental/implant group with a growing aligner line; the high-end aligner challenger.",0.10,0.25,"~30x P/E"),
         ("At-home / DIY (SmileDirect legacy)","private","Direct-to-consumer aligners at the low end; SmileDirect went bankrupt, but the price-competitive segment persists.",None,None,"private")],
 threats=[("branding","Angelalign + at-home/DIY (price competition)","ASPs fall faster than the guided -1 to -2% as the brand premium erodes against lower-cost aligners."),
          ("cornered_resource","Angelalign (patents / ITC)","The patent suits + ITC import-block action fail, letting competitors replicate the technology and scan-data edge."),
          ("scale_economies","Discretionary-demand softness + China bulk-procurement","Case volume flat-lines or declines and a low-cost mix de-levers the ~70% gross margin below ~13% operating margin.")],
 take="Align's brand Power is genuine - Invisalign is the category-defining clear-aligner name with pricing power and consumer demand pull, reinforced by the iTero installed base and patent estate as a cornered resource - but the franchise is decelerating: revenue is flat (+1%), op margin has slid four straight years to 13.5%, and ASPs are guided down under Angelalign + at-home price competition. The Audit: branding is durable (medium) but eroding at the price line; the cornered resource (iTero/scan-data/patents) is the real defense, and the live threats are commoditization + a discretionary-demand market. The ~75% de-rate from the 2021 peak corrected the prior excess to roughly fair, not to a bargain; the DCF tests whether category penetration + the teen/IPE TAM outrun ASP/share erosion, and the modal case lands +1% - de-rated, but priced about right.",
)

if __name__ == "__main__":
    build(SPEC)
