#!/usr/bin/env python3
"""GOOGL — Alphabet (NASDAQ) mature-company memo spec. Emits data/_intake/googl.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1652044)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="GOOGL", company="Alphabet", exch="NASDAQ", spot=359.68,
 cap=4348.0, sh=12088.0, cash=126.8, net_debt=48.5, rev_b=402.8,
 wl="fcf-megacap", tier=None, themes=["platform-marketplace-tech","ai-compute"],
 extras=[
   "$126.8B cash vs $48.5B debt (~$78.3B net cash); ~12.09B shares (Class A+B+C), buyback + a small dividend",
   "Revenue $402.8B FY25 (+15%); GAAP op margin 32.0%; FCF $73.3B; capex ~$91B and guided to ~$190B in FY26",
   "Up ~28% YTD and ~130-160% TTM to ~$360 / ~$4.35T cap; ATH close $402.38 (May-2026), re-rated on owning the full AI stack"],
 cq="Does Alphabet's full AI stack (TPUs->Gemini->Cloud->apps) defend and monetize Search faster than generative-AI assistants erode its query and ad economics?",
 thesis="Alphabet trades at ~$4.35T (~$360, +28% YTD and ~130-160% TTM) - roughly 60x EV/FCF on $402.8B revenue growing ~15%, 32% operating margins, net cash, $73.3B FCF before a capex ramp to ~$190B. Cloud just re-accelerated to +63% with a ~$462B backlog and the AI stack re-rated the name, but Search is still ~60%+ of revenue and the price embeds the win. The DCF asks whether Search holds its economics through the generative-AI shift while Cloud compounds. The finding lands -21.4% (weighted ~$286): the modal base sits right at spot, so the run priced in the franchise and then some.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[257.6,282.8,307.4,350.0,402.8]),
   ("history_op_margin",[30.6,26.5,27.4,32.1,32.0]),
   ("history_fcf",[67.0,60.0,69.5,72.8,73.3]),
   ("history_ev_rev",[7.4,4.1,5.7,6.6,8.0])],
 p3cfg=[("segment_a","Search + YouTube"),("segment_b","Cloud"),
   ("hist_ent_split",[0.92,0.91,0.90,0.88,0.86]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec  ·  Q1 2026 results",
 sources="Sources: SEC XBRL company facts (CIK 1652044; revenue, GAAP operating income/margin, cash flow, debt), Alphabet Q1 2026 release (revenue $109.9B/+22%, op margin 36.1%, Search & other +19% to $60.4B, Cloud +63% to $20.0B at 32.9% margin, backlog ~$462B, FY26 capex guided ~$190B). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs mega-cap platform peers (MSFT/META/AMZN).",
 ipo="IPO Aug '04", xmin=-6.2,
 points=[[-6.0,70],[-5.0,145],[-4.0,90],[-3.0,100],[-2.0,140],[-1.0,200],[-0.5,280],[-0.1,402],[-0.02,359.68]],
 scn={
  "ultra_bear":dict(p=0.13,g=[0.08,0.06,0.04,0.03,0.03],fcfm=[0.15,0.15,0.16,0.17,0.17],opm=[0.28,0.28,0.29,0.29,0.30],wacc=0.09,tg=0.025,fs=12100,evr=[4,3.5,3,2.8,2.6],evf=[18,16,16,16,16],
    hl="AI assistants gut Search economics.",
    narr=["Generative-AI assistants take real query share and lower ad load: Search growth stalls toward low-single-digit, AI Overviews monetize below legacy CPCs, and the ~$190B capex ramp lands while revenue decelerates - so FCF margin sinks to ~15-17% off the ~18% base. Cloud keeps growing but can't offset a structurally impaired core.","A franchise whose primary cash engine is being disrupted earns a low-growth, ~16x terminal multiple -> DCF ~$104 (-71%). The net cash sets a floor but can't offset a Search that loses its economics while capex stays committed."],
    pr="The genuine bear: Search is ~60%+ of revenue, the capex commitment is now ~$190B and 'significantly higher' in 2027, and chatbots are a live substitution threat. 13% weight on the AI shift impairing the core."),
  "bear":dict(p=0.25,g=[0.13,0.11,0.09,0.08,0.07],fcfm=[0.17,0.18,0.19,0.20,0.20],opm=[0.30,0.30,0.31,0.31,0.32],wacc=0.085,tg=0.03,fs=12050,evr=[5,4.5,4,3.8,3.6],evf=[22,20,19,19,19],
    hl="Search slows; capex caps returns.",
    narr=["Search defends volume but ad load and CPCs drift lower as queries route through AI surfaces, growth decelerates to high-single-digit, and the capex ramp holds FCF margin near 18-20% even as Cloud scales. The AI stack works but the blended economics are lower than the past decade's.","DCF ~$171 (-52%) - a still-dominant platform that grows slower and converts less of revenue to free cash flow at ~19x FCF is worth well below today's price; the post-run multiple already prices the win."],
    pr="Search holds share but the shift compresses ad economics while ~$190B capex weighs on returns - the plausible 'defends but de-rates' path. 25% given the antitrust overhang and the capex trajectory."),
  "base":dict(p=0.34,g=[0.18,0.15,0.13,0.11,0.10],fcfm=[0.19,0.20,0.22,0.23,0.24],opm=[0.32,0.32,0.33,0.34,0.34],wacc=0.08,tg=0.035,fs=12000,evr=[6,5.5,5,4.8,4.6],evf=[26,24,23,23,23],
    hl="Search defends; Cloud compounds.",
    narr=["The modal path: Search defends and monetizes the AI transition at roughly parity (Q1'26's +19% argues defense is winning), Cloud keeps compounding off the ~$462B backlog with expanding margins, and FCF margin recovers from the capex trough toward ~24% as the ~$190B spend builds capacity that fills. Revenue compounds low-double-digit to ~$680B.","DCF ~$286 (-20%) - the modal case lands right at spot. A franchise growing low-double-digit at a recovering ~24% FCF margin and a ~23x multiple is worth about today's price; the 2026 run priced the franchise in, leaving little margin of safety at the modal outcome."],
    pr="Requires Search to monetize AI at near-parity and Cloud to keep compounding while capex stays productive - consistent with Q1'26 (Search +19%, Cloud +63%, margin doubling). 34% as the central, near-spot outcome."),
  "bull":dict(p=0.20,g=[0.21,0.18,0.16,0.14,0.12],fcfm=[0.20,0.22,0.24,0.26,0.27],opm=[0.33,0.34,0.35,0.36,0.36],wacc=0.078,tg=0.04,fs=11900,evr=[7,6.5,6,5.8,5.6],evf=[30,28,27,27,27],
    hl="AI stack compounds; Cloud re-rates.",
    narr=["The full stack pays off: TPUs lower the cost of serving Gemini, Cloud sustains hyper-growth and operating leverage off the backlog, AI Mode/Overviews lift Search monetization above legacy rates, and FCF margin climbs toward ~27% once the capex wave is absorbed. Revenue compounds mid-teens to ~$730B.","DCF ~$423 (+18%) - if Search not only defends but Cloud + the AI stack compound into a second profit engine, the franchise is worth meaningfully above spot at a ~27x multiple; this is the bull the re-rating is paying for."],
    pr="Cloud's +63% and doubling margin plus a defended, AI-monetized Search make a genuine compounding case credible. 20% weight on the full AI stack delivering on both legs."),
  "ultra_bull":dict(p=0.08,g=[0.24,0.21,0.19,0.16,0.14],fcfm=[0.21,0.24,0.26,0.28,0.29],opm=[0.34,0.35,0.36,0.37,0.37],wacc=0.075,tg=0.04,fs=11800,evr=[8,7.5,7,6.8,6.6],evf=[32,30,30,30,30],
    hl="Full-stack AI platform; multiple re-rates.",
    narr=["Everything compounds: Gemini + AI Mode expand Search economics, Cloud becomes a durable second franchise at scale, Waymo and the model/TPU stack add optionality, and FCF margin reaches ~29% as the capex cycle turns into high-return capacity. Revenue compounds high-teens to ~$790B.","DCF ~$553 (+54%) - Alphabet re-rates as the broadest full-stack AI platform; ~8% probability, the asymmetric upside that owning chips through apps could deliver."],
    pr="Everything works - Search monetizes AI above parity AND Cloud compounds AND TPUs/Gemini/Waymo add value AND the multiple holds. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 13%","AI assistants erode Search economics; ~$104 (-71%)."),
     ("Bear 25%","Search slows; capex caps returns; ~$171 (-52%)."),
     ("Base 34%","Search defends; Cloud compounds; ~$286 (-20%)."),
     ("Bull 20%","AI stack compounds; Cloud re-rates; ~$423 (+18%)."),
     ("Ultra Bull 8%","Full-stack AI platform re-rates; ~$553 (+54%).")],
 pb=[("The run priced the franchise in.","After +28% YTD / ~130-160% TTM the name is ~60x EV/FCF and the modal DCF is ~-20% - the AI stack is real, but the price already embeds the win, leaving thin margin of safety."),
     ("Cloud at +63% with doubling margins is the new engine.","Cloud hit $20.0B/+63% at 32.9% operating margin (from 17.8%) with a ~$462B backlog ~2x QoQ - a credible second franchise that the bull/ultra-bull cases lean on."),
     ("Search defense is winning so far.","Q1'26 Search & other still grew +19% to $60.4B with AI Overviews at 2.5B MAU monetizing near parity - the central bear (query/CPC leakage) is not yet visible in the numbers."),
     ("The ~$190B capex is the FCF swing.","Capex guided to ~$190B FY26 and higher in 2027 crushes near-term FCF; the bull needs that spend to convert to high-return Cloud/AI capacity, the bear sees it cap returns."),
     ("Antitrust is the unpriced tail.","The DOJ search remedy (no Chrome divestiture, but default bans + data-sharing, on appeal to the D.C. Circuit) and a pending ad-tech remedy that could force an AdX/DFP divestiture sit outside the DCF.")],
 tr=[("Bull validation","Cloud growth holds >40% with margin above 30%  ·  Search & other stays >+15% as AI Overviews/AI Mode monetize  ·  FCF margin recovers above ~22% as capex is absorbed  ·  backlog keeps building"),
     ("Bear validation","Search & other decelerates toward low-single-digit or CPCs fall  ·  FCF margin stays below ~18% as ~$190B+ capex outruns cash  ·  Cloud growth/margin rolls over  ·  an adverse ad-tech (AdX/DFP) divestiture remedy"),
     ("Reframe needed","if generative-AI assistants take durable query share and ad load drops, the ~60%-of-revenue Search engine loses its economics - re-rate the terminal toward a slower-growth, lower-FCF-margin platform")],
 gloss=[("Search & other","Alphabet's core search-advertising revenue (~$60.4B in Q1'26, ~60%+ of total); the swing-factor segment the generative-AI shift threatens or that Gemini/AI Overviews defend."),
        ("Google Cloud","The cloud-infrastructure + Workspace segment ($20.0B/+63% in Q1'26 at ~33% operating margin, ~$462B backlog) - the second engine the bull case compounds."),
        ("AI Overviews / AI Mode","Gemini-powered answers atop Search (2.5B / 1B MAU) monetizing roughly at Search-parity rates - the mechanism by which Google defends ad economics through the AI transition."),
        ("TPU","Tensor Processing Unit - Google's custom AI accelerator; the cornered-resource that lets it train/serve Gemini and offer Cloud AI at lower cost than buying merchant silicon."),
        ("FCF margin","Free cash flow / revenue (~18% FY25, depressed by the capex ramp); the mature-DCF lever - whether ~$190B capex converts to high-return capacity and FCF margin recovers toward ~24%.")],
 arena="Search + digital advertising and cloud/AI infrastructure - Alphabet (Search, YouTube, Cloud, the TPU->Gemini->apps stack) vs Microsoft/OpenAI, Amazon, Meta, and chatbot challengers; auditing entrenched network/scale/cornered-resource Powers against a generative-AI substitution and a live antitrust threat.",
 powers=[("scale_economies",4,"Massive fixed-cost leverage across the index, ad systems, YouTube, and global data centers; 32% operating margin at $403B revenue - few can match the spend per query."),
         ("network_economies",4,"Search's two-sided advertiser/user loop, YouTube's creator/viewer flywheel, and Android/Play ecosystems - more users sharpen results and pricing, a genuine network Power."),
         ("counter_positioning",1,"The incumbent now being counter-positioned by AI-native assistants (ChatGPT), not the disruptor; AI Overviews is a defensive retrofit, not counter-positioning."),
         ("switching_costs",3,"Workspace/Cloud contracts and the ~$462B backlog lock enterprises in; consumer Search switching is low, but Android/Chrome/account defaults raise friction."),
         ("branding",3,"'Google' is a verb and a default trust signal, but brand alone won't hold queries if an assistant answers better - durable yet not the binding Power."),
         ("cornered_resource",4,"The crawl index, decades of query/click data, custom TPUs, and frontier Gemini models - assets rivals cannot quickly replicate; the data + silicon edge is the deepest moat."),
         ("process_power",2,"Deep ML/infra engineering capability, but increasingly a contested field rather than a unique repeatable process.")],
 dom="network_economies", dur="high",
 rivals=[("Microsoft / OpenAI","public","Azure + Copilot + OpenAI partnership attack both Cloud and Search via AI assistants; the primary full-stack rival.",0.16,0.45,"~35x P/E"),
         ("Amazon (AWS)","public","Cloud market leader; the EV/FCF and Cloud-growth benchmark Alphabet's Cloud is measured against.",0.15,0.11,"~30x EV/FCF"),
         ("Meta Platforms","public","Ad-budget rival and AI-compute peer; competes for advertiser dollars and AI talent/capex.",0.20,0.41,"~24x EV/FCF"),
         ("OpenAI / Anthropic","private","Frontier-model labs whose assistants are the direct generative-AI substitution threat to Search query volume.",None,None,"private")],
 threats=[("network_economies","ChatGPT / AI-native assistants","Search & other growth decelerates toward low-single-digit or query volume visibly leaks to chatbots, breaking the user/advertiser loop."),
          ("cornered_resource","Frontier labs + merchant silicon (NVIDIA)","Rivals match Gemini quality and serving cost, eroding the data/TPU advantage as a differentiator."),
          ("scale_economies","DOJ / ad-tech antitrust remedy","An adverse ad-tech ruling forces an AdX/DFP divestiture or default-distribution bans dent Search's scale and reach.")],
 take="Alphabet's network and scale Powers are deeply entrenched - a two-sided Search/advertiser loop, YouTube's flywheel, and a cornered-resource stack (index, query data, custom TPUs, Gemini) few rivals can replicate. The Audit: network_economies is durable (high); the live threats are generative-AI assistants substituting for ~60%+-of-revenue Search and an antitrust overhang (DOJ search appeal, a pending ad-tech divestiture) the DCF doesn't price. Q1'26 (Search +19%, Cloud +63%) says the defense is winning - but the ~28% YTD run re-rated the name to ~60x EV/FCF, so the modal case lands at spot: -21.4%, a durable franchise priced for the win.",
)

if __name__ == "__main__":
    build(SPEC)
