#!/usr/bin/env python3
"""TOST — Toast, Inc. (NYSE) mature-company memo spec. Emits data/_intake/tost.yml
via the reusable Batch-B builder (gen_b1.build). Numerics modeled in model_mature;
op-margin history is GAAP (us-gaap:OperatingIncomeLoss / revenue) from SEC XBRL (CIK 1650164)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="TOST", company="Toast, Inc.", exch="NYSE", spot=24.82, cap=14.44, sh=582.0, cash=1.353, net_debt=0.0, rev_b=6.153,
 wl="fun-speculative", tier="Med", themes=["platform-marketplace-tech","digital-assets-fintech-rails"],
 extras=[
   "Net cash +$1.35B ($1.353B cash, no debt); ~582M shares; SBC ~11% of recurring gross profit is the dilution to watch",
   "Revenue $6.15B FY25 (+23%); GAAP op margin inflected to 4.7% (21% in Q1'26); FCF ~$0.6B; net income $342M (vs $19M FY24)",
   "~$25, down ~29% YTD / ~40% TTM, near the 52-week low ($22.26-$49.66)"],
 cq="Did Toast's ~40% de-rate near the lows misprice a proven operating-leverage inflection — or is it priced for location growth and a payments take-rate that competition compresses?",
 thesis="Toast trades at ~$14.4B (~$24.82, down ~40% TTM, near the 52-week low) — ~2.1x EV/sales on $6.15B revenue growing ~23%, net cash, with a proven margin inflection (GAAP op margin -7% -> 0.3% -> 4.7%, and 21% last quarter). The bull is durable ~20% location growth (171k of 875k+ US restaurants) plus attach (Capital, marketing) lifting ARPU and take rate; the bear is payments take-rate compression and SMB cyclicality against Block/Square, Olo and Shift4. The DCF asks whether the location runway and the inflection compound — the modal case lands +24%, so the de-rate looks like it overshot a real inflection.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[1.7,2.7,3.9,5.0,6.15]),
   ("history_op_margin",[-13.4,-14.1,-7.4,0.3,4.7]),
   ("history_fcf",[-0.0,-0.2,0.1,0.3,0.6]),
   ("history_ev_rev",[8,4,3,2.5,2.1])],
 p3cfg=[("segment_a","Fintech (payments)"),("segment_b","Subscription (SaaS)"),
   ("hist_ent_split",[0.82,0.83,0.83,0.82,0.81]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  Q1 FY2026 results",
 sources="Sources: SEC XBRL company facts (CIK 1650164; revenue, GAAP operating income/margin, cash flow, debt), Toast Q1 FY2026 release (ARR $2.2B/+26%, GPV $51.3B/+22%, 171,000 live locations/+22%, GAAP op margin ~21%, adj EBITDA $179M/34% margin, SaaS gross margin 81%, fintech/payments ~80%+ of revenue). Revenue modeled as a growth-rate path off FY25; FCF margin is modeled on TOTAL (payments-heavy) revenue, so it reads low (~6-11%) - read it ex-SBC owner FCF on recurring gross profit, net of ~11% SBC dilution. Gordon terminal at scenario WACC. EV/sales & EV/FCF vs Block/Square, Olo, Shift4, Fiserv (Clover).",
 ipo="IPO Sep '21", xmin=-4.5,
 points=[[-4.5,40],[-4.0,20],[-3.3,14],[-2.5,22],[-1.5,38],[-0.8,46],[-0.3,30],[-0.05,24.82]],
 scn={
  "ultra_bear":dict(p=0.14,g=[0.06,0.05,0.04,0.04,0.04],fcfm=[0.04,0.05,0.05,0.06,0.06],opm=[0.04,0.05,0.06,0.06,0.07],wacc=0.110,tg=0.030,fs=595,evr=[1.5,1.3,1.2,1.1,1.0],evf=[14,13,13,13,13],
    hl="Take-rate compresses; growth stalls.",
    narr=["Competition does its worst: Block/Square and Clover undercut payments pricing, the take rate on $51B+ of GPV compresses, and SMB churn rises through a restaurant-spending downturn. Location adds decelerate toward mid-single-digit, the margin inflection stalls near today's level, and revenue compounds only ~4-5%.","A payments-heavy platform whose take rate erodes while growth fades earns a low EV/sales (~1.0-1.5x) and a ~13x terminal FCF multiple -> DCF ~$10 (-58%). Net cash sets a floor; a compressed, slowing fintech book can't support more."],
    pr="The genuine bear: payments is ~80% of revenue and the take rate is the contested battleground (Block/Square, Clover, Shift4), restaurants are cyclical SMBs, and the ~37x P/E left little safety margin before the de-rate. 14% on take-rate compression plus a soft cycle."),
  "bear":dict(p=0.27,g=[0.12,0.10,0.08,0.07,0.06],fcfm=[0.05,0.06,0.07,0.08,0.08],opm=[0.06,0.07,0.08,0.09,0.10],wacc=0.100,tg=0.035,fs=590,evr=[1.8,1.6,1.5,1.4,1.3],evf=[17,16,16,16,16],
    hl="Locations grow; margins inflect slowly.",
    narr=["Locations keep growing but adds slow to ~8-10% as the easy US share is taken and enterprise/international ramps gradually; the take rate holds but doesn't expand, and operating margin grinds up from the mid-single digits rather than stepping. Revenue compounds ~8% to ~$9B at a still-modest FCF margin.","DCF ~$18 (-27%) - a real franchise that grows but whose cash conversion lags its top line is worth below today's price; the market's discount is warranted if the inflection plateaus."],
    pr="Share gains continue but competition caps the take rate and the cycle softens SMB demand, so margins improve modestly rather than re-rating. 27% as the plausible 'grows but converts slowly' path."),
  "base":dict(p=0.34,g=[0.18,0.15,0.12,0.10,0.09],fcfm=[0.06,0.08,0.09,0.10,0.11],opm=[0.08,0.10,0.12,0.14,0.15],wacc=0.095,tg=0.035,fs=585,evr=[2.1,1.9,1.8,1.7,1.6],evf=[20,18,18,18,18],
    hl="Runway + leverage compound to ~15%.",
    narr=["The modal path: locations keep compounding low-double-digit toward a long US runway (171k of 875k+) with enterprise/international adding, the take rate holds as attach (Capital, marketing, ToastIQ) lifts ARPU, and operating leverage carries GAAP op margin from ~5% toward ~15%. Revenue compounds ~13% to ~$11B.","DCF ~$31 (+24%) - the proven inflection continues at a moderating pace and the de-rated entry re-rates with the fundamentals; the modal case clears today's price, so the crash looks like it overshot a real inflection rather than correcting an excess."],
    pr="Requires the location runway to continue and the demonstrated operating leverage to keep flowing through - consistent with the -7%->21% margin trajectory and the attach flywheel, not a step-change. 34% as the central outcome."),
  "bull":dict(p=0.17,g=[0.22,0.18,0.15,0.13,0.11],fcfm=[0.08,0.10,0.11,0.13,0.14],opm=[0.10,0.13,0.16,0.18,0.20],wacc=0.090,tg=0.040,fs=580,evr=[2.5,2.3,2.2,2.1,2.0],evf=[24,22,22,22,22],
    hl="Adds + take-rate + attach all compound.",
    narr=["Locations, take rate and attach compound together: ~20% location growth holds as enterprise/international scale (Q1 enterprise bookings already exceeded the prior-year customer count), Toast Capital and marketing/ads lift the take rate and ARPU, and operating margin inflects toward ~20% as SaaS (81% gross margin) carries the mix. Revenue compounds ~15% to ~$12.5B.","DCF ~$52 (+108%) - if the location runway, take rate and attach all compound, the de-rated entry re-rates hard with the fundamentals; this is the core of the bull."],
    pr="Toast's switching-cost Power (the embedded POS/payments operating system) plus the attach flywheel and a long location runway make a compounding-take-rate outcome credible. ~17% weight on adds and take rate compounding together."),
  "ultra_bull":dict(p=0.08,g=[0.26,0.22,0.18,0.15,0.13],fcfm=[0.09,0.11,0.13,0.15,0.16],opm=[0.12,0.15,0.18,0.21,0.23],wacc=0.088,tg=0.040,fs=575,evr=[2.8,2.6,2.5,2.4,2.3],evf=[26,24,24,24,24],
    hl="Restaurant OS; platform FCF machine.",
    narr=["The full second act: Toast becomes the default restaurant operating system, sustaining ~20%+ location growth deep into the US TAM and internationally, fintech attach (Capital, marketing, data/ToastIQ) compounds the take rate, and a nascent network/data effect widens the moat as operating margin marches toward ~23%. Revenue compounds ~18% to ~$14B and free cash flow scales.","DCF ~$69 (+180%) - the platform earns a software-and-payments compounder multiple; ~8% probability, the asymmetric upside the depressed entry is buying."],
    pr="Everything works - locations AND take rate AND attach AND international AND a data/network flywheel, the embedded-OS outcome. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 14%","Take-rate compresses, growth stalls; ~$10 (-58%)."),
     ("Bear 27%","Locations grow but margins inflect slowly; ~$18 (-27%)."),
     ("Base 34%","Runway + leverage compound to ~15%; ~$31 (+24%)."),
     ("Bull 17%","Adds + take-rate + attach all compound; ~$52 (+108%)."),
     ("Ultra Bull 8%","Restaurant OS, platform FCF machine; ~$69 (+180%).")],
 pb=[("The de-rate met a proven inflection, not a story.","GAAP op margin went -7% -> 0.3% -> 4.7% (21% last quarter) and adj EBITDA doubled to $633M FY25 - the operating leverage is demonstrated, so the ~40% TTM drop re-priced a real, improving business near the lows."),
     ("Payments is ~80% of revenue, so FCF margin reads low.","Modeled on TOTAL (payments-heavy) revenue, FCF margin looks like ~6-11%; read ex-SBC owner FCF on recurring gross profit (81% SaaS GM) net of ~11% SBC dilution - the take rate, not the headline margin, is the real lever."),
     ("The take rate is the whole question.","Payments competition (Block/Square, Clover, Shift4) is the live threat to the ~80% fintech book; attach - Capital, marketing/ads, ToastIQ - is the offset that lifts take rate and ARPU as Toast scales."),
     ("Location runway is long but the easy share thins.","171k of 875k+ US restaurants leaves a long runway, but US SMB adds get harder; enterprise/international (Q1 enterprise bookings exceeded the prior-year customer count) is the next leg the bull needs."),
     ("Net cash, p_fail ~0.","$1.35B cash, no debt, GAAP-profitable (net income $342M FY25) - no solvency risk; the downside is take-rate/multiple, not survival.")],
 tr=[("Bull validation","location adds hold ~20% (enterprise/international ramping)  ·  payments take rate stable-to-up as attach scales (Capital, marketing, ToastIQ)  ·  GAAP op margin sustains the inflection toward the teens  ·  ARR growth stays >=20%"),
     ("Bear validation","location adds decelerate below ~10%  ·  payments take rate compresses as Block/Clover/Shift4 undercut  ·  GAAP op margin stalls or reverses  ·  SMB churn rises through a restaurant-spending downturn"),
     ("Reframe needed","if the take rate compresses structurally or location growth falls below ~10% without enterprise/international offsetting, the runway shortens - re-rate the terminal toward a low-growth, price-competed payments processor multiple")],
 gloss=[("GPV","Gross Payment Volume - total payments processed across Toast restaurants (~$51.3B/quarter, +22%); the base the payments take rate is applied to, and the swing-factor's denominator."),
        ("Take rate","Fintech (payments) revenue as a fraction of GPV; ~80%+ of total revenue rides on it, so its durability against Block/Square/Clover competition is the central question."),
        ("ARR","Annualized recurring revenue (~$2.2B, +26%) - the SaaS subscription book (81% gross margin); the higher-margin leg whose mix-up is the margin-inflection lever."),
        ("Attach","Add-on products beyond core POS/payments - Toast Capital (lending), marketing/ads, ToastIQ - that lift ARPU and the effective take rate per location."),
        ("FCF margin","Free cash flow / revenue; modeled on TOTAL payments-heavy revenue so it reads ~6-11% - read ex-SBC owner FCF on recurring gross profit net of ~11% SBC dilution; the mature-DCF swing factor.")],
 arena="Restaurant commerce platforms (POS + payments + software) - Toast (171k live locations, $51B+ GPV, vertically-integrated hardware/SaaS/payments) vs Block/Square, Fiserv (Clover), Shift4, Olo, plus legacy POS (NCR/Aloha, Lightspeed); auditing an embedded switching-cost Power against payments take-rate competition.",
 powers=[("scale_economies",3,"Real and growing: $51B+ GPV and 171k locations give payments/sourcing/R&D leverage that funded the margin inflection, but Block/Fiserv process far more volume overall."),
         ("network_economies",1,"Nascent - data/ToastIQ across the restaurant base and supplier/marketplace links could compound, but it is early and not yet a durable network effect."),
         ("counter_positioning",2,"The vertically-integrated restaurant-specific stack (hardware + SaaS + payments) is awkward for horizontal processors (Block) and pure-SaaS (Olo) to copy without cannibalizing their model."),
         ("switching_costs",4,"The dominant Power: once Toast is the restaurant's POS, payments, payroll, online-ordering and capital operating system, ripping it out mid-service is costly and risky - high retention, the moat the take rate rides on."),
         ("branding",2,"A strong restaurant-category brand and reference base, but brand alone doesn't set the payments take rate."),
         ("cornered_resource",1,"The installed base and restaurant operating data are valuable, but not a truly cornered resource."),
         ("process_power",2,"Demonstrated operating-leverage execution (-7% -> 21% GAAP op margin, adj EBITDA doubled) and product velocity (Capital, marketing, ToastIQ); improving, not yet a structural process moat.")],
 dom="switching_costs", dur="high",
 rivals=[("Block / Square","public","Horizontal payments + Square for Restaurants; the primary payments take-rate competitor and pricing pressure.",0.10,0.10,"~3x EV/sales"),
         ("Fiserv (Clover)","public","Scaled processor with a fast-growing restaurant/SMB POS; the volume-and-distribution threat to the take rate.",0.07,0.30,"~14x P/E"),
         ("Olo","public","Restaurant ordering/digital SaaS; an attach/adjacency competitor and partner, asset-light vs Toast's payments model.",0.18,0.10,"~5x EV/sales"),
         ("Shift4","public","Payments-led restaurant/hospitality processor; a direct take-rate rival expanding in the vertical.",0.25,0.20,"~18x P/E")],
 threats=[("switching_costs","Block/Square, Clover, Shift4 underpricing payments","Payments take rate on GPV compresses as competitors undercut, eroding the ~80% fintech book even with retention holding."),
          ("scale_economies","Fiserv/Block volume + distribution","Location adds decelerate below ~10% as scaled processors win SMB share through bundling and price."),
          ("network_economies","Olo / data-platform entrants","ToastIQ/data and the attach flywheel fail to compound, leaving Toast a price-competed processor rather than an operating system.")],
 take="Toast's switching-cost Power is genuine and dominant - once it is the restaurant's POS, payments, payroll and ordering operating system, ripping it out mid-service is costly, which underpins high retention and the take rate the model rides on, supported by real scale (171k locations, $51B+ GPV). The Audit: switching_costs is durable (high), scale_economies funded a demonstrated margin inflection (-7% -> 21% GAAP op margin), and a network/data leg (ToastIQ) is nascent; the live threat is payments take-rate competition from Block/Square, Clover and Shift4 against an ~80%-payments revenue base. The ~40% TTM de-rate met that proven inflection, and the modal DCF lands +24% - the distribution says the sell-off overshot a real operating-leverage story, gated on the take rate holding as Toast scales.",
)

if __name__ == "__main__":
    build(SPEC)
