#!/usr/bin/env python3
"""PRME — Prime Medicine (NASDAQ) · YOUNG memo intake builder.
Numbers locked via /tmp/moon/model.py (auto-diluted); prose conviction-neutral.
Finding: weighted $3.39 vs spot $3.16 = +7.2% — distressed prime-editing option, ~fair (the anti-BEAM)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_young import build_young

def sc(p, rev, opm, wacc, tg, s2c, pf, dist, raises, rprices, dil, fs, tam, comp, hl, narr, pr):
    return dict(p=p, rev=rev, opm=opm, wacc=wacc, tg=tg, s2c=s2c, pf=pf, dist=dist, raises=raises,
                rprices=rprices, dil=dil, fs=fs, tam=tam, comp=comp, hl=hl, narr=narr, pr=pr)

SPEC = dict(
 ticker="PRME", company="Prime Medicine", exch="NASDAQ", spot=3.16,
 cap=0.57, sh=180.6, cash=0.149, net_debt=0.0, last_rev=0.02,
 extras=["~$149M cash = ~9-month runway; FY2025 10-K flags GOING-CONCERN doubt; $200M ATM",
         "Pre-product prime editing (search-and-replace; David Liu / Broad lineage); burn ~$43M/qtr",
         "PM359 first-ever clinical prime edit (NEJM Dec'25); May'25 restructuring -> in-vivo liver (Wilson/AATD)"],
 wl="asymmetrical-moonshots", tier="Low", themes=["precision-medicine-oncology"],
 cq="PRME proved the first-in-human prime edit, but holds only ~9 months of cash against a going-concern flag and a $200M ATM — does the platform tail survive the dilution before it pays off?",
 thesis="Prime Medicine is a clinical-stage prime-editing biotech — the precise 'search-and-replace' gene edit (no double-strand break), David Liu's sister technology to BEAM's base editing. Pre-revenue at $3.16 (~$585M cap), it proved the first-ever clinical prime edit (PM359, NEJM Dec 2025). But cash is ~$149M (~9 months), the FY2025 10-K flags going-concern doubt, and a $200M ATM means severe dilution at a ~$3 stock; a May 2025 restructuring refocused it on in-vivo liver (Wilson's, AATD). The DCF asks whether the platform tail can outrun forced dilution. Weighted fair value $3.39 vs $3.16 — roughly fair, an option where the platform almost exactly offsets the balance sheet.",
 tam_billion=30, hist_years=[2023, 2024, 2025], hist_rev=[0.01, 0.015, 0.005], hist_fleet=[0, 0, 0],
 p3cfg=[("peer_y", 32), ("peer_text", "Profitable biopharma op margin ~30-40%"), ("fleet_anchor", 0),
        ("fleet_title", "Revenue ramp (log)"), ("fleet_reference", None), ("valn_anchor_y", 5),
        ("valn_anchor_text", "Commercial biotech P/S ~4-6x"),
        ("valn_caption", "Pre-product: the ~$585M cap is pipeline value over a thin $149M cash floor."),
        ("tam_title", "$30B genetic-disease therapeutics — PRME share"),
        ("tam_legend", ["PRME", "Gene-editing rivals", "Other genetic medicine"])],
 subtitle="FY23-FY25 history + FY26-FY35 scenario projections  ·  fiscal years end Dec 31  ·  Q1'26 (May 2026) release",
 sources="Sources: PRME FY2025 10-K (going-concern) + Q1'26 results (CIK 1894562), PM359 CGD data (NEJM Dec 2025), May'25 restructuring, BMS/CFF agreements. Revenue is minimal collaboration income; product revenue modeled post-approval; raises auto-sized (the $200M ATM dilution path). FCF is NOL-shielded pre-tax over the explicit window. TAM: a serviceable slice of genetic-disease therapeutics, ~$30B.",
 ipo="IPO Oct '22", xmin=-3.7,
 points=[[-3.6, 17.0], [-3.0, 9.0], [-2.2, 5.0], [-1.5, 3.5], [-1.0, 2.2], [-0.5, 5.5], [-0.25, 4.0], [-0.05, 3.16]],
 wr=[
   ("Ultra Bear 16%", "Programs fail or cash runs out; ATM dilutes to the $0.40 floor."),
   ("Bear 30%", "One program limps; repeated raises at low prices overwhelm holders."),
   ("Base 30%", "A liver program clears + BMS pays, but ~$0.9B of raises nearly triples shares."),
   ("Bull 16%", "Multiple liver successes; milder dilution as proof lifts the financing price."),
   ("Ultra Bull 8%", "Prime editing wins broadly in-vivo; cleanest share count, platform terminal."),
 ],
 pb=[
   ("First-in-class proof is real", "PM359 restored NADPH-oxidase activity in the first-ever clinical prime edit (NEJM Dec 2025) — the core chemistry works in humans, not just in vitro."),
   ("Liver refocus de-risks delivery", "The May 2025 pivot to in-vivo liver (Wilson's, AATD) targets the best-validated delivery route, where LNP-to-liver is a solved problem for rivals."),
   ("Non-dilutive capital exists", "BMS ($55M upfront, $55M equity, >$3.5B milestones) and CFF (up to $39M) offset some burn — not every dollar of progress must come from the ATM."),
   ("The de-rating prices the distress", "At $3.16, down from a $6.94 high, much of the going-concern risk is already in the stock; the platform tail is being bought cheaply."),
   ("David Liu lineage", "The Broad-Institute prime-editing IP and scientific lead are a genuine cornered resource that a partner or acquirer could fund through the cash crunch."),
 ],
 tr=[
   ("Bull validation", "A partnered or approved liver program (Wilson's/AATD), a PM359 partner/BLA path, or a financing/partnership that closes the runway gap before the ATM is leaned on."),
   ("Bear validation", "Repeated ATM draws at sub-$3 prices, a clinical setback in the lead liver programs, or runway slipping below two quarters without a partner."),
   ("Reframe needed", "Insolvency, a recap, or a take-under would move this from 'distressed option' to 'broken' — re-underwrite from the floor, not the platform tail."),
 ],
 gloss=[
   ("prime editing", "Precise 'search-and-replace' gene edit that rewrites DNA without a double-strand break; makes many edit types. David Liu / Broad lineage."),
   ("PM359 / CGD", "PRME's program for chronic granulomatous disease; the first-ever clinical prime edit (NEJM Dec 2025). Deprioritized; now seeking a partner/BLA path."),
   ("in-vivo liver editing", "Editing genes directly inside the body in the liver — the focus after the May 2025 refocus (Wilson's disease PM577, AATD PM647)."),
   ("going-concern", "Auditor/management doubt, flagged in the FY2025 10-K, that the company has enough cash to operate for the next 12 months."),
   ("ATM / forced dilution", "An 'at-the-market' equity program ($200M here) that sells new shares into the open market; at a ~$3 stock it heavily dilutes existing holders."),
   ("p_fail", "Modeled probability the scenario ends in failure or insolvency before economics arrive — elevated here because surviving the cash crunch is itself uncertain."),
 ],
 competitive=dict(
   arena="In-vivo and ex-vivo precise gene editing for genetic disease, against base editors (BEAM), nuclease editors (Intellia, CRISPR Therapeutics) and editing platforms (Editas).",
   powers=[
     ("scale_economies", 1, "Sub-scale and cash-starved; forced to cut ~25% of staff and the pipeline in May 2025."),
     ("network_economies", 0, "No network effects in a therapeutics platform; value is clinical proof, not adoption density."),
     ("counter_positioning", 2, "Prime editing avoids double-strand breaks and makes edit types base editing cannot — a model rivals can't simply copy."),
     ("switching_costs", 1, "Switching costs accrue only post-approval, per indication; none yet with zero approved products."),
     ("branding", 0, "No commercial brand; pre-revenue clinical-stage with reputational, not pricing, recognition."),
     ("cornered_resource", 2, "David Liu / Broad prime-editing IP and know-how are a genuine scarce asset — but underfunded to exploit."),
     ("process_power", 1, "Editing-design and delivery know-how is real but early and not yet a durable manufacturing advantage."),
   ],
   dom="cornered_resource", window="closing",
   rivals=[
     ("BEAM (base editing)", "public", "Same gene-editing family; $1.21B cash vs PRME's $149M — far better capitalized.", 0.30, 0.30, "$1.21B cash, runway to ~2029"),
     ("Intellia / NTLA", "public", "In-vivo CRISPR nuclease editing; deeper clinical pipeline and balance sheet.", 0.25, 0.25, "well-funded, partnered"),
     ("CRISPR Therapeutics", "public", "Approved ex-vivo product (Casgevy) and substantial cash; nuclease leader.", 0.25, 0.20, "product revenue + large cash"),
     ("Editas Medicine", "public", "Editing platform peer; also capital-constrained and restructuring.", 0.10, 0.05, "constrained"),
   ],
   lead_lag=[
     ("Clinical first", "PM359 first-ever clinical prime edit (NEJM)", "Base/nuclease peers further in pivotal trials", "even"),
     ("Balance sheet", "~$149M / ~9 months / going-concern", "BEAM ~$1.21B / runway to ~2029", "lagging"),
     ("In-vivo delivery", "Refocused to liver, pre-clinical-readout", "NTLA/peers with in-vivo human data", "lagging"),
   ],
   take="PRME is trying to originate a cornered-resource/process Power in versatile, precise editing — the David Liu prime-editing platform is a genuine scarce asset, and PM359 proves the chemistry works in humans. But the company is cash-starved and was forced to cut its pipeline, so the Power-origination window is closing faster than the science is maturing. The falsifier the bull must clear is concrete — reach a partnered or approved program before the balance sheet forces value-destroying dilution. Same family as BEAM, opposite balance sheet.",
 ),
 scn={
  "ultra_bear": sc(0.16, [0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.10,0.11],
    [-7.0,-5.0,-3.5,-2.5,-1.8,-1.3,-0.9,-0.6,-0.4,-0.25], (0.155,0.12), 0.03, 1.0, 90, 0.40,
    [0.041,0.16,0.15,0.135,0.118,0.101,0.082,0.064,0.05,0.038], 1.8, 289, 702.3, 0.367, 15.0,
    "Programs fail; dilutive death-march",
    ["Clinical programs miss and the cash runs out before any partner steps in. With ~9 months of runway and a going-concern flag, the $200M ATM is tapped repeatedly into a falling stock, sinking the equity toward the $0.40 distress floor.",
     "FY35 product revenue stalls at ~$0.11B and p_fail is 90% — survival itself is the bet, not just the science. The share count balloons from 180M to ~702M, so even residual value is spread thin. DCF −$0.81; the distress-weighted expected value is ~$0.28."],
    "16% — the combination of 9-month runway, going-concern doubt, and clinical-stage risk makes near-term insolvency or a dilutive collapse a genuine, not tail, outcome."),
  "bear": sc(0.30, [0.03,0.05,0.08,0.12,0.16,0.20,0.24,0.27,0.29,0.31],
    [-6.5,-4.0,-2.5,-1.4,-0.7,-0.15,0.12,0.20,0.25,0.29], (0.145,0.115), 0.035, 1.1, 70, 0.40,
    [0.103,0.218,0.228,0.204,0.148,0.067,0.0,0.0,0.0,0.0], 2.5, 214, 567.8, 1.033, 15.0,
    "One program limps; dilution wins",
    ["A single program advances but slowly, forcing repeated capital raises through the ATM at depressed prices. The platform partly works, yet the financing dominates the equity story — every milestone is paid for in shares.",
     "FY35 revenue reaches ~$0.31B with p_fail still 70%. The share count rises to ~568M, diluting surviving holders before economics arrive. DCF −$0.46; expected value ~$0.14 — value is created, but new shares capture most of it."],
    "30% — the most likely single path: the science shows enough to keep going but not enough to raise cheaply, so dilution erodes the per-share claim faster than value compounds."),
  "base": sc(0.30, [0.04,0.07,0.11,0.17,0.24,0.32,0.40,0.45,0.48,0.50],
    [-5.5,-3.2,-1.8,-0.8,-0.15,0.12,0.22,0.28,0.33,0.37], (0.135,0.105), 0.04, 1.2, 55, 0.40,
    [0.134,0.249,0.232,0.186,0.094,0.0,0.0,0.0,0.0,0.0], 2.8, 177, 500.2, 1.667, 15.0,
    "A liver program ships; dilution offsets",
    ["A Wilson's or AATD in-vivo program reaches market and BMS milestones (>$3.5B potential) start landing, validating prime editing as a real modality. The business survives and generates revenue at ~37% drug margins.",
     "But getting there costs ~$0.9B of dilutive raises at depressed prices, nearly tripling the share count to ~500M. FY35 revenue ~$0.50B; p_fail 55%. DCF $0.84, expected ~$0.60 — per-share value lands just below spot because dilution claims the upside."],
    "30% — co-equal modal case: clinical proof exists (PM359) and the liver targets are credible, but the model auto-sizes the raises needed to fund them, and that dilution is the binding constraint on per-share value."),
  "bull": sc(0.16, [0.05,0.09,0.17,0.30,0.46,0.64,0.80,0.90,0.96,1.00],
    [-4.5,-2.2,-0.8,0.05,0.18,0.26,0.32,0.36,0.38,0.40], (0.125,0.10), 0.05, 1.4, 30, 0.40,
    [0.142,0.226,0.193,0.078,0.032,0.0,0.0,0.0,0.0,0.0], 3.5, 106, 372.3, 3.333, 15.0,
    "Liver successes; platform validates",
    ["Several in-vivo liver programs succeed and the platform partly validates as a versatile precise editor, drawing partners and pricing power. Revenue scales toward ~$1.00B at 40% margins, and earlier validation means raises come at higher prices.",
     "Because the equity is less distressed, dilution is milder — the share count rises only to ~372M, not the 500M+ of the base. p_fail falls to 30%. DCF $7.17, expected ~$5.14 — the first scenario where the platform clearly outruns the balance sheet."],
    "16% — requires both clinical breadth across liver targets and a financing path that improves as proof accumulates; plausible given the NEJM precedent, but it needs the science to de-risk before the cash forces bad raises."),
  "ultra_bull": sc(0.08, [0.06,0.12,0.24,0.44,0.70,1.05,1.45,1.75,1.92,2.00],
    [-3.5,-1.4,-0.2,0.14,0.24,0.32,0.38,0.41,0.43,0.45], (0.12,0.095), 0.06, 1.6, 18, 0.40,
    [0.129,0.205,0.123,0.063,0.0,0.0,0.0,0.0,0.0,0.0], 5.0, 58, 284.6, 6.667, 15.0,
    "Prime editing wins broadly in-vivo",
    ["Prime editing establishes itself as a broad in-vivo platform across many edit types, the durable advantage David Liu's chemistry promises. Revenue reaches ~$2.00B at 45% margins, and validation lets PRME fund growth without punishing dilution.",
     "The share count rises only to ~285M — the cleanest balance-sheet outcome — and p_fail drops to 18%. DCF $34.96, expected ~$28.74. This is the platform-wins tail that the distressed entry price makes cheap to own."],
    "8% — the platform-validation tail: requires prime editing to beat base editing and nuclease approaches on versatility and safety at scale, and the equity to survive intact long enough to capture it."),
 })
build_young(SPEC)
