#!/usr/bin/env python3
"""HOOD — Robinhood Markets (NASDAQ) mature-company memo spec. Emits data/_intake/hood.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature. CAVEAT: SEC XBRL
doesn't tag a clean operating margin for the broker, so the op-margin history below uses
net-margin estimates (not GAAP us-gaap:OperatingIncomeLoss); HOOD is SBC-dilutive (shares grow)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="HOOD", company="Robinhood Markets", exch="NASDAQ", spot=93.19,
 cap=82.80, sh=888.5, cash=4.26, net_debt=0.0, rev_b=4.473,
 wl="fcf-plus-plus-growth", tier="Med", themes=["digital-assets-fintech-rails"],
 extras=[
   "Net cash ~$4.3B, no debt; ~888.5M shares and growing (SBC-dilutive); ~$82.8B market cap",
   "Revenue $4.473B FY25 (+49%); ~50% adj-EBITDA margin in Q1'26 ($534M); FCF positive (~$1.6B), but capital-light and cyclical",
   "Down ~27% YTD to ~$93 (52-wk $63.52-$153.86), giving back part of a ~280% 2025 rally"],
 cq="Has Robinhood diversified beyond crypto and rates into a durable platform worth ~52x FCF — or is it still a transaction broker levered to the crypto and rate cycle?",
 thesis="Robinhood trades at ~$82.8B (~$93, down ~27% YTD after a ~280% 2025 rally) — ~52x FCF on $4.473B revenue growing ~49%, ~50% adj-EBITDA margin, net cash, share count rising (SBC-dilutive). Roughly a third of revenue is rate-sensitive net interest (~$40M/qtr per 25bp Fed cut) and transaction revenue is crypto/rate-cyclical (crypto -47% last quarter). The DCF asks whether events/futures/options/Gold convert HOOD into a durable diversified platform or it reverts to a transaction broker. The finding: even the diversification bull lands -40%, and only the ultra-bull (-14%) approaches fair — the price embeds a hyper-growth platform the modal case (-59%) doesn't deliver.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[1.8,1.4,1.9,3.0,4.47]),
   ("history_op_margin",[-50,-20,5,22,31]),
   ("history_fcf",[-0.9,-0.9,1.2,-0.2,1.6]),
   ("history_ev_rev",[20,12,15,20,18])],
 p3cfg=[("segment_a","Transaction"),("segment_b","Net interest + other"),
   ("hist_ent_split",[0.75,0.55,0.50,0.55,0.58]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec  ·  Q1 FY2026 results (Apr-28)",
 sources="Sources: SEC XBRL company facts (CIK 1783879; revenue, cash flow, debt), Robinhood Q1 FY2026 release (net revenue $1.07B/+15%, transaction $623M incl event contracts $147M/+320% and crypto $134M/-47%, net interest $359M/+24%, adj EBITDA $534M/~50% margin, 27.4M funded customers, 4.3M Gold subscribers). CAVEAT: XBRL does not tag a clean broker operating margin, so the op-margin history uses net-margin estimates, not GAAP operating income. Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs Coinbase, Charles Schwab, Interactive Brokers.",
 ipo="IPO Jul '21", xmin=-5.0,
 points=[[-5.0,38],[-4.5,8],[-3.5,9],[-2.5,12],[-1.5,25],[-0.8,60],[-0.3,154],[-0.1,100],[-0.05,93.19]],
 scn={
  "ultra_bear":dict(p=0.15,g=[-0.05,0.03,0.05,0.05,0.05],fcfm=[0.22,0.24,0.26,0.27,0.28],opm=[0.20,0.22,0.24,0.25,0.26],wacc=0.115,tg=0.030,fs=920,evr=[8,6,5,4.5,4],evf=[14,13,13,13,13],
    hl="Crypto rolls over; rate cuts bite.",
    narr=["The cyclical case turns: crypto extends its slide (transaction already -47% there last quarter), the Fed cuts and ~$40M/qtr per 25bp drains net interest, and the events/futures push doesn't scale fast enough to offset. Revenue dips then crawls back low-single-digit as a transaction broker, not a platform.","A cyclical broker whose growth has reversed earns a low-teens FCF multiple -> DCF ~$20 (-79%). Net cash sets a floor, but at ~52x FCF entry the de-rate to a cyclical multiple is most of the loss."],
    pr="The genuine bear: crypto revenue already fell 47% in a single quarter and ~32% of revenue rides net interest into a cutting cycle. 15% weight on the cycle turning before diversification matures."),
  "bear":dict(p=0.27,g=[0.05,0.06,0.06,0.06,0.06],fcfm=[0.28,0.30,0.31,0.32,0.32],opm=[0.26,0.28,0.29,0.30,0.30],wacc=0.105,tg=0.030,fs=915,evr=[12,10,9,8,7.5],evf=[16,15,14,14,14],
    hl="Diversifies slowly; growth normalizes.",
    narr=["Events/options/Gold grow but the crypto and rate cyclicality keep the top line lumpy; revenue normalizes to mid-single-digit as the hyper-growth fades and the SBC-driven share count keeps creeping. Robinhood is a good diversified broker, not a compounding platform.","DCF ~$28 (-69%) - a ~30%-FCF-margin broker growing mid-single-digit is worth a mid-teens multiple, well below ~52x; the market's premium unwinds as growth normalizes."],
    pr="Diversification is real but partial, and the rate/crypto cycle caps the multiple. 27% as the plausible 'diversifies but stays cyclical' path given the Q1 mix shift."),
  "base":dict(p=0.32,g=[0.14,0.11,0.09,0.08,0.07],fcfm=[0.30,0.31,0.32,0.33,0.33],opm=[0.28,0.29,0.30,0.31,0.31],wacc=0.100,tg=0.035,fs=910,evr=[15,13,11,10,9.5],evf=[18,16,16,16,16],
    hl="Diversification holds; growth decelerates to high-single.",
    narr=["The modal path: event contracts (+320% off a small base), futures (MIAXdx JV), options, Gold (4.3M subs/+36%) and banking/credit broaden the mix enough to keep ~30%+ FCF margins and double-digit-fading-to-high-single growth, but the crypto and rate cyclicality stays in the model. Revenue compounds toward ~$7B.","DCF ~$38 (-59%) - even crediting durable diversification at a ~16x FCF terminal, the modal case sits well below spot; ~52x FCF prices a faster, less cyclical platform than the base delivers."],
    pr="Requires the new lines to keep scaling while crypto/rates stay choppy - consistent with the Q1 diversification but not a step-change. 32% as the central outcome."),
  "bull":dict(p=0.18,g=[0.22,0.17,0.13,0.11,0.10],fcfm=[0.32,0.33,0.34,0.35,0.35],opm=[0.30,0.31,0.32,0.33,0.33],wacc=0.095,tg=0.040,fs=900,evr=[18,15,13,12,11],evf=[20,18,18,18,18],
    hl="Platform scales; events/futures/Gold compound.",
    narr=["The diversification thesis lands: prediction markets, futures, options and the Gold/banking ecosystem compound into a durable platform, deposit growth (~20%) cushions rate cuts, and Robinhood out-grows the cycle at a ~35% FCF margin. Revenue compounds high-teens early then high-single as the base scales.","DCF ~$56 (-40%) - a genuine platform re-rate, yet still below spot; even crediting the bull case, ~52x FCF starts above where durable diversification gets you."],
    pr="Robinhood's ~50% EBITDA margin, 36% Gold-sub growth and 320% event-contract growth make a platform path credible. ~18% weight on the diversification compounding."),
  "ultra_bull":dict(p=0.08,g=[0.30,0.24,0.18,0.14,0.12],fcfm=[0.33,0.35,0.36,0.37,0.38],opm=[0.31,0.33,0.34,0.35,0.36],wacc=0.090,tg=0.040,fs=890,evr=[20,17,15,13,12],evf=[22,20,20,20,20],
    hl="Full fintech platform; crypto cyclicality fades.",
    narr=["The full second act: prediction markets become a major venue, futures/tokenized assets/Bitstamp scale globally, banking/credit deepen the relationship, and the revenue base diversifies enough that the crypto/rate cycle stops driving it - a true fintech platform at a high-30s% FCF margin. Revenue compounds ~20%+ early.","DCF ~$80 (-14%) - the only path that approaches today's price, and it requires nearly everything to work; ~8% probability, the asymmetric outcome the rich entry is paying for."],
    pr="Everything compounds - events AND futures AND Gold AND banking AND a multiple that holds - the durable-platform outcome. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 15%","Crypto rolls over; rate cuts bite; ~$20 (-79%)."),
     ("Bear 27%","Diversifies slowly; growth normalizes; ~$28 (-69%)."),
     ("Base 32%","Diversification holds; growth fades to high-single; ~$38 (-59%)."),
     ("Bull 18%","Platform scales on events/futures/Gold; ~$56 (-40%)."),
     ("Ultra Bull 8%","Full fintech platform; cyclicality fades; ~$80 (-14%).")],
 pb=[("~52x FCF prices a platform, not a broker.","~50% EBITDA margin and +49% revenue look elite, but ~32% of revenue is rate-sensitive net interest and transaction revenue is crypto-cyclical - even the diversification bull is -40%."),
     ("Crypto -47% is the cyclicality, in the open.","Crypto transaction revenue fell 47% in a single quarter; the offset (events +320%, options, equities) is real but proves the top line still swings with the trade."),
     ("Rate cuts are a mechanical drag.","~$40M/qtr per 25bp Fed cut flows straight out of net interest; a normal cutting cycle is a multi-hundred-million annual headwind the multiple doesn't discount."),
     ("Diversification is genuine - but partial and early.","Event contracts, MIAXdx futures, Gold (4.3M/+36%), banking/credit and Bitstamp broaden the mix, yet they're small bases against the crypto/rate-levered core."),
     ("SBC dilutes the per-share math.","Share count (~888.5M) keeps rising on stock comp; even with ~50% EBITDA margins, growth must outrun dilution to lift per-share value.")],
 tr=[("Bull validation","event contracts + futures + options scale to a steady >25% of transaction revenue  ·  net-interest share falls below ~25% (less rate-levered)  ·  deposit/Gold growth holds >20%  ·  FCF margin holds >=33% through a rate-cut cycle"),
     ("Bear validation","crypto transaction revenue keeps falling and isn't offset  ·  net interest drops materially on Fed cuts  ·  revenue growth normalizes below ~10%  ·  regulatory action on EU tokenized equities or prediction markets"),
     ("Reframe needed","if crypto + net interest stay the swing factors and the new lines plateau, re-rate the terminal toward a cyclical-broker multiple (Coinbase/IBKR), not a hyper-growth platform")],
 gloss=[("Transaction revenue","Order-flow / transaction-based revenue from options, crypto, equities and event contracts (~$623M Q1, options the largest); the crypto-cyclical core the diversification is meant to de-risk."),
        ("Net interest revenue","Interest earned on margin loans, cash and securities (~$359M Q1, ~32% of revenue); the rate-sensitive line that loses ~$40M/qtr per 25bp Fed cut - the swing factor against the cycle."),
        ("Event contracts / prediction markets","Yes/no contracts on real-world outcomes (~$147M Q1, +320%); the fastest-growing new line and the centerpiece of the diversification-beyond-crypto thesis."),
        ("Gold subscription","Robinhood's ~$5/mo membership (4.3M subs, +36%) bundling higher rates, margin and perks; recurring, counter-cyclical revenue that deepens the customer relationship."),
        ("FCF margin","Free cash flow / revenue (~30-38% across scenarios); the mature-DCF lever - whether diversification keeps the high margin durable as the crypto/rate cycle turns.")],
 arena="Online brokerage / fintech rails - Robinhood (mobile-first broker, 27.4M funded customers, Gold ecosystem) vs Coinbase, Charles Schwab, Interactive Brokers, Webull, Cash App; auditing a nascent platform/branding Power against a weak moat and the transaction/rate cycle.",
 powers=[("scale_economies",3,"The dominant Power: 27.4M funded customers and ~$4.5B revenue spread fixed tech/clearing/compliance cost - real operating leverage (~50% EBITDA margin), the source of the FCF."),
         ("network_economies",1,"Nascent - prediction markets and a social/referral layer have mild network character, but trading isn't a true two-sided network."),
         ("counter_positioning",2,"Was the zero-commission disruptor that forced incumbents to drop fees; now the model is copied (Schwab/Fidelity went free), so the edge has eroded to brand/UX."),
         ("switching_costs",1,"Weak - ACATS portability and low balances make accounts easy to move; this is the moat's central hole."),
         ("branding",2,"A genuine consumer-fintech brand (the app + Gold ecosystem, default broker for a younger cohort), but young and not yet pricing power."),
         ("cornered_resource",0,"None - no proprietary asset; order flow, rates and crypto venues are all contestable."),
         ("process_power",1,"Fast product velocity (events, futures, banking, Bitstamp shipped quickly), but execution speed, not a structural process moat.")],
 dom="scale_economies", dur="medium",
 rivals=[("Coinbase (COIN)","public","The crypto-cycle benchmark; the comp for Robinhood's crypto-revenue swings and exchange economics.",0.40,0.30,"~25x EV/FCF"),
         ("Charles Schwab (SCHW)","public","Scale incumbent that went commission-free; far larger asset base, the brokerage the disruption targeted.",0.10,0.40,"~18x P/E"),
         ("Interactive Brokers (IBKR)","public","High-margin, rate-levered broker; the closest cyclical-broker multiple comp.",0.20,0.65,"~22x P/E"),
         ("Webull / Cash App","public","Mobile-first challengers competing for the same younger cohort; switching-cost pressure on the franchise.",0.20,None,"varies")],
 threats=[("scale_economies","The transaction + rate cycle","Crypto transaction revenue keeps falling and Fed cuts drain net interest, so revenue growth normalizes below ~10% before the new lines scale."),
          ("switching_costs","Bigger brokers + mobile challengers (Schwab/Fidelity/Webull/Cash App)","Funded-customer or deposit growth stalls as low switching costs let balances migrate to incumbents or rivals."),
          ("branding","Regulatory action (EU tokenized equities, prediction markets)","A regulatory curb on tokenized equities or event contracts caps the diversification lines the bull depends on.")],
 take="Robinhood's Power is scale_economies - 27.4M funded customers and ~$4.5B revenue across fixed tech/clearing cost throw off a ~50% EBITDA margin and the FCF that supports the case - plus a nascent network/branding edge in the app and Gold ecosystem. But the moat is weak: switching costs are near zero (ACATS portability), the zero-commission counter-positioning has been copied, and the live threat is the transaction/rate cycle itself (crypto -47% last quarter, ~$40M/qtr per 25bp rate cut) plus bigger brokers. The Audit: the scale Power is medium-durable, diversification is genuine but early, and that squares with a DCF where ~52x FCF prices a durable platform the modal case (-59%) doesn't deliver - only the ultra-bull (-14%), where the cyclicality truly fades, approaches today's price.",
)

if __name__ == "__main__":
    build(SPEC)
