#!/usr/bin/env python3
"""DIS — Walt Disney (NYSE) mature-company memo spec. Emits data/_intake/dis.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1744489)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="DIS", company="Walt Disney", exch="NYSE", spot=100.04, cap=178.6, sh=1785.3, cash=5.7, net_debt=42.0, rev_b=94.4,
 wl="fcf-megacap", tier=None, themes=["consumer-experience"],
 extras=[
   "$5.7B cash against ~$42B total debt (~$36B net debt); ~1,785M shares; dividend raised +50%, buyback >=$8B in FY26",
   "Revenue $94.4B FY25 (+3%); GAAP op margin 18.6% (rising); FCF ~$10.1B; streaming (DTC) OI just crossed 10%",
   "~$100, down ~9% YTD (52-wk ~$92-125), popped ~7-8% on the May print; the cheap turnaround alongside META"],
 cq="Does streaming operating margin scale from ~10% toward mid-teens fast enough to outrun the secular decline of linear TV and cable-affiliate revenue?",
 thesis="Disney trades at ~$178.6B equity (~$100, down ~9% YTD) — ~22x EV/FCF on $94.4B revenue, an 18.6% and rising operating margin, ~$10.1B FCF against ~$36B net debt. Streaming (DTC) operating income just crossed 10% (+88% YoY, guided to keep scaling), Experiences is a record cash engine (~$2.6B quarterly OI) with a $60B capex runway, and the CEO succession overhang is resolved. The DCF asks whether DTC margin scales toward mid-teens before linear TV erodes the base. The modal case lands +14% — the cheap-turnaround read, with the secular cable decline as the live drag.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[67.4,82.7,88.9,91.4,94.4]),
   ("history_op_margin",[11.5,14.7,14.5,17.1,18.6]),
   ("history_fcf",[2.0,1.1,4.9,8.6,10.1]),
   ("history_ev_rev",[4.9,2.7,2.2,2.4,2.3])],
 p3cfg=[("segment_a","Entertainment + Sports"),("segment_b","Experiences"),
   ("hist_ent_split",[0.62,0.63,0.62,0.61,0.60]),
   ("chart6_title","Equity build (Op EV - net debt)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Sept  ·  FQ2 2026 (May'26) results",
 sources="Sources: SEC XBRL company facts (CIK 1744489; revenue, GAAP operating income/margin, cash flow, debt), Disney FQ2 2026 release (DTC revenue $5.49B +13% / operating income $582M +88% / 10.6% margin; Experiences revenue $9.5B +7% / OI $2.6B records; domestic park visitation -1%; dividend +50%, buyback >=$8B; $60B/10-yr Experiences capex; Josh D'Amaro named CEO). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs NFLX/CMCSA/WBD/PARA.",
 ipo="NYSE since '57", xmin=-6.2,
 points=[[-6.0,110],[-5.0,150],[-4.2,200],[-3.3,90],[-2.5,85],[-1.5,110],[-0.8,120],[-0.3,92],[-0.05,100.04]],
 scn={
  "ultra_bear":dict(p=0.13,g=[0.01,0.01,0.01,0.01,0.01],fcfm=[0.08,0.08,0.08,0.09,0.09],opm=[0.16,0.16,0.16,0.17,0.17],wacc=0.10,tg=0.02,fs=1790,evr=[2,1.8,1.7,1.6,1.5],evf=[13,13,13,13,13],
    hl="Cable erodes faster than DTC scales.",
    narr=["The secular decline wins: linear TV and cable-affiliate revenue erode faster than streaming margin builds, sports rights costs outrun ESPN DTC ramp, and parks demand softens as domestic attendance keeps slipping. Revenue barely grows (~1%) and the operating margin stalls near 16-17% as the mix shift turns into a mix drag.","A media-and-parks conglomerate whose growth core never outpaces its declining legacy earns a low terminal multiple -> DCF ~$36 (-64%). The ~$36B net debt amplifies the equity hit when EBITDA disappoints."],
    pr="The genuine bear: cord-cutting is structural, domestic park visitation already printed -1%, and content is hit-driven. 13% weight on the legacy decline outrunning the DTC turnaround."),
  "bear":dict(p=0.27,g=[0.03,0.03,0.03,0.03,0.03],fcfm=[0.10,0.10,0.11,0.11,0.11],opm=[0.18,0.18,0.19,0.19,0.19],wacc=0.095,tg=0.025,fs=1780,evr=[2.5,2.3,2.2,2.1,2],evf=[16,15,15,15,15],
    hl="DTC profits, but cable offsets it.",
    narr=["Streaming holds its ~10% margin and grows, but the affiliate/ad decline at the linear networks offsets most of the gain; parks lean on price (attendance flat) and the $60B capex weighs on near-term free cash flow until the new capacity opens. Revenue compounds ~3% at a low-double-digit FCF margin.","DCF ~$66 (-34%) — a stabilizing but not-yet-reaccelerating Disney at ~15x FCF is worth less than today's price; the market's discount holds if DTC scaling only treads water against the cable runoff."],
    pr="The DTC turnaround is real but the linear drag and capex timing cap it; parks growth is price-led until 2027-2029. 27% as the plausible 'profits but doesn't compound' path."),
  "base":dict(p=0.34,g=[0.05,0.05,0.05,0.04,0.04],fcfm=[0.11,0.12,0.13,0.13,0.14],opm=[0.19,0.20,0.21,0.21,0.22],wacc=0.09,tg=0.03,fs=1760,evr=[3,2.8,2.7,2.6,2.5],evf=[19,18,17,17,17],
    hl="DTC scales toward mid-teens; FCF compounds.",
    narr=["The modal path: streaming operating margin grinds from ~10% toward mid-teens on operating leverage (ESPN DTC, bundling, Hulu fully owned), Experiences compounds mid-single-digit as the $60B runway adds supply-constrained capacity, and the combined engine outgrows the shrinking linear base. Revenue compounds ~5% and the operating margin climbs past 20%; FCF margin grinds toward 14%.","DCF ~$114 (+14%) — the cheap-turnaround read. A franchise with a scaling DTC margin and a record cash engine in Experiences, at ~17x FCF, re-rates modestly above today's price once the growth core clears the legacy drag."],
    pr="Requires DTC margin to keep scaling (guided >=10% FY26, +88% YoY OI) and Experiences to hold its record cash flow as capex pays off. 34% as the central, modestly-positive outcome."),
  "bull":dict(p=0.18,g=[0.06,0.06,0.06,0.05,0.05],fcfm=[0.13,0.14,0.15,0.16,0.16],opm=[0.20,0.21,0.22,0.23,0.23],wacc=0.085,tg=0.035,fs=1740,evr=[3.5,3.3,3.2,3.1,3],evf=[22,21,21,21,21],
    hl="Streaming hits mid-teens; parks reaccelerate.",
    narr=["The turnaround compounds: streaming margin reaches mid-teens and keeps climbing as the bundle (Disney+/Hulu/ESPN DTC) gains pricing and scale, the new park capacity opens into resilient demand and reaccelerates Experiences past price-led growth, and FCF margin lifts toward 16%. Revenue compounds ~6% at a margin recovering toward the historical peak.","DCF ~$173 (+73%) - if the DTC engine becomes the durable growth core and Experiences reaccelerates, the de-rated entry re-rates with the fundamentals; this is the core of the bull."],
    pr="DTC scaling plus a $60B-funded Experiences reacceleration and a smooth CEO handoff make a real compounding case credible. ~18% weight on the turnaround landing."),
  "ultra_bull":dict(p=0.08,g=[0.07,0.07,0.07,0.06,0.06],fcfm=[0.14,0.15,0.16,0.17,0.18],opm=[0.21,0.22,0.23,0.24,0.25],wacc=0.082,tg=0.035,fs=1720,evr=[4,3.8,3.7,3.6,3.5],evf=[24,22,22,22,22],
    hl="Full re-rate; streaming a profit machine.",
    narr=["The full second act: streaming becomes a high-teens-margin profit machine, the IP library and franchises monetize across DTC, parks and consumer products, the new $60B of capacity compounds Experiences for a decade, and Disney re-rates to a growth-media multiple as the linear drag fades into irrelevance. Revenue compounds ~7% at peak margins.","DCF ~$223 (+123%) - the franchise reclaims a premium compounder valuation; ~8% probability, the asymmetric upside the depressed entry is buying."],
    pr="Everything works - DTC margins AND Experiences reacceleration AND franchise monetization AND a multiple re-rate, the long-duration tail. ~8%."),
 },
 wr=[("Ultra Bear 13%","Cable erodes faster than DTC scales; ~$36 (-64%)."),
     ("Bear 27%","DTC profits but linear decline offsets it; ~$66 (-34%)."),
     ("Base 34%","DTC scales toward mid-teens; FCF compounds; ~$114 (+14%)."),
     ("Bull 18%","Streaming hits mid-teens; parks reaccelerate; ~$173 (+73%)."),
     ("Ultra Bull 8%","Full re-rate; streaming a profit machine; ~$223 (+123%).")],
 pb=[("The streaming turnaround is no longer a maybe.","DTC operating income +88% YoY to a 10.6% margin (first quarter above double digits, guided >=10% FY26) - the central bull thesis is already printing, not projected."),
     ("Experiences is a record cash engine.","~$2.6B quarterly OI (a record), a $60B/10-yr capex runway adding supply-constrained capacity - the parks fund the streaming build and anchor the floor."),
     ("Linear TV is the live drag, not a tail risk.","Cable-affiliate and ad revenue are in structural decline; the whole question is whether DTC + Experiences outgrow it, and the bear/base fork turns on that pace."),
     ("The CEO overhang is resolved.","Josh D'Amaro (28-yr veteran who ran Experiences) named CEO, effective at the March annual meeting - the succession question that hung over the stock is settled, though a first-time CEO carries transition risk."),
     ("Net debt ~$36B is the amplifier.","Unlike the net-cash mega-caps, ~$36B of net debt levers the equity to EBITDA - the modal case re-rates above spot, but the downside scenarios bite harder.")],
 tr=[("Bull validation","DTC operating margin scales past low-teens toward mid-teens  ·  ESPN DTC + bundle pricing hold  ·  Experiences reaccelerates beyond price-led growth as new capacity opens  ·  FCF compounds despite the $60B capex"),
     ("Bear validation","DTC margin stalls near 10% while linear affiliate/ad revenue keeps eroding  ·  domestic park attendance stays negative  ·  content underperforms (hit-driven)  ·  net debt rises on the capex without offsetting EBITDA"),
     ("Reframe needed","if linear TV erodes faster than DTC + Experiences can grow - the growth core never clears the legacy drag - re-rate the terminal toward a declining-media-conglomerate multiple rather than a scaling-streamer one")],
 gloss=[("DTC / streaming","Direct-to-consumer (Disney+, Hulu, ESPN DTC) operating income; just crossed a 10% margin (+88% YoY), the swing-factor metric the whole turnaround turns on."),
        ("Linear networks / affiliate","Traditional cable/broadcast (ABC, ESPN cable, the channels) and the carriage fees pay-TV distributors pay - in structural secular decline as cord-cutting erodes the base the DTC gains must outrun."),
        ("Experiences","The parks, resorts, cruise lines and consumer-products segment - a record cash engine (~$2.6B quarterly OI) with a $60B/10-yr capex runway; near-term growth is price-led ('essentially full') until 2027-2029 expansions."),
        ("Cornered resource (IP)","Helmer Power: the franchise/IP library (Disney, Pixar, Marvel, Star Wars, ESPN) that monetizes across streaming, parks and products - Disney's most durable moat."),
        ("FCF margin","Free cash flow / revenue (~11% FY25, ~$10.1B); the mature-DCF lever the 18.6% operating margin converts to once the $60B Experiences capex is funded.")],
 arena="Media + theme parks - Disney (IP library/franchises, parks, the Disney+/Hulu/ESPN DTC bundle) vs Netflix in streaming, Comcast/Universal in parks, Warner Bros. Discovery and Paramount in legacy media; auditing a cornered-resource/brand Power against the secular decline of linear TV.",
 powers=[("scale_economies",4,"Massive content and capex scale - Disney spreads franchise production, a global parks footprint and DTC tech across the industry's largest revenue base; a genuine cost advantage."),
         ("network_economies",2,"The Disney+/Hulu/ESPN bundle plus loyalty/MagicBand data create modest cross-sell pull, but streaming is not a hard network - subscribers churn freely."),
         ("counter_positioning",0,"None - Disney is the incumbent being disrupted by streaming and cord-cutting, not the disruptor; it had to cannibalize its own cable economics to build DTC."),
         ("switching_costs",1,"Weak - streaming is month-to-month and promiscuous; parks/cruise loyalty is real but a small share of revenue."),
         ("branding",4,"A top global consumer brand - Disney/Pixar/Marvel/Star Wars command pricing power in parks and a trust premium with families; durable but not converting fast while linear declines."),
         ("cornered_resource",5,"The dominant Power: an irreplaceable IP/franchise library (a century of characters + ESPN sports rights) that monetizes across DTC, parks and products - the hardest asset in media to replicate."),
         ("process_power",2,"Decades of theme-park operating and franchise-development know-how; real but not a primary moat versus the IP itself.")],
 dom="cornered_resource", dur="high",
 rivals=[("Netflix (NFLX)","public","The streaming scale leader and DTC-margin benchmark Disney's turnaround is measured against; far higher streaming margin.",0.14,0.27,"~12x EV/sales"),
         ("Comcast / Universal (CMCSA)","public","The parks rival (Epic Universe) and a cable peer; the closest media-plus-parks comp, cheaper multiple.",0.02,0.19,"~7x EV/FCF"),
         ("Warner Bros. Discovery (WBD)","public","Legacy-media peer mid-restructuring; the cautionary 'cable decline + DTC build + leverage' comparison.",0.0,0.10,"~6x EV/EBITDA"),
         ("Paramount (PARA)","public","Sub-scale legacy media + DTC; the 'left behind by streaming economics' comp.",0.0,0.08,"~7x EV/EBITDA")],
 threats=[("cornered_resource","Cord-cutting / linear decline","Cable-affiliate and ad revenue erode faster than DTC + Experiences grow, so the franchise library's legacy monetization shrinks faster than the new channels replace it."),
          ("branding","Netflix / streaming competition","DTC margin stalls near 10% as bundle pricing and ESPN DTC fail to scale against Netflix's lead, and subscriber growth/churn worsens."),
          ("scale_economies","Parks demand softness","Domestic attendance stays negative and the $60B capacity opens into a soft consumer, so Experiences growth stays price-led and the cash engine stalls.")],
 take="Disney's cornered-resource Power is genuine and durable (high) - a century-deep IP/franchise library plus ESPN sports rights that monetize across streaming, parks and consumer products, the hardest asset in media to replicate, backed by a top brand and the industry's largest scale. The Audit: the live threat is the secular decline of linear TV/cable affiliate revenue, and the question is whether the scaling DTC margin (just crossed 10%, +88% YoY) and the record Experiences engine ($2.6B quarterly OI, $60B runway) outgrow that runoff before it erodes the base. The DCF tests the pace; the modal case lands +14% - the cheap-turnaround read, with ~$36B net debt amplifying both tails.",
)

if __name__ == "__main__":
    build(SPEC)
