#!/usr/bin/env python3
"""TEM — Tempus AI (NASDAQ) · MATURE memo intake builder (reclassified young->mature,
TXG precedent). Numbers locked via /tmp/young/tem_mature.py (model_mature); prose
conviction-neutral. Finding: weighted $34.18 vs spot $47.82 = -28.5% — rich, priced for
perfection (ILMN/RDDT family); SBC ~$136M/yr swamps the +$65M adj-EBITDA -> owner-FCF still negative."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="TEM", company="Tempus AI", exch="NASDAQ", spot=47.82, cap=8.59, sh=179.6, cash=0.644, net_debt=0.560, rev_b=1.30,
 wl="asymmetrical-moonshots", tier="Low", themes=["precision-medicine-oncology"],
 extras=["$1.3B revenue FY25 (+83%, Ambry-boosted); FY26 guide $1.59-1.60B (+25%)",
         "Adj-EBITDA inflected positive (FY26 guide ~$65M) but SBC ~$136M/yr -> owner-FCF still negative",
         "Net cash ~$84M ($0.644B cash vs $0.560B Ares term loan); Lefkofsky ~60% voting control"],
 cq="At ~6.6x sales and near-breakeven, is the market paying for proven cash economics, or for a data-moat plus a margin inflection that SBC currently swamps and the modal case doesn't deliver?",
 thesis="Tempus AI is AI-precision-oncology diagnostics plus a multimodal health-data flywheel. Revenue is $1.3B, growing 25-36%, adj-EBITDA just inflected positive (FY26 guide ~$65M). But SBC runs ~$136M/yr — more than 10% of revenue and larger than that adj-EBITDA — so true owner free cash flow is still negative. At $47.82 (~$8.6B cap, down ~20% YTD, net cash ~$84M) the modal 5-year DCF is $30.42, about 36% below spot. Only the bull case — sustained 21%+ growth and a ~23% terminal margin — clears the price. You are paying today for continued hypergrowth and an unproven margin turn.",
 chartref=[("history_years", [2023, 2024, 2025]), ("history_revenue", [0.532, 0.693, 1.303]),
           ("history_op_margin", [-50.0, -29.0, -19.0]), ("history_fcf", [-0.21, -0.13, -0.12]),
           ("history_ev_rev", [10.0, 9.0, 6.5])],
 p3cfg=[("segment_a", "Genomics / Diagnostics"), ("segment_b", "Data & Applications"),
        ("hist_ent_split", [0.80, 0.78, 0.75]), ("chart6_title", "Equity build (Op EV + net cash)"),
        ("chart6_type", "matureEquityBuild")],
 subtitle="FY23-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec 31  ·  FY2025 (Feb'26) + Q1'26 results",
 sources="Sources: Tempus AI FY2025 10-K + Q1'26 8-K (CIK 1717115), FY2026 guidance. Revenue as a growth-rate path off FY25; FCF = revenue x an SBC-adjusted owner-FCF margin (the ~$136M/yr SBC exceeds the +$65M adj-EBITDA, so the modeled margin starts negative); Gordon terminal at scenario WACC. EV/sales vs precision-diagnostics peers.",
 ipo="IPO Jun '24", xmin=-2.0,
 points=[[-1.9, 37.0], [-1.5, 55.0], [-1.0, 70.0], [-0.7, 103.0], [-0.5, 60.0], [-0.3, 50.0], [-0.05, 47.82]],
 scn={
  "ultra_bear": dict(p=0.14, g=[0.15,0.10,0.07,0.05,0.04], fcfm=[-0.08,-0.04,0.0,0.03,0.05], opm=[-0.06,-0.02,0.02,0.05,0.07], wacc=0.115, tg=0.03, fs=200, evr=[5.0,4.0,3.0,2.5,2.0], evf=[60,40,30,26,22],
    hl="Growth collapses, never durably profitable",
    narr=["Revenue growth fades toward ~8% as oncology test volume saturates and the data-licensing pipeline stalls. The margin path inches from −8% to only 5% — operating leverage never arrives because SBC and clinical-lab costs scale with revenue.",
          "The company de-rates to a distressed multiple as the market stops paying for a moat that did not compound. Dilution from continued stock comp erodes per-share value. The DCF lands at $3.45, roughly 93% below spot."],
    pr="A ~14% tail. Requires both the diagnostics franchise to stall and Data and Applications to stop scaling — possible if pharma budgets tighten and foundation-model rivals commoditize the data, but it contradicts the +40%+ data-licensing trend now in evidence."),
  "bear": dict(p=0.28, g=[0.20,0.15,0.11,0.08,0.07], fcfm=[-0.04,0.0,0.05,0.08,0.11], opm=[-0.02,0.02,0.07,0.10,0.13], wacc=0.105, tg=0.035, fs=196, evr=[5.5,5.0,4.5,4.0,3.5], evf=[55,38,30,26,22],
    hl="Decelerates hard, thin margins persist",
    narr=["Growth slows to ~12% as Guardant, Natera, and Caris pressure diagnostics pricing and reimbursement caps revenue per test. The data flywheel keeps compounding but cannot offset a maturing core diagnostics line.",
          "Margins climb from −4% to ~11% — positive, but far short of software economics, because SBC and lab infrastructure stay heavy. The DCF is $13.47, about 72% below spot. The market re-rates toward a mid-teens-growth diagnostics comp."],
    pr="A ~28% weight, the second-likeliest outcome. This is the world where TEM is a good but ordinary diagnostics-plus-data business — real growth, real competition, no durable software margin. Pricing pressure is the swing variable."),
  "base": dict(p=0.33, g=[0.25,0.20,0.15,0.12,0.10], fcfm=[-0.02,0.04,0.09,0.13,0.17], opm=[0.0,0.06,0.11,0.15,0.19], wacc=0.10, tg=0.04, fs=192, evr=[6.0,5.5,5.0,4.5,4.0], evf=[50,32,26,22,19],
    hl="Solid growth, but modal value sits below spot",
    narr=["Revenue compounds ~16% as oncology volume grows ~28% and Data and Applications scales the ~80%-margin pharma-licensing line. The AstraZeneca-Pathos deal type repeats, and the 7.3M-record library keeps feeding both segments.",
          "Margins ramp from −2% to ~17% as the data mix lifts the blend, but SBC keeps owner-FCF modest early. The DCF is $30.42 — a healthy business, about 36% below spot. The modal case simply does not support $47.82."],
    pr="The single most-likely path at ~33%. It assumes the current trajectory broadly holds — mid-teens growth, a scaling data line, gradual margin gains — without the step-change in operating leverage the bull requires. It is the honest anchor for the finding."),
  "bull": dict(p=0.17, g=[0.30,0.25,0.20,0.16,0.13], fcfm=[0.02,0.08,0.14,0.19,0.23], opm=[0.04,0.10,0.16,0.21,0.25], wacc=0.095, tg=0.045, fs=188, evr=[6.5,6.0,5.5,5.0,4.5], evf=[45,30,24,20,17],
    hl="Data flywheel drives a real margin inflection",
    narr=["Growth holds at ~21% as Data and Applications compounds 40%+ and the ~80%-margin data line becomes a larger share of the mix. The multimodal library proves hard to replicate, and pharma standardizes on Tempus for oncology data.",
          "Operating leverage finally clears SBC: margins ramp from 2% to ~23%, reaching a durable-profit inflection. The DCF is $61.38, about 28% above spot. This is the lowest scenario that justifies today's price."],
    pr="A ~17% weight. Requires two things at once — sustained high growth AND a genuine terminal margin, not just adj-EBITDA. Plausible if the data moat re-rates the whole company, but it is the entry hurdle, not the expected case."),
  "ultra_bull": dict(p=0.08, g=[0.36,0.30,0.25,0.20,0.16], fcfm=[0.05,0.12,0.19,0.25,0.29], opm=[0.07,0.14,0.21,0.27,0.31], wacc=0.09, tg=0.05, fs=186, evr=[7.0,6.5,6.0,5.5,5.0], evf=[40,28,22,18,15],
    hl="Becomes the oncology-data standard",
    narr=["TEM wins the platform: the multimodal library becomes the default substrate for oncology drug development and clinical decisioning. Revenue compounds ~25%, with Data and Applications the growth engine at software gross margins.",
          "Margins ramp from 5% to ~29% as the high-margin data mix dominates and scale economics compound. The DCF reaches $118.12, about 147% above spot — a platform-winner outcome, not a diagnostics multiple."],
    pr="An ~8% tail. The data-moat optionality the price already embeds, paid off in full: a network-and-scale flywheel that no rival replicates. Low probability, but it is the asymmetric reason a long position is debated at all."),
 },
 wr=[("Ultra Bear 14%", "Growth fades to ~8%, margin tops out ~5%, distressed re-rate; DCF $3.45."),
     ("Bear 28%", "~12% growth, pricing pressure, margins ~11% but thin; DCF $13.47."),
     ("Base 33%", "~16% growth, data line scales, margins ~17%; DCF $30.42 — below spot."),
     ("Bull 17%", "~21% growth plus a ~23% terminal margin; DCF $61.38 — clears spot."),
     ("Ultra Bull 8%", "~25% growth, software margins, data standard; DCF $118.12.")],
 pb=[("The moat is real and hard to replicate", "7.3M multimodal records (1.3M genomic, 1.4M imaging) feeding an ~80%-margin licensing flywheel is a cornered resource rivals can't quickly assemble."),
     ("Data and Applications is compounding +40%+", "If data-licensing keeps growing 44% as in Q1'26, the high-margin mix re-rates the whole company toward the bull/ultra-bull path."),
     ("Ambry adds scale and a funnel", "The ~$600M Ambry deal added hereditary-cancer testing volume that feeds more records into the library — scale economics, not just revenue."),
     ("Adj-EBITDA already inflected positive", "Q4'25 was +$12.9M and FY26 guides ~$65M; the margin turn the base needs may already be underway, just masked by SBC."),
     ("Pharma is validating the data, not just buying tests", "The $200M AstraZeneca-Pathos foundation-model deal prices the data asset directly — a repeatable, capital-light revenue type.")],
 tr=[("Bull validation", "Data and Applications sustains 40%+ growth; gross margin and adj-EBITDA margin both expand while SBC falls as a share of revenue; new multi-year pharma data deals sign."),
     ("Bear validation", "Diagnostics revenue-per-test compresses under Guardant/Natera/Caris; total growth slips toward the low teens; SBC stays above adj-EBITDA so owner-FCF remains negative."),
     ("Reframe needed", "Foundation models trained on open or competitor data erode the licensing premium, or reimbursement cuts diagnostics economics — either would collapse the ~80%-margin moat thesis.")],
 gloss=[("Multimodal data library", "TEM's 7.3M+ de-identified patient records linking genomic, imaging, and clinical data — the proprietary asset feeding both diagnostics and licensing."),
        ("Data and Applications", "The pharma data-licensing segment ($87M in Q1'26, +41%); ~80% gross margin, the high-margin flywheel distinct from the diagnostics lab business."),
        ("MRD", "Minimal residual disease — detecting trace cancer after treatment; a growth vector for oncology testing volume and a competitive battleground."),
        ("Adj-EBITDA vs owner-FCF", "Adjusted EBITDA adds back ~$136M/yr of stock comp; true owner free cash flow does not, so the headline positive adj-EBITDA still maps to negative cash today."),
        ("SBC", "Stock-based compensation (~$136M/yr, over 10% of revenue) — a real, recurring, dilutive cost that exceeds adj-EBITDA and currently swamps the margin story."),
        ("Dual-class control", "Founder-CEO Eric Lefkofsky holds ~60% of the vote via super-voting shares, concentrating control and limiting outside accountability — a governance flag.")],
 arena="AI-precision-oncology: molecular diagnostics plus a multimodal-data-licensing flywheel, against Guardant, Natera, Caris, Foundation Medicine (Roche), and Exact Sciences.",
 powers=[("scale_economies", 2, "Larger record base lowers unit cost of model training and licensing; reinforces the data flywheel as volume grows."),
         ("network_economies", 2, "More clinical use feeds more records, which improve products that attract more use — a data network loop, not a user network."),
         ("counter_positioning", 1, "Software-margin data licensing is a model legacy lab-only rivals can't easily adopt without cannibalizing test revenue."),
         ("switching_costs", 1, "Pharma data pipelines and clinician workflow integration create modest stickiness, but contracts are re-competed."),
         ("branding", 1, "Recognized in AI-oncology, but diagnostics buyers decide on accuracy, reimbursement, and price, not brand."),
         ("cornered_resource", 3, "The 7.3M-record multimodal library (1.3M genomic, 1.4M imaging) is the proprietary, hard-to-replicate asset and the dominant Power."),
         ("process_power", 1, "Multimodal data engineering is a capability, but not yet a durable, uncopyable process advantage.")],
 dom="cornered_resource", dur="medium",
 rivals=[("Guardant Health", "public", "Liquid biopsy and MRD; scaling oncology volume", 0.20, None, "~6x sales"),
         ("Natera", "public", "Oncology and women's-health molecular testing; near breakeven", 0.30, 0.0, "~9x sales"),
         ("Foundation Medicine", "private", "Roche-owned genomic-profiling division; deep-pocketed", None, None, "division of Roche"),
         ("Exact Sciences", "public", "Cologuard plus oncology; established but slower-growing", 0.12, None, "~4x sales")],
 threats=[("cornered_resource erosion", "foundation-model rivals", "Open or competitor-trained oncology models replicate the data edge, commoditizing the ~80%-margin licensing line."),
          ("scale_economies / pricing", "Guardant, Natera, Caris", "Diagnostics price competition compresses revenue per test, starving the volume that feeds the data flywheel."),
          ("regulatory / reimbursement", "payers and CMS", "Reimbursement cuts to molecular diagnostics undermine the core economics and the funnel that grows the record library.")],
 take="A durable Power is plausibly present but not proven. The cornered resource — a 7.3M-record multimodal library feeding an ~80%-margin licensing flywheel with a data-network loop — is genuinely hard to replicate, hence the bull case. But durability is medium, not high: the falsifier is foundation models trained on open or rival data closing the gap, or diagnostics pricing pressure starving the volume that feeds it. The moat must keep Data and Applications compounding 40%+ to earn the price.",
)
build(SPEC)
