#!/usr/bin/env python3
"""U — Unity Software (NYSE) mature-company memo spec. Emits data/_intake/u.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1810806)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="U", company="Unity Software", exch="NYSE", spot=27.24, cap=11.79, sh=433.0, cash=2.06, net_debt=2.24, rev_b=1.850,
 wl="fcf-plus-plus-growth", tier="Low", themes=["creator-design-software","ai-compute"],
 extras=[
   "~$2.06B cash vs ~$2.24B convertibles (net debt ~$0.18B); 2026 Notes mature Nov-2026; ~433M shares, up ~56% over 5 years on SBC",
   "Revenue $1.85B FY25 (+3%); GAAP op margin still -25.9% (loss); FCF +$0.4B (~22%) but ex-SBC FCF far thinner; adj EBITDA ~27%",
   "~$27, down ~58% YTD (52-wk ~$15-$52); IPO'd Sep-2020 at $52 — a GAAP-loss turnaround, the most speculative name in this batch"],
 cq="Does Vector turn Unity into a durable, profitable ad-and-engine platform — or does engine-share erosion plus SBC dilution and the convertibles keep GAAP losses and a wide downside?",
 thesis="Unity trades at ~$11.8B (~$27, down ~58% YTD) — ~30x FCF on $1.85B revenue, but the FCF flatters a still-GAAP-loss business: shares are up ~56% in five years on stock comp and ~$2.2B convertibles (Nov-2026) sit against ~$2.15B cash. This is a turnaround bet on the Vector AI ad engine (Grow +24%, Vector +80%, ~$1B ARR targeted), not an FCF compounder. The base case models a lower ex-SBC FCF margin AND a growing share count, so dilution is the core mechanism. The distribution is wide and the weighted finding is -56.5% — the modal case is still well below spot.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[1.1,1.4,2.2,1.8,1.85]),
   ("history_op_margin",[-47.9,-63.4,-38.1,-41.6,-25.9]),
   ("history_fcf",[-0.2,-0.1,0.2,0.3,0.4]),
   ("history_ev_rev",[25,8,7,6,6.5])],
 p3cfg=[("segment_a","Grow (ads / Vector)"),("segment_b","Create (subscriptions)"),
   ("hist_ent_split",[0.55,0.60,0.65,0.68,0.69]),
   ("chart6_title","Equity build (Op EV − net debt)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec  ·  Q1 FY2026 (May-2026) results",
 sources="Sources: SEC XBRL company facts (CIK 1810806; revenue, GAAP operating income/margin, cash flow, debt), Unity Q1 FY2026 release (revenue $508M +17%; Grow/ads $352M +24% with Vector +80%; GAAP net loss -$347M incl a $279M ironSource Ads impairment; adj EBITDA ~27%; FCF +$66M; cash ~$2.15B; ~$2.2B convertibles). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin (ex-SBC, with a growing share count); Gordon terminal at scenario WACC. EV/sales & EV/FCF vs AppLovin, Epic (Unreal), Godot.",
 ipo="IPO Sep '20", xmin=-5.7,
 points=[[-5.7,52],[-5.0,180],[-4.2,120],[-3.3,30],[-2.5,40],[-1.5,25],[-0.8,52],[-0.3,18],[-0.1,27],[-0.05,27.24]],
 scn={
  "ultra_bear":dict(p=0.18,g=[-0.05,0.00,0.03,0.04,0.05],fcfm=[0.02,0.04,0.06,0.07,0.08],opm=[-0.10,-0.05,0.00,0.02,0.04],wacc=0.125,tg=0.025,fs=520,evr=[3,2.5,2.2,2,1.8],evf=[11,11,10,10,10],
    hl="Vector stalls; engine bleeds; dilution wins.",
    narr=["Vector's +80% comp lapses and ad share reverts toward AppLovin; Create keeps losing developers to Godot/Unreal post-runtime-fee, revenue barely grows, and GAAP stays in the red. Ex-SBC free cash flow stays near 2-8% while the share count keeps climbing past 520M on stock comp.","A barely-growing, loss-making engine whose cash flow is consumed by dilution earns a distressed ~10x terminal multiple net of the convertibles -> DCF ~$2.02 (-93%). The ~$2.2B notes maturing into ~$2.15B cash leave no cushion if FCF doesn't inflect.",],
    pr="The genuine bear: GAAP losses persist, the ironSource sunset forced a $279M charge, soft gaming demand pressures Grow, and SBC has diluted holders ~56% in five years. 18% on Vector failing and dilution dominating."),
  "bear":dict(p=0.28,g=[0.06,0.07,0.07,0.07,0.06],fcfm=[0.06,0.08,0.10,0.11,0.12],opm=[-0.02,0.03,0.07,0.09,0.11],wacc=0.115,tg=0.030,fs=500,evr=[4,3.5,3.2,3,2.8],evf=[13,12,12,12,12],
    hl="Modest growth; FCF thin; GAAP barely turns.",
    narr=["Vector grows but decelerates as easy comps lapse and Create stabilizes only slowly; revenue compounds mid-single-digit, GAAP operating margin crosses zero late, and ex-SBC FCF margin grinds to ~12% against a still-rising ~500M share count.","DCF ~$5.44 (-80%) — a low-growth software business whose free cash flow is split with dilutive stock comp, net of the convertibles, is worth a fraction of today's price; the market is pricing more of the turnaround than this path delivers.",],
    pr="Vector helps but doesn't compound, engine-share leakage caps Create, and dilution keeps per-share cash flow thin. 28% as the plausible 'turns but doesn't compound' path given the GAAP losses and competition."),
  "base":dict(p=0.30,g=[0.15,0.13,0.11,0.10,0.09],fcfm=[0.08,0.11,0.13,0.15,0.16],opm=[0.00,0.05,0.10,0.13,0.15],wacc=0.110,tg=0.035,fs=485,evr=[5,4.5,4.2,4,3.8],evf=[15,14,14,14,14],
    hl="Vector scales; GAAP turns; dilution persists.",
    narr=["The modal path: Vector hits ~$1B ARR and keeps gaining mobile-ad share, Grow compounds low-double-digit, Create stabilizes, and GAAP operating margin turns positive and climbs toward ~15%. But ex-SBC FCF margin only reaches ~16% and the share count still drifts up toward ~485M, so per-share cash flow lags the headline.","DCF ~$10.78 (-60%) — even with Vector working and GAAP turning, a ~14x terminal multiple on diluted, ex-SBC free cash flow net of the ~$2.2B convertibles lands well below spot. The modal case still says the price embeds more than the fundamentals underwrite.",],
    pr="Requires Vector to sustain ad-share gains and GAAP to inflect while dilution continues - consistent with the +80% Vector growth and the ~$1B ARR target, but not a full re-rate. 30% as the central, still-negative outcome."),
  "bull":dict(p=0.16,g=[0.22,0.20,0.17,0.14,0.12],fcfm=[0.10,0.14,0.17,0.20,0.22],opm=[0.03,0.09,0.14,0.18,0.21],wacc=0.105,tg=0.040,fs=470,evr=[6,5.5,5.2,5,4.8],evf=[17,16,16,16,16],
    hl="Vector beyond gaming; margins inflect.",
    narr=["Vector sustains its ad-share gains and extends beyond mobile gaming into new verticals, adj EBITDA margin keeps expanding past 27%, ex-SBC FCF margin inflects toward ~22%, and SBC moderates so the share count nearly stabilizes near ~470M. Revenue compounds high-teens.","DCF ~$22.13 (-19%) - if Vector becomes a durable cross-vertical ad platform and dilution slows, the de-rated entry closes most of the gap to spot; this is the core of the bull.",],
    pr="Vector durably wins ad share beyond gaming while cost discipline lifts margins and curbs dilution - the turnaround landing. ~16% weight on Vector becoming a real platform."),
  "ultra_bull":dict(p=0.08,g=[0.30,0.27,0.23,0.19,0.16],fcfm=[0.12,0.16,0.21,0.25,0.28],opm=[0.05,0.12,0.18,0.23,0.26],wacc=0.100,tg=0.040,fs=460,evr=[7,6.5,6.2,6,5.8],evf=[18,17,17,17,17],
    hl="Vector platform; GAAP-profitable compounder.",
    narr=["The full second act: Vector becomes the default cross-vertical AI ad engine, Create re-accelerates on AI tooling, Unity turns durably GAAP-profitable, ex-SBC FCF margin reaches high-20s%, and dilution falls away so per-share cash flow finally compounds. Revenue compounds ~20%+.","DCF ~$39.96 (+47%) - the only path that prices Unity as a profitable platform compounder rather than a dilutive turnaround; ~8% probability, the asymmetric upside the depressed, speculative entry is buying.",],
    pr="Everything works - Vector platformizes AND Create recovers AND GAAP profitability AND dilution stops. ~8%, the long-duration tail on a name with a very wide distribution."),
 },
 wr=[("Ultra Bear 18%","Vector stalls; engine bleeds; dilution wins; ~$2.02 (-93%)."),
     ("Bear 28%","Modest growth; FCF thin; GAAP barely turns; ~$5.44 (-80%)."),
     ("Base 30%","Vector scales; GAAP turns; dilution persists; ~$10.78 (-60%)."),
     ("Bull 16%","Vector beyond gaming; margins inflect; ~$22.13 (-19%)."),
     ("Ultra Bull 8%","Vector platform; profitable compounder; ~$39.96 (+47%).")],
 pb=[("FCF is positive — why a -60% modal case?","~$0.4B FCF (~22%) is real but flatters a GAAP-loss business; the base models the ex-SBC margin AND a growing share count, so per-share cash flow is far thinner than the headline."),
     ("Vector is genuinely re-accelerating ads.","Grow +24% with Vector +80% toward ~$1B ARR at high mobile-ad share is the bull; the question is whether it sustains past easy comps and beyond gaming, vs AppLovin."),
     ("The convertibles are a 2026 cliff.","~$2.2B notes mature Nov-2026 against ~$2.15B cash — manageable but it removes the buffer if the turnaround slips, and it's why the bear net-of-debt bridge bites."),
     ("Dilution is the core bear mechanism.","Shares are up ~56% in five years on SBC; even with revenue growing, per-share value leaks unless stock comp moderates — modeled as a rising share count in every scenario."),
     ("Engine share is being contested.","Godot + Unreal gained share post-runtime-fee (since cancelled); the Create franchise and the ad-data install base are the cornered resource being actively attacked.")],
 tr=[("Bull validation","Vector ARR tracks toward ~$1B and Grow stays >20%  ·  ad share holds/expands beyond mobile gaming  ·  GAAP operating margin turns positive  ·  SBC/share count flattens"),
     ("Bear validation","Vector growth decelerates sharply as comps lapse  ·  Create seats/engine share keep leaking to Godot/Unreal  ·  GAAP stays loss-making  ·  share count keeps climbing >5%/yr"),
     ("Reframe needed","if the convertibles refinance on bad terms or Vector reverts to a low-growth engine losing developers, re-rate the terminal toward a dilutive, loss-making software multiple net of debt")],
 gloss=[("Vector","Unity's AI-driven ad engine inside Grow - the turnaround driver, +80% YoY toward ~$1B ARR; whether it sustains ad-share gains beyond mobile gaming is the swing factor."),
        ("Grow vs Create","Grow = the ads/monetization business (~69% of revenue, incl Vector); Create = the engine subscriptions (Unity Pro/Enterprise) - the two reported segments."),
        ("Runtime fee","The 2023 per-install engine pricing (since cancelled) that triggered a developer backlash and gave Godot/Unreal an opening - the Create-franchise bear catalyst."),
        ("Convertible notes","~$2.2B of convertible debt (2026 Notes due Nov-2026) sitting against ~$2.15B cash; the maturity that shapes the equity bridge net of debt."),
        ("FCF margin (ex-SBC)","Free cash flow / revenue net of stock-based comp, against a growing share count; the mature-DCF lever - here dilution, not GAAP FCF, drives the per-share result.")],
 arena="Game-engine + mobile-ad monetization — Unity (the dominant cross-platform engine + the Grow/Vector ad network) vs Epic's Unreal and open-source Godot in engines, and AppLovin in mobile ads; auditing a contested branding + cornered-resource Power against an active developer exodus and dilution.",
 powers=[("scale_economies",2,"Ad-network and engine scale at ~$1.85B revenue give data/cost leverage, but Unity is loss-making and sub-scale vs AppLovin in ads."),
         ("network_economies",2,"Developers + ad demand share the same install base (more games -> more ad inventory -> better targeting), but the loop is weaker than a pure marketplace and contested."),
         ("counter_positioning",1,"Was the accessible cross-platform engine vs costly bespoke tooling; now the incumbent, with Godot the low-cost counter-position after the runtime fee."),
         ("switching_costs",2,"Real once a game is built in Unity, but weak at the franchise edge - the runtime fee proved developers will start new projects on Godot/Unreal."),
         ("branding",3,"The dominant Power: Unity is the default name in mobile/indie game development with a huge install base - but the brand was damaged by the runtime fee and is eroding."),
         ("cornered_resource",3,"The ad-data + engine install base feeding Vector is the genuine asset - nascent and being actively contested, the swing of the whole audit."),
         ("process_power",1,"AI/ML ad-optimization (Vector) is improving fast but unproven and chased by AppLovin; not yet a durable process advantage.")],
 dom="cornered_resource", dur="low",
 rivals=[("AppLovin (APP)","public","The mobile-ad-monetization benchmark Vector is chasing; far more profitable, the Grow/Vector comp.",0.30,0.55,"~30x EV/FCF"),
         ("Epic Games (Unreal)","private","Owns Unreal + Fortnite; the high-end engine taking AAA/console share, the Create threat.",None,None,"private"),
         ("Godot","private","Free, open-source engine that gained indie share post-runtime-fee; the low-cost counter-position.",None,None,"open-source"),
         ("Roblox (RBLX)","public","Adjacent UGC platform competing for creators/developers and ad dollars.",0.25,None,"~loss-making")],
 threats=[("cornered_resource","AppLovin (ad share) + comp lapse","Vector growth decelerates sharply as easy comps roll off and ad share stops expanding beyond mobile gaming."),
          ("branding","Godot + Unreal (engine share)","Create seats/engine share keep leaking as developers start new projects off Unity post-runtime-fee."),
          ("switching_costs","Developer exodus / dilution","GAAP stays loss-making and the share count keeps climbing >5%/yr, so per-share value leaks even as revenue grows.")],
 take="Unity's most genuine Power is a cornered resource - the ad-data plus engine install base feeding Vector - but it is nascent and being actively contested, and the branding leg (the default game engine) was damaged by the runtime fee and is eroding to Godot and Unreal. The Audit: the dominant Power is the contested ad-data/install-base resource (durability low), the live threats are engine-share erosion plus a developer exodus and ~56%-in-five-years SBC dilution, and ~$2.2B convertibles mature into ~$2.15B cash in Nov-2026. That squares with the DCF: even with Vector working and GAAP turning, the base lands -60% because the model carries a thinner ex-SBC margin and a growing share count - this is the most speculative name in the batch, a turnaround bet on Vector with a very wide -93% to +47% distribution, not an FCF compounder.",
)

if __name__ == "__main__":
    build(SPEC)
