#!/usr/bin/env python3
"""NVDA — NVIDIA (NASDAQ) mature-company memo spec. Emits data/_intake/nvda.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1045810). Fiscal year ends late January
(FY22=Jan'22 ... FY26=Jan'26)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="NVDA", company="NVIDIA", exch="NASDAQ", spot=205.19,
 cap=4986.0, sh=24300.0, cash=10.6, net_debt=8.5, rev_b=215.9,
 wl="fcf-megacap", tier=None, themes=["ai-compute"],
 extras=[
   "$10.6B cash vs ~$8.5B debt (~$2B net cash); ~24.3B shares; +$80B buyback authorized, $0.25/quarter dividend",
   "Revenue $215.9B FY26 (+65%); GAAP op margin ~60%; FCF ~$96.7B (~45%); Data Center now ~88% of revenue",
   "World's largest company at ~$5.0T; ATH ~$235 (May), ~$205 now (~+45% TTM); slid post-earnings despite the beat"],
 cq="Can datacenter AI capex compound for years at high-70s% gross margin to justify ~$5T and ~50x FCF, or does a digestion/air-pocket hit a stock priced for perfection?",
 thesis="NVIDIA trades at ~$4,986B (~$205/sh, ~+45% TTM) - the world's largest company at ~50x FCF on $215.9B revenue (+65%), ~60% operating margins, ~$2B net cash. Data Center is ~88% of revenue and grew +92% last quarter at a mid-70s% gross margin, on a clean Blackwell -> Ultra -> Rubin cadence. The DCF asks whether hyperscaler + sovereign AI capex keeps compounding or hits a pause. The finding: the distribution is enormous (ultra-bear -80% to ultra-bull +73%), and even at huge growth the modal case can't justify ~$5T - the weighted read is -25%.",
 chartref=[("history_years",[2022,2023,2024,2025,2026]),
   ("history_revenue",[26.9,27.0,60.9,130.5,215.9]),
   ("history_op_margin",[37.3,15.7,54.1,62.4,60.4]),
   ("history_fcf",[8.1,3.8,27.0,60.9,96.7]),
   ("history_ev_rev",[28,21,25,25,18])],
 p3cfg=[("segment_a","Data Center"),("segment_b","Gaming + Other"),
   ("hist_ent_split",[0.39,0.56,0.78,0.88,0.88]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY22-FY26 history + FY27-FY31 scenario projections  ·  fiscal years end late January  ·  FQ1 FY2027 (rep. May 2026) results",
 sources="Sources: SEC XBRL company facts (CIK 1045810; revenue, GAAP operating income/margin, cash flow, debt), NVIDIA FQ1 FY2027 release (revenue $81.6B +85% YoY, Data Center $75.2B +92% with compute $60.4B / networking $14.8B +199%, non-GAAP gross margin 75.0%, FQ2 guide ~$91B, zero China datacenter revenue), Blackwell Ultra (GB300) sold out through mid-2026 and Rubin on annual cadence (GTC Mar 2026). Revenue modeled as a growth-rate path off FY26; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs AMD, the hyperscaler custom-ASIC programs, and Broadcom.",
 ipo="IPO Jan '99", xmin=-5.2,
 points=[[-5.0,13],[-4.3,33],[-3.5,15],[-2.5,50],[-1.5,135],[-0.8,140],[-0.1,235],[-0.02,205.19]],
 scn={
  "ultra_bear":dict(p=0.15,g=[-0.10,-0.05,0.03,0.05,0.05],fcfm=[0.40,0.40,0.41,0.42,0.42],opm=[0.48,0.48,0.50,0.51,0.51],wacc=0.105,tg=0.025,fs=24400,evr=[8,6,5,4.5,4],evf=[14,13,13,13,13],
    hl="Capex air-pocket; revenue contracts.",
    narr=["The AI capex cycle hits a digestion air-pocket: hyperscalers pause after over-building, Data Center revenue contracts (-10% then -5%), and custom ASICs plus AMD's H2-2026 launches take share at the margin so gross margin compresses toward the low-70s. China stays a structural $0. The compute giant cyclically resets to a slower-growth, lower-margin base.","A cyclical semiconductor whose growth has rolled over earns a mid-teens terminal multiple -> DCF ~$40 (-80%). Net cash is immaterial against a ~$5T cap; this is what a priced-for-perfection name does when perfection breaks."],
    pr="The genuine bear: the entire thesis rides on hyperscaler capex holding, custom silicon (OpenAI-Broadcom 10GW) + AMD (Meta ~$100B, OpenAI 6GW) all land H2-2026, and the stock already slid at $5T despite a +85% quarter. 15% weight on a real digestion/share-loss break."),
  "bear":dict(p=0.25,g=[0.12,0.08,0.06,0.06,0.06],fcfm=[0.42,0.43,0.44,0.44,0.45],opm=[0.55,0.56,0.57,0.57,0.58],wacc=0.095,tg=0.03,fs=24400,evr=[12,10,8,7,6.5],evf=[18,17,16,16,16],
    hl="Growth decelerates hard; share erodes.",
    narr=["Demand keeps growing but decelerates fast as the first wave of build-out matures: +12% then high-single-digit as custom ASICs and AMD chip away GPU share and pricing, holding gross margin in the high-50s/low-60s operating. The annual cadence ships but each generation no longer doubles the installed base; sovereign + diversified demand cushions, not offsets.","DCF ~$77 (-63%) - a still-large, still-profitable franchise whose hyper-growth has normalized is worth far below a $5T price; the market's premium assumes years of compounding the bear doesn't deliver."],
    pr="Growth deceleration plus custom-silicon/AMD share loss is the central pull on a name lapping +65% FY26 revenue; even mid-teens forward growth at high margins leaves the price stretched. 25% as the plausible 'grows but normalizes' path."),
  "base":dict(p=0.32,g=[0.40,0.25,0.16,0.12,0.10],fcfm=[0.44,0.45,0.46,0.47,0.47],opm=[0.58,0.59,0.60,0.60,0.60],wacc=0.09,tg=0.035,fs=24300,evr=[16,13,11,10,9.5],evf=[22,20,19,19,19],
    hl="Capex holds; cadence extends; still rich.",
    narr=["The modal path: datacenter AI capex holds, Blackwell Ultra ramps into Rubin on the annual cadence, and Data Center compounds (+40% then decelerating) at a defended ~60% operating margin while networking (+199% last quarter) extends the full-rack systems franchise. Revenue roughly doubles over the window; China remains $0. A genuinely dominant, fast-growing compute platform - but already priced for it.","DCF ~$159 (-23%) - even with capex holding and the cadence intact, ~50x FCF and a ~19x terminal multiple on a company this size leaves the modal case below today's price; the franchise is excellent and the entry is rich."],
    pr="Requires hyperscaler + sovereign capex to keep compounding and the cadence to ship without a share break - consistent with a sold-out backlog and FQ2 guide ~$91B, but not a step-change beyond it. 32% as the central, still-negative outcome at a $5T cap."),
  "bull":dict(p=0.20,g=[0.50,0.32,0.21,0.15,0.12],fcfm=[0.45,0.47,0.48,0.49,0.49],opm=[0.60,0.61,0.62,0.62,0.62],wacc=0.085,tg=0.04,fs=24200,evr=[20,16,14,12,11],evf=[26,24,23,23,23],
    hl="Capex holds; Rubin extends the cadence.",
    narr=["Hyperscaler capex holds and broadens: the Rubin generation extends the annual cadence, networking and full-rack systems compound the moat beyond the GPU, sovereign deployments (Saudi HUMAIN ~$20B, UAE) and diversified AI clouds (~50% of Data Center) add a durable second leg, and gross margin stays mid-70s. Demand keeps outrunning supply; CUDA + the developer ecosystem hold share against ASICs and AMD.","DCF ~$246 (+20%) - if capex holds and the cadence extends, the franchise grows into and past the multiple; this is the core of the bull and where the price is defensible."],
    pr="Demand outrunning supply, +92% Data Center, +199% networking and a sold-out Blackwell Ultra backlog make sustained compounding credible if the capex cycle doesn't pause. 20% weight on capex holding and Rubin extending the run."),
  "ultra_bull":dict(p=0.08,g=[0.58,0.40,0.28,0.21,0.17],fcfm=[0.46,0.48,0.50,0.51,0.51],opm=[0.61,0.62,0.63,0.63,0.63],wacc=0.082,tg=0.04,fs=24000,evr=[24,20,17,15,14],evf=[28,26,25,25,25],
    hl="AI build-out runs for years; full platform.",
    narr=["The full second act: AI infrastructure spend compounds for years across hyperscale, sovereign and enterprise, NVIDIA stays the platform standard through Rubin and beyond, networking + software + the CUDA ecosystem entrench an end-to-end systems moat, and gross margin holds low-to-mid-70s as supply scales. Revenue more than doubles at peak margins with no meaningful share loss.","DCF ~$355 (+73%) - the build-out runs and NVIDIA captures it as the standard platform; ~8% probability, the asymmetric upside the price embeds beyond the modal case."],
    pr="Everything works - capex compounds for years AND the cadence holds AND CUDA/networking entrench the platform AND ASICs/AMD stay marginal. ~8%, the long-duration AI-infrastructure tail."),
 },
 wr=[("Ultra Bear 15%","Capex air-pocket; revenue contracts; ~$40 (-80%)."),
     ("Bear 25%","Growth decelerates hard; share erodes; ~$77 (-63%)."),
     ("Base 32%","Capex holds; cadence extends; still rich; ~$159 (-23%)."),
     ("Bull 20%","Capex holds; Rubin extends cadence; ~$246 (+20%)."),
     ("Ultra Bull 8%","AI build-out runs for years; ~$355 (+73%).")],
 pb=[("~50x FCF on the world's largest company.","~$96.7B FCF and ~60% operating margins, but at a ~$5T cap the modal DCF is still ~-23% - the price, not the business, is the constraint; the distribution does the talking."),
     ("The single swing factor is datacenter capex.","The whole valuation hinges on hyperscaler + sovereign AI spend compounding for years; capex holding is the bull (+20%), a digestion/air-pocket is the ultra-bear (-80%)."),
     ("China datacenter is a structural $0.","Results and guidance assume ~no China; Beijing steered firms away and Huawei is entrenching - a permanently lost ~$15-50B/yr TAM already out of the numbers, not a future risk."),
     ("Competition all lands H2-2026.","AMD MI450/Helios (OpenAI 6GW, Meta ~$100B) and OpenAI-Broadcom 10GW custom ASICs ship H2-2026; the GPU monopoly erodes at the margin even if NVIDIA stays the leader."),
     ("The systems moat is more than the GPU.","Networking +199% and CUDA + the developer ecosystem make the full-rack platform stickier than a chip - the durability case for the bull/ultra-bull, but already in the price.")],
 tr=[("Bull validation","hyperscaler capex guidance keeps rising  ·  Rubin samples Q4-2026 / volumes Q1-2027 on cadence  ·  Data Center growth + networking stay strong  ·  gross margin holds mid-70s  ·  sovereign/diversified demand keeps building"),
     ("Bear validation","a major hyperscaler cuts or pauses AI capex  ·  custom ASICs / AMD take visible Data Center share  ·  gross margin slips toward low-70s on pricing  ·  backlog/booking commentary softens  ·  a guide-vs-miss on Data Center"),
     ("Reframe needed","if datacenter AI capex hits a sustained digestion/air-pocket or custom silicon structurally takes share, the cadence stops compounding - re-rate the terminal toward a cyclical-semiconductor multiple on a normalized base")],
 gloss=[("Data Center","NVIDIA's dominant segment (~88% of revenue, +92% last quarter) - GPUs (compute) + networking for AI training/inference; the whole thesis rides on its growth and margin."),
        ("Hyperscaler capex","Cloud-provider (Microsoft/Amazon/Google/Meta) capital spending on AI infrastructure - the demand source; whether it holds or pauses is the single biggest 5-year swing factor."),
        ("Annual cadence (Blackwell -> Rubin)","NVIDIA's once-a-year new-architecture rhythm (Blackwell -> Blackwell Ultra/GB300 -> Rubin); sustaining it is how it stays ahead of ASICs and AMD."),
        ("Custom ASICs","Purpose-built AI chips (OpenAI-Broadcom 10GW, hyperscaler in-house silicon) that fragment GPU procurement - the live threat to NVIDIA's share at the margin."),
        ("FCF margin","Free cash flow / revenue (~45% FY26); the mature-DCF swing factor - whether high-70s% gross margin and growth convert to free cash flow as capex and the cadence scale.")],
 arena="AI accelerators / datacenter compute - NVIDIA (GPUs + networking + the CUDA software platform, ~88% Data Center) vs AMD, the hyperscaler custom-ASIC programs (OpenAI-Broadcom, in-house silicon), and Broadcom; auditing a cornered-resource (CUDA) + scale Power against custom silicon and a credible #2.",
 powers=[("scale_economies",4,"Massive R&D and supply scale at $215.9B revenue funds a once-a-year architecture cadence rivals struggle to match; the leader's volume self-reinforces."),
         ("network_economies",4,"The CUDA developer ecosystem - millions of developers, libraries, frameworks tuned to NVIDIA - is a genuine two-sided network that compounds with installed base."),
         ("counter_positioning",1,"None meaningful now - NVIDIA is the incumbent being attacked by lower-cost ASICs/AMD, not the counter-positioner."),
         ("switching_costs",4,"Code, models and full racks are written/optimized to CUDA + NVIDIA networking; re-platforming to ASICs or AMD is costly and risky - a real lock-in."),
         ("branding",2,"Strong reputation as the AI-compute standard, but the buy is governed by performance/TCO and ecosystem, not brand premium."),
         ("cornered_resource",5,"The dominant Power: CUDA + the integrated GPU/networking/software stack is a ~two-decade head start rivals cannot quickly replicate - the moat's foundation."),
         ("process_power",3,"Deep systems/packaging and supply-chain (CoWoS) execution feeding the annual cadence; real, but partly bought capacity others can also access.")],
 dom="cornered_resource", dur="high",
 rivals=[("AMD","public","The credible #2; MI450/Helios ships H2-2026 with OpenAI (6GW) and Meta (~$100B) commitments - the direct GPU challenger.",0.30,0.25,"~30x EV/FCF"),
         ("Custom ASICs (hyperscalers)","public","In-house AI silicon (Google TPU, plus new programs) fragmenting GPU procurement; reduces NVIDIA's wallet share at the largest buyers.",None,None,"captive"),
         ("OpenAI-Broadcom","public","10GW of custom accelerators (Broadcom-designed) landing H2-2026 - the marquee defection from merchant GPUs to bespoke silicon.",None,None,"~partnership"),
         ("Huawei (Ascend)","private","Entrenching in China as the closed-market alternative now that NVIDIA datacenter revenue there is $0; not a US/global threat yet.",None,None,"private")],
 threats=[("cornered_resource","Custom ASICs (OpenAI-Broadcom, hyperscaler in-house silicon)","Custom-silicon deployments take visible Data Center share and slow NVIDIA's growth/pricing as buyers re-platform off CUDA."),
          ("switching_costs","AMD (MI450/Helios, H2-2026)","Major accounts (OpenAI, Meta) shift meaningful training/inference to AMD, proving the CUDA lock-in is breachable at scale."),
          ("scale_economies","A datacenter AI capex digestion/air-pocket","Hyperscaler capex pauses, the annual cadence stops compounding the installed base, and the scale advantage stops self-reinforcing.")],
 take="NVIDIA's dominant Power is a cornered resource - CUDA plus the integrated GPU/networking/software stack, reinforced by switching costs, scale and a developer-ecosystem network - and it's durable (high). The live threat is the H2-2026 wave: AMD's MI450 and the OpenAI-Broadcom custom ASICs erode GPU share at the margin even if NVIDIA stays the standard, and China datacenter is a permanent $0. The Audit squares with the DCF: the Power is real, but the swing factor is whether datacenter AI capex holds or hits an air-pocket, and at ~50x FCF on ~$5T even the modal capex-holds case lands ~-23% - the distribution is the finding, weighted -25%.",
)

if __name__ == "__main__":
    build(SPEC)
