#!/usr/bin/env python3
"""Batch-B group 2: ABNB, UBER. Reuses build() from gen_b1."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPECS=[
# ============================== ABNB ==============================
dict(ticker="ABNB",company="Airbnb",exch="NASDAQ",spot=133.0,cap=79.0,sh=650.0,cash=9.5,rev_b=12.24,
 wl="fcf-plus-plus-growth",tier="Med-High",themes=["travel-mobility-services"],
 extras=["~$9.5B net cash; ~650M diluted shares; ~$3.8B/yr buyback offsets SBC","Revenue $12.24B FY25 (+10%, decel from +40%); 38% FCF margin, $4.6B FCF","~15x EV/FCF; Experiences/Services relaunch (2025) the swing optionality"],
 cq="Does Airbnb's ~15x EV/FCF fairly price a decelerating but FCF-gushing travel network — or is the Experiences/Services optionality + international runway underpriced?",
 thesis="Airbnb trades at ~$79B (≈$133/sh) — ~15x EV/FCF on a $4.6B-FCF, 38%-margin two-sided travel network with ~$9.5B net cash. Growth has decelerated (+40%→+10%, guided low-mid-teens) and regulation (Barcelona, NYC) caps dense-urban supply. The mature DCF asks whether the verb-grade brand + network defend the FCF and whether Experiences/Services + international re-accelerate growth. The finding: at ~15x FCF for this quality the modal case implies modest undervaluation — the premium-to-Booking is on P/E, not on the cash flow the DCF values.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),("history_revenue",[5.99,8.4,9.92,11.1,12.24]),("history_op_margin",[7.2,21.5,15.3,23.0,20.8]),("history_fcf",[1.6,3.4,3.8,4.5,4.6]),("history_ev_rev",[10.0,7.0,6.0,6.0,5.7])],
 p3cfg=[("segment_a","Core stays"),("segment_b","Experiences/Services"),("hist_ent_split",[0.99,0.99,0.98,0.97,0.96]),("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  calendar fiscal year  ·  FY2025 10-K (Feb'26)",
 sources="Sources: Airbnb FY2025 10-K (revenue $12.24B, FCF $4.6B/38%, ~$9.5B net cash, GBV $91.3B), Q1'26 results. Revenue as a growth-rate path off FY25; FCF = revenue x FCF margin (use ~38% structural, not the seasonal Q1 64%); Gordon terminal. EV/FCF vs Booking/Expedia.",
 ipo="IPO Dec '20",xmin=-5.5,points=[[-5.4,145.0],[-5.0,210.0],[-4.0,90.0],[-3.0,130.0],[-2.0,150.0],[-1.5,160.0],[-1.0,140.0],[-0.5,120.0],[-0.05,133.0]],
 scn={
  "ultra_bear":dict(p=0.12,g=[0.04,0.04,0.03,0.03,0.03],fcfm=[0.36,0.36,0.36,0.36,0.36],opm=[0.20,0.20,0.20,0.21,0.21],wacc=0.10,tg=0.02,fs=650,evr=[5.0,4.5,4.0,4.0,3.5],evf=[13,12,12,12,12],
    hl="Regulation + maturation; growth stalls.",
    narr=["City STR bans spread (Barcelona's 2028 phase-out as the template), growth decays toward GDP-plus, and Experiences/Services never monetizes. Revenue grows only ~3%; the premium multiple de-rates toward Booking's.","DCF ~$106 (-20%) — a great FCF machine, but priced for the growth it has stopped delivering."],
    pr="Regulation is the structural bear: NYC listings fell ~92%, Spain fined Airbnb EUR65M. 12% weight on bans + maturation capping the network."),
  "bear":dict(p=0.25,g=[0.07,0.07,0.06,0.06,0.05],fcfm=[0.37,0.37,0.37,0.38,0.38],opm=[0.21,0.21,0.22,0.22,0.22],wacc=0.095,tg=0.025,fs=650,evr=[6.5,6.0,5.5,5.5,5.0],evf=[15,14,14,14,14],
    hl="Decelerates to high-single; regulation bites.",
    narr=["Growth settles in the high-single digits as Booking out-executes in alternative accommodations and regulation nibbles supply; FCF margin holds ~37%.","DCF ~$137 (+3%) — roughly fair; the network defends the cash even as growth matures."],
    pr="The law-of-large-numbers + Booking competition path. 25% weight — a very plausible 'matures gracefully' outcome."),
  "base":dict(p=0.35,g=[0.10,0.11,0.10,0.09,0.09],fcfm=[0.38,0.38,0.39,0.39,0.39],opm=[0.22,0.23,0.23,0.24,0.24],wacc=0.09,tg=0.03,fs=650,evr=[8.0,7.5,7.0,6.5,6.5],evf=[17,16,16,16,16],
    hl="Low-mid-teens growth; Experiences ramps.",
    narr=["The modal path: revenue compounds low-mid-teens (the 2026 guide), Experiences/Services begins to monetize, and international under-penetration carries the network at a 38-39% FCF margin.","DCF ~$183 (+37%). A verb-grade FCF machine at ~15x FCF is mispriced for this quality if growth holds in the teens."],
    pr="Requires the guided low-mid-teens growth + modest Experiences/Services monetization. 35% as the central outcome — the network + brand are genuinely durable."),
  "bull":dict(p=0.20,g=[0.12,0.14,0.13,0.12,0.11],fcfm=[0.38,0.39,0.40,0.40,0.40],opm=[0.23,0.24,0.25,0.25,0.26],wacc=0.085,tg=0.035,fs=650,evr=[10.0,9.5,9.0,8.5,8.5],evf=[20,19,19,19,19],
    hl="Experiences/Services + international re-accel.",
    narr=["Experiences/Services becomes a real second leg, international scales, and AI-driven conversion lifts the take rate — revenue re-accelerates to the mid-teens at a 40% FCF margin.","DCF ~$242 (+82%) — the optionality the relaunch is buying actually pays off."],
    pr="Experiences/Services monetizes into a needle-mover + international compounds. ~20%; the relaunch is early but credible."),
  "ultra_bull":dict(p=0.08,g=[0.14,0.17,0.16,0.15,0.14],fcfm=[0.39,0.40,0.41,0.41,0.41],opm=[0.24,0.25,0.26,0.27,0.27],wacc=0.08,tg=0.035,fs=650,evr=[12.0,11.5,11.0,10.5,10.5],evf=[23,22,22,22,22],
    hl="End-to-end travel hub; AI concierge.",
    narr=["Airbnb becomes an end-to-end travel/lifestyle platform (homes + services + experiences + AI concierge), expanding TAM well beyond rentals at peak network margins.","DCF ~$306 (+130%) — the platform vision fully realized; ~8% probability."],
    pr="The full 'Airbnb everything' hub + AI concierge. ~8%, the asymmetric upside the Experiences/Services bet is really for.")},
 wr=[("Ultra Bear 12%","Regulation + maturation; ~$106 (-20%)."),("Bear 25%","High-single growth; regulation; ~$137 (+3%)."),("Base 35%","Low-mid-teens; Experiences ramps; ~$183 (+37%)."),("Bull 20%","Experiences/intl re-accel; ~$242 (+82%)."),("Ultra Bull 8%","End-to-end travel hub; ~$306 (+130%).")],
 pb=[("~15x EV/FCF, 38% FCF margin.","A verb-grade two-sided network throwing off $4.6B FCF at a 38% margin — priced like a maturing OTA, not a durable platform."),
     ("$9.5B net cash, working-capital-positive.","Guest pre-payments fund the float -> structurally high FCF conversion; fortress balance sheet, ~$3.8B/yr buyback."),
     ("Network economies + a verb brand.","'Airbnb' is the default for alternative accommodations; direct traffic lowers CAC vs OTAs — the two-sided liquidity moat."),
     ("Experiences/Services optionality is free.","The 2025 relaunch expands TAM beyond rentals; unmonetized today, so any traction is upside the multiple doesn't pay for."),
     ("International under-penetrated.","Latin America / Asia-Pacific grow faster than core — a multi-year runway the US-centric view misses.")],
 tr=[("Bull validation","revenue re-accelerates to mid-teens  ·  Experiences/Services monetizes into a reported needle-mover  ·  take rate rises  ·  international outgrows core"),
     ("Bear validation","growth decays to high-single  ·  major-metro bans spread  ·  Booking out-grows ABNB in alternative accommodations  ·  multiple de-rates toward peers"),
     ("Reframe needed","if a flagship market structurally bans STRs or Google disintermediates search, re-rate the network durability + terminal multiple")],
 gloss=[("GBV / take rate","Gross booking value (~$91B FY25) x ~13.4% take = revenue; the two metrics that drive the model."),
        ("Network economies","Helmer Power: more hosts -> more guests -> more hosts; the two-sided liquidity flywheel that is Airbnb's core moat."),
        ("Experiences / Services","The 2025 relaunch (locally-hosted activities + in-stay services); the TAM-expanding optionality, unmonetized today."),
        ("FCF margin","Free cash flow / revenue (~38% structural; ignore the seasonal Q1 ~64% float build) — the mature-DCF lever."),
        ("STR regulation","Short-term-rental bans/registration (Barcelona 2028 phase-out, NYC -92%) — the structural cap on dense-urban supply.")],
 arena="Travel / lodging + experiences — Airbnb (two-sided STR marketplace, ~8M listings, verb-grade brand) vs Booking, Expedia/Vrbo, Google Travel, hotels; defending a network + brand Power as growth matures and regulation tightens.",
 powers=[("scale_economies",2,"Fixed platform/trust-&-safety/marketing spread over $91B GBV -> best-in-class ~38% FCF margin."),
         ("network_economies",3,"The dominant Power: two-sided host<->guest density; more hosts -> more guests -> more hosts."),
         ("counter_positioning",1,"Was the disruptor vs hotels; incumbents (Booking, Vrbo) have matched the STR model."),
         ("switching_costs",1,"Weak-medium: hosts multi-list; guests are promiscuous."),
         ("branding",3,"'Airbnb' is a verb; direct-traffic advantage lowers CAC vs OTAs — durable demand-side Power."),
         ("cornered_resource",1,"No durable exclusive asset; supply is replicable."),
         ("process_power",2,"Matching/pricing/trust-and-safety execution at scale.")],
 dom="network_economies",dur="medium-high",
 rivals=[("Booking Holdings","public","Larger GBV; pushing into alternative accommodations (>8M listings, growing faster than ABNB there).",0.13,0.36,"~15.6x P/E"),
         ("Expedia / Vrbo","public","#3 OTA; Vrbo the direct STR competitor.",0.06,0.15,"~11.8x P/E"),
         ("Google Travel","incumbent-division","Disintermediation risk at the search layer.",None,None,"n/a"),
         ("Hotels / chains","incumbent","Direct booking + loyalty; the alternative for urban stays.",0.05,None,"varies")],
 threats=[("network_economies","Booking in alternative accommodations","Booking out-grows ABNB in alt-accommodations bookings for 2+ years."),
          ("branding","Google Travel disintermediation","Paid-search dependence rises and direct-traffic share falls."),
          ("scale_economies","STR regulation","A flagship metro structurally bans STRs, or registration regimes materially shrink supply.")],
 take="Airbnb's network-economies + verb-grade brand are genuinely durable on the demand side (direct traffic, two-sided liquidity), and the ~38% FCF margin is best-in-class. The terminal-value debate is not a competitor out-networking them — it's regulation (dense-urban supply caps) + growth maturation. At ~15x EV/FCF the cash flow is priced cheaply for the quality; the Experiences/Services relaunch is the unpaid-for optionality, and the sign hinges on whether growth holds in the teens or decays to GDP-plus."),

# ============================== UBER ==============================
dict(ticker="UBER",company="Uber Technologies",exch="NYSE",spot=70.40,cap=145.0,sh=2036.0,cash=2.7,rev_b=52.0,
 wl="fcf-megacap",tier=None,themes=["travel-mobility-services"],
 extras=["~$2.7B net cash; ~2.04B shares; $20B buyback authorization (2025)","Revenue $52B / gross bookings $193.5B FY25 (+19% GB); $9.76B FCF (+40% YoY), ~14x EV/FCF","Down ~30% from highs on AV fear; ads >$2B run-rate, Uber One ~50M members"],
 cq="Is Uber a dominant FCF-inflecting mobility/delivery network at ~14x EV/FCF — or does autonomy commoditize its driver-marketplace and erode the network toll?",
 thesis="Uber trades at ~$145B (≈$70/sh, down ~30% on AV fear) — ~14x EV/FCF on $9.76B FCF (growing 40%+), $193.5B gross bookings (+19%), net cash and a $20B buyback. The mature DCF asks whether the two-sided network + advertising (>$2B run-rate) + delivery-margin ramp compound, or whether Waymo/Tesla bypass the marketplace. The finding: at 14x FCF for a network compounding GB ~mid-teens with expanding margins, the modal case implies meaningful undervaluation — but a genuine AV-disruption ultra-bear is -44%, so the sign is a bet on Uber remaining the AV demand-aggregator.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),("history_revenue",[17.5,31.9,37.3,44.0,52.0]),("history_op_margin",[-22.0,-5.7,3.0,6.4,10.7]),("history_fcf",[-0.7,0.4,3.4,6.9,9.76]),("history_ev_rev",[8.0,4.0,4.0,3.5,2.9])],
 p3cfg=[("segment_a","Mobility"),("segment_b","Delivery"),("hist_ent_split",[0.55,0.56,0.57,0.57,0.57]),("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  calendar fiscal year  ·  FY2025 + Q1'26 results",
 sources="Sources: Uber FY2025 results (revenue $52B, GB $193.5B, adj EBITDA $8.73B, FCF $9.76B), Q1'26 (GB +25%). Revenue as a growth-rate path off FY25 (or GB x ~27% take); FCF = revenue x FCF margin; Gordon terminal. Equity stakes (Aurora ~$1.4B) immaterial -> no SOTP. EV/FCF vs DASH/LYFT.",
 ipo="IPO May '19",xmin=-7.2,points=[[-7.0,42.0],[-6.0,30.0],[-5.0,45.0],[-4.0,25.0],[-3.0,44.0],[-2.0,62.0],[-1.0,85.0],[-0.6,102.0],[-0.3,80.0],[-0.05,70.4]],
 scn={
  "ultra_bear":dict(p=0.15,g=[0.02,0.02,0.01,0.0,0.0],fcfm=[0.15,0.15,0.14,0.14,0.14],opm=[0.06,0.06,0.05,0.05,0.05],wacc=0.11,tg=0.01,fs=1950,evr=[2.0,1.8,1.6,1.5,1.4],evf=[10,9,9,9,9],
    hl="AV bypasses the marketplace; toll erodes.",
    narr=["Waymo/Tesla scale direct-to-consumer robotaxi fleets that don't need Uber's demand layer, and driver reclassification raises the labor-cost base. Gross bookings stall and the take-rate toll compresses.","DCF ~$40 (-44%) — the network's value collapses if it's disintermediated from the supply side."],
    pr="The autonomy paradox bear: Uber's biggest hedge (platform for all AVs) is its biggest vulnerability if a winning fleet goes direct. 15% weight on real disruption."),
  "bear":dict(p=0.27,g=[0.06,0.06,0.05,0.05,0.04],fcfm=[0.18,0.18,0.18,0.19,0.19],opm=[0.09,0.10,0.10,0.11,0.11],wacc=0.10,tg=0.02,fs=1950,evr=[2.6,2.4,2.3,2.2,2.1],evf=[12,12,12,12,12],
    hl="AV pressure; growth decelerates.",
    narr=["AV uncertainty and competition slow GB to mid-single digits and cap margin expansion; Uber stays profitable but the network thesis is contested.","DCF ~$75 (+6%) — roughly fair; the FCF defends the floor while the AV question hangs over the multiple."],
    pr="AV pressure + regulation + competition decelerate the network without breaking it. 27% weight as the 'contested but intact' path."),
  "base":dict(p=0.33,g=[0.10,0.10,0.09,0.08,0.08],fcfm=[0.19,0.20,0.20,0.21,0.21],opm=[0.11,0.12,0.13,0.13,0.14],wacc=0.095,tg=0.025,fs=1930,evr=[3.2,3.1,3.0,2.9,2.9],evf=[15,14,14,14,14],
    hl="Stays the AV aggregator; ads + delivery margin.",
    narr=["The modal path: Uber remains the demand aggregator for AV fleets, advertising scales past $3B, delivery margins converge toward mobility's, and GB compounds low-double-digits at a rising FCF margin.","DCF ~$110 (+55%). At 14x FCF the market over-discounts the AV threat relative to the network's durability and the FCF ramp."],
    pr="Uber stays the AV demand layer (Waymo productivity data supports it) and ads/delivery margins compound. 33% as the central outcome."),
  "bull":dict(p=0.18,g=[0.13,0.13,0.11,0.10,0.10],fcfm=[0.21,0.22,0.22,0.23,0.23],opm=[0.13,0.14,0.15,0.15,0.16],wacc=0.09,tg=0.03,fs=1900,evr=[3.8,3.7,3.6,3.5,3.5],evf=[17,17,17,17,17],
    hl="Network holds; ads scale; AV accretive.",
    narr=["The network power holds, AV partnerships prove accretive (cheaper rides expand the TAM), advertising + Uber One drive a software-like margin mix, and GB compounds mid-teens.","DCF ~$155 (+120%) — the FCF machine re-rates as the AV fear proves overblown."],
    pr="AV becomes a tailwind (Uber as the aggregator for cheaper AV rides) + ads scale. ~18%; the productivity data hints at it."),
  "ultra_bull":dict(p=0.07,g=[0.16,0.15,0.13,0.12,0.11],fcfm=[0.22,0.24,0.24,0.25,0.25],opm=[0.14,0.15,0.16,0.16,0.17],wacc=0.085,tg=0.03,fs=1880,evr=[4.4,4.3,4.2,4.1,4.1],evf=[19,19,18,18,18],
    hl="The AV demand layer; advertising platform.",
    narr=["Uber becomes the indispensable demand/marketplace layer for the entire AV ecosystem plus a >$10B advertising platform, compounding GB high-teens at peak margins.","DCF ~$202 (+187%) — the platform-for-all-autonomy outcome; ~7% probability."],
    pr="Uber is the demand layer every AV fleet needs + a major ad platform. ~7%, the asymmetric upside the AV-discounted entry is buying.")},
 wr=[("Ultra Bear 15%","AV bypasses marketplace; ~$40 (-44%)."),("Bear 27%","AV pressure; decel; ~$75 (+6%)."),("Base 33%","Stays AV aggregator; ads + delivery; ~$110 (+55%)."),("Bull 18%","Network holds; AV accretive; ~$155 (+120%)."),("Ultra Bull 7%","The AV demand layer; ~$202 (+187%).")],
 pb=[("~14x EV/FCF on $9.76B FCF growing 40%+.","A dominant two-sided network priced at a mid-teens FCF multiple while FCF is still inflecting steeply — the AV fear is doing the discounting."),
     ("Advertising is the hidden high-margin lever.",">$2B run-rate, +50%, near-100% incremental margin — the single biggest take-rate/margin-expansion driver, embedded in the segments."),
     ("Uber One + multi-product flywheel.","~50M members driving ~half of gross bookings; rides+eats+ads on one app deepen switching costs."),
     ("AV could be a tailwind, not just a threat.","Waymo on Uber outproduced 99% of human drivers; Uber's aggregator strategy + ~$10B AV commitments position it as the demand layer."),
     ("$20B buyback, net cash.","~7% FCF yield funding a large buyback at a depressed multiple — accretive.")],
 tr=[("Bull validation","autonomous trips scale on Uber's network profitably  ·  advertising passes $3B run-rate  ·  delivery margin converges toward mobility's 8% of GB  ·  GB stays mid-teens+"),
     ("Bear validation","a major AV fleet (Waymo/Tesla) scales direct-to-consumer  ·  driver reclassification raises the cost base  ·  GB decelerates to mid-single"),
     ("Reframe needed","if AV demonstrably disintermediates the driver-marketplace (fleets bypass Uber's demand), re-rate the network durability + terminal toward a commoditized-logistics multiple")],
 gloss=[("Gross bookings (GB)","Total value of rides+eats+freight (~$193.5B FY25); revenue is GB x ~27% take rate — the top of the model."),
        ("AV / autonomy paradox","Uber's strategy to be the demand aggregator for all AV fleets is also its vulnerability — a winning fleet could bypass the marketplace."),
        ("Network economies","Helmer Power: more riders <-> more drivers -> lower wait/price -> more riders; the deepest two-sided marketplace globally."),
        ("Uber One","~50M-member subscription driving ~half of gross bookings; the frequency/retention + switching-cost flywheel."),
        ("FCF margin","Free cash flow / revenue (~19% FY25, rising); the mature-DCF lever as ads + delivery margin mix up.")],
 arena="Global mobility + delivery — Uber (two-sided rides + eats network, ads, Uber One) vs Lyft (rides), DoorDash (delivery), and the autonomous-vehicle stack (Waymo, Tesla); defending a network Power whose driver-supply side autonomy could commoditize.",
 powers=[("scale_economies",3,"Largest GB base spreads fixed tech/insurance/support; data + routing density."),
         ("network_economies",3,"The dominant Power: two-sided liquidity flywheel, deepest marketplace globally."),
         ("counter_positioning",1,"Was the disruptor; AV-native players could counter-position against the human-driver model."),
         ("switching_costs",2,"Uber One (~50M, ~half of GB) + cross-product habit; real but not deep."),
         ("branding",2,"'Get an Uber' verb; default global ride-hail brand."),
         ("cornered_resource",1,"No durable exclusive asset; the AV stack is the cornered resource Uber lacks (Waymo/Tesla have it)."),
         ("process_power",2,"Matching/pricing-algorithm + multi-product operational edge.")],
 dom="network_economies",dur="medium-high",
 rivals=[("Waymo (Alphabet)","incumbent-division","AV leader; runs on Uber in Austin/Atlanta but separating in Dallas/SF — partner turning competitor.",None,None,"n/a"),
         ("Tesla","public","Camera-only robotaxi bet; could go direct-to-consumer and bypass the marketplace.",None,None,"n/a"),
         ("DoorDash","public","US delivery leader; richer EV/EBITDA, faster GOV growth.",0.27,None,"~25x EV/EBITDA"),
         ("Lyft","public","Distant #2 in US rides; sub-scale margin.",0.15,0.029,"sub-scale")],
 threats=[("network_economies","Waymo/Tesla direct-to-consumer AV","A major AV fleet scales D2C robotaxi without Uber's demand layer."),
          ("counter_positioning","Driver reclassification","A major-jurisdiction gig-worker ruling structurally raises the labor-cost base."),
          ("scale_economies","DoorDash / Lyft competition","DoorDash extends its delivery lead or Lyft regains rides share, compressing take rate.")],
 take="Uber's network economies + scale are genuinely dominant — the deepest two-sided marketplace, now throwing off ~$10B FCF with advertising and delivery margins still ramping. The entire terminal-value debate is the autonomy paradox: the network power is durable only if Uber remains the demand aggregator for AV fleets. At ~14x EV/FCF the market is pricing meaningful AV-disruption risk; the sign of the memo hinges on whether autonomy commoditizes the driver-supply side (ultra-bear -44%) or Uber tolls the cheaper AV rides (base +55%)."),
]
for sp in SPECS: build(sp)
