#!/usr/bin/env python3
"""WRBY — Warby Parker (NYSE) mature-company memo spec. Emits data/_intake/wrby.yml
via the reusable Batch-B builder (gen_b1.build). Numerics modeled in model_mature;
op-margin history is GAAP (us-gaap:OperatingIncomeLoss / revenue) from SEC XBRL
(CIK 1504776; direct-listed Sep 2021)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="WRBY", company="Warby Parker", exch="NYSE", spot=26.46, cap=3.25, sh=122.7, cash=0.286, net_debt=0.0, rev_b=0.872,
 wl="fun-speculative", tier="Med", themes=["premium-consumer-brands"],
 extras=[
   "Net cash +$286M (no debt); ~122.7M shares; SBC ~5% of revenue (~$12M/qtr), a live dilution drag",
   "Revenue $872M FY25 (+13%); GAAP op margin -0.6% (still a small loss); FCF +$30M (~3%); adj EBITDA ~12.2%",
   "~$26, up ~13-16% YTD, 52-wk $14.96-$31.00; added to S&P SmallCap 600 (Jun 2026); ~3x sales"],
 cq="Does store-led scale finally drive Warby Parker's EBITDA margin from ~12% toward high-teens/20% with durable GAAP profit and FCF — or stay a thin-margin, decelerating brand priced for an inflection?",
 thesis="Warby Parker trades at ~$3.25B (~$26.46, up ~13-16% YTD) — ~3x sales on $872M revenue growing ~13%, net cash, but only a ~12% adj-EBITDA margin and razor-thin GAAP profit that flips between a small profit and breakeven. The bull is store-led operating leverage finally lifting EBITDA toward high-teens/20% as the unit base scales from 323 toward ~900-1,000+, plus a Google AI-smart-glasses call-option outside guidance; the bear is decelerating customer growth (+4.8%), gross-margin compression, and the inflection never arriving. At ~3x sales the price already embeds the margin ramp, so the weighted finding is -42.1% and the modal case lands -43% — priced for an inflection that has not yet shown up.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[0.54,0.60,0.67,0.77,0.87]),
   ("history_op_margin",[-26.6,-18.6,-10.7,-3.9,-0.6]),
   ("history_fcf",[-0.06,-0.02,0.01,0.02,0.03]),
   ("history_ev_rev",[5,4,3.5,3,3.4])],
 p3cfg=[("segment_a","Retail (stores)"),("segment_b","E-commerce"),
   ("hist_ent_split",[0.55,0.62,0.68,0.70,0.72]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  Q1 FY2026 results + FY26 guidance",
 sources="Sources: SEC XBRL company facts (CIK 1504776; revenue, GAAP operating income/margin, cash flow, no debt), Warby Parker Q1 FY2026 release (revenue $242.4M/+8.3%, 2.69M active customers/+4.8% TTM, revenue/customer $331, gross margin 54.0%, adj EBITDA $29.6M/12.2%, GAAP net income +$3.2M, FCF +$8.4M), FY26 guide ($959-976M revenue, ~12.2% adj EBITDA), 323 stores end-2025 (+47), Google Android XR / Gemini glasses partnership ($150M committed, not in guidance). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/EBITDA vs eyewear / premium-consumer peers (EssilorLuxottica, National Vision).",
 ipo="Direct list Sep '21", xmin=-4.5,
 points=[[-4.5,40],[-4.0,18],[-3.3,9],[-2.5,13],[-1.5,18],[-0.8,22],[-0.4,15],[-0.1,29],[-0.05,26.46]],
 scn={
  "ultra_bear":dict(p=0.15,g=[0.04,0.04,0.04,0.04,0.04],fcfm=[0.02,0.03,0.04,0.04,0.05],opm=[0.01,0.02,0.03,0.03,0.04],wacc=0.115,tg=0.025,fs=127,evr=[2,1.8,1.7,1.6,1.5],evf=[12,12,11,11,11],
    hl="Growth stalls; margin never inflects.",
    narr=["Customer growth keeps decelerating below ~+5%, the model leans on price not new buyers, gross margin compresses further from 54%, and the operating leverage never arrives: EBITDA stays mired near ~12% while GAAP stays at a small loss/breakeven and FCF margin crawls 2-5%. SBC dilution offsets what little cash is generated.","A decelerating, thin-margin brand that never inflects earns ~2x sales and a low-double-digit EBITDA multiple -> DCF ~$5.98 (-77%). Net cash sets a floor, but at ~3x sales today the downside if the inflection fails is severe."],
    pr="The genuine bear: active-customer growth is already only +4.8% TTM, gross margin slipped to 54.0% from 56.3%, and GAAP profit is a few million dollars that easily flips negative. 15% on the inflection never showing up."),
  "bear":dict(p=0.27,g=[0.08,0.08,0.07,0.07,0.06],fcfm=[0.04,0.05,0.06,0.07,0.07],opm=[0.03,0.04,0.05,0.06,0.07],wacc=0.105,tg=0.030,fs=126,evr=[2.5,2.4,2.3,2.2,2.1],evf=[15,14,14,14,14],
    hl="Stores grow; leverage comes slowly.",
    narr=["Stores keep opening (~50/yr) and revenue compounds ~7% toward ~$1.2B, but operating leverage is grudging: EBITDA inches up while gross-margin pressure and SBC keep GAAP profit thin and FCF margin near 7%. The unit runway is real; the margin step-change is not.","DCF ~$9.84 (-63%) — a single-digit grower whose EBITDA only crawls toward the mid-teens is worth well below ~3x sales; the market's premium assumes a faster inflection than this path delivers."],
    pr="Units and revenue grow but the capital and SBC intensity keep margins suppressed — the plausible 'grows but doesn't lever' path given the customer-growth deceleration. 27% weight."),
  "base":dict(p=0.33,g=[0.11,0.11,0.10,0.09,0.08],fcfm=[0.05,0.07,0.08,0.09,0.10],opm=[0.04,0.06,0.08,0.10,0.11],wacc=0.100,tg=0.030,fs=125,evr=[3,2.9,2.8,2.7,2.6],evf=[17,16,16,16,16],
    hl="Runway continues; margin grinds to ~11%.",
    narr=["The modal path: the store base compounds low-double-digit toward ~900-1,000 units, holistic vision (eye exams, insurance/HSA, contacts) lifts revenue/customer, and operating margin grinds from ~0% toward ~11% with FCF margin reaching ~10% as new-store cohorts mature. Revenue compounds ~10% to ~$1.4B.","DCF ~$15.20 (-43%) — a genuine unit runway and a real margin grind, but at ~3x sales today the price already embeds that ramp; the modal case at a ~16x EBITDA multiple lands well below spot. The market is paying for the inflection in advance."],
    pr="Requires the store-led leverage to show up and FCF to scale as cohorts mature — consistent with the FY26 ~12% EBITDA guide and the new-store economics, but not a step-change. 33% as the central outcome, still -43% from a price that pre-pays the ramp."),
  "bull":dict(p=0.17,g=[0.14,0.13,0.12,0.11,0.10],fcfm=[0.07,0.09,0.11,0.12,0.13],opm=[0.06,0.09,0.11,0.13,0.15],wacc=0.095,tg=0.035,fs=124,evr=[3.5,3.4,3.3,3.2,3.1],evf=[20,19,18,18,18],
    hl="Leverage inflects to ~15%; glasses optionality.",
    narr=["Store-led operating leverage finally lands: a maturing unit base drives EBITDA toward the high-teens, gross margin stabilizes, GAAP profit turns durable and FCF margin reaches ~13% — and the Google Android XR / Gemini AI-smart-glasses program (a free, $150M-committed call-option outside guidance) starts to read as a credible Meta-Ray-Ban competitor. Revenue compounds ~12% to ~$1.5B.","DCF ~$24.03 (-9%) — if the margin inflection arrives, the de-rate-to-fair math nearly closes the gap to spot; this is the core of the bull, and it still does not clear today's price on the fundamentals alone."],
    pr="The Wingstop-style 'leverage finally shows up' path plus a maturing store base make a real EBITDA inflection credible; the glasses add free optionality. ~17% weight on the inflection landing."),
  "ultra_bull":dict(p=0.08,g=[0.17,0.16,0.14,0.13,0.11],fcfm=[0.08,0.11,0.13,0.15,0.16],opm=[0.07,0.10,0.13,0.16,0.18],wacc=0.092,tg=0.035,fs=123,evr=[4,3.9,3.7,3.6,3.5],evf=[22,20,20,20,20],
    hl="Full inflection + glasses second act.",
    narr=["Everything works: the unit machine marches toward multi-thousand US TAM, operating margin reaches ~18% with FCF margin ~16%, holistic vision compounds revenue/customer, and the Google AI-glasses partnership becomes a real second revenue stream rather than a call-option. Revenue compounds ~14% to ~$1.6B at a premium-brand multiple.","DCF ~$33.41 (+26%) — the only scenario that clears spot: a true margin inflection plus the glasses second act re-rate the brand. ~8% probability, the asymmetric upside the rich entry is buying."],
    pr="Margins AND units AND revenue/customer AND the glasses optionality all land — the long-duration tail where the price's embedded inflection actually arrives and then some. ~8%."),
 },
 wr=[("Ultra Bear 15%","Growth stalls; margin never inflects; ~$5.98 (-77%)."),
     ("Bear 27%","Stores grow but leverage crawls; ~$9.84 (-63%)."),
     ("Base 33%","Runway continues; margin grinds to ~11%; ~$15.20 (-43%)."),
     ("Bull 17%","Leverage inflects + glasses optionality; ~$24.03 (-9%)."),
     ("Ultra Bull 8%","Full inflection + glasses second act; ~$33.41 (+26%).")],
 pb=[("At ~3x sales the price already embeds the margin ramp.","The weighted DCF is -42.1% and the modal base is -43% — only the ultra-bull (+26%) clears spot; the inflection is pre-paid, not a free upside."),
     ("The Google glasses are a genuine free call-option.","$150M committed ($75M dev + $75M milestone equity), Android XR + Gemini, NOT in 2026 guidance — credible optionality, but it lives only in the bull/ultra-bull, not the base."),
     ("Stores are the engine and the economics work.","323 stores end-2025 (+47), guiding ~50 more in 2026 at profitable new-store economics; the runway toward ~900-1,000+ units is real, but it has to convert to EBITDA to justify the price."),
     ("Gross-margin compression is the watch-item.","Gross margin fell to 54.0% from 56.3% and GAAP profit is a few million dollars; thin profitability plus SBC dilution is what 'never inflects' looks like."),
     ("Net cash, p_fail ~0.","$286M cash, no debt — no solvency risk; the downside here is multiple/margin (the inflection failing), not survival.")],
 tr=[("Bull validation","adj-EBITDA margin expands above ~14-15% (not just held at 12%)  ·  active-customer growth re-accelerates above +5-6%  ·  gross margin stabilizes/recovers toward 56%  ·  Google AI-glasses ship and read as a real Meta-Ray-Ban competitor"),
     ("Bear validation","customer growth decelerates below ~+4% / turns price-led  ·  gross margin compresses below ~53%  ·  GAAP turns back to a loss and FCF margin stalls near 5%  ·  glasses program slips or disappoints"),
     ("Reframe needed","if EBITDA margin stays stuck near ~12% for 2+ years while customer growth fades, the inflection thesis breaks — re-rate the terminal toward a thin-margin, low-double-digit-growth specialty retailer multiple, not a premium-brand compounder")],
 gloss=[("Active customers","Trailing-12-month buyers (2.69M, +4.8% TTM); the demand gauge — decelerating growth, increasingly price- not customer-led, is the central bear signal."),
        ("Revenue per customer","TTM revenue / active customer (~$331, +6.9%); rising as holistic vision (eye exams, insurance/HSA, contacts) deepens the wallet — the offset to slowing customer counts."),
        ("Adjusted EBITDA margin","Non-GAAP operating profitability (~12.2%); the swing-factor metric — whether store-led scale lifts it toward high-teens/20% is the whole question."),
        ("Android XR / Gemini glasses","Google-partnered AI smart glasses ($150M committed, launching 2026, not in guidance) — a call-option to compete with Meta-Ray-Ban, upside not base case."),
        ("FCF margin","Free cash flow / revenue (~3% FY25); the mature-DCF lever — whether the unit runway and holistic-vision upsell convert thin EBITDA into durable free cash flow.")],
 arena="Eyewear / premium consumer DTC — Warby Parker (vertically-integrated DTC brand, ~323 stores + e-commerce, ~4% US eyewear share) vs EssilorLuxottica (Ray-Ban/LensCrafters/Sunglass Hut), National Vision, Zenni/EyeBuyDirect, and the optical-retail incumbents; auditing a brand Power + a nascent vertical-integration process edge against a dominant incumbent and a thin margin.",
 powers=[("scale_economies",2,"Vertical integration (in-house design, lens labs, optometry) gives a nascent cost/process edge, but tiny vs EssilorLuxottica's global manufacturing/retail scale."),
         ("network_economies",0,"None — eyewear isn't a network; the app and Virtual Try-On are channels, not network effects."),
         ("counter_positioning",2,"Was the DTC disruptor that undercut the EssilorLuxottica markup; now part-incumbent with its own stores, so the counter-position is narrowing."),
         ("switching_costs",1,"Weak — eyewear is a periodic, promiscuous purchase; holistic vision (exams/insurance) builds modest stickiness but no lock-in."),
         ("branding",3,"The dominant Power: a genuine premium DTC brand (design, price-transparency, Buy-a-Pair-Give-a-Pair) with pricing power — but a brand alone doesn't convert to EBITDA while margins are thin."),
         ("cornered_resource",1,"In-house design/lens-lab capability + store locations; valuable but not truly cornered."),
         ("process_power",1,"Emerging: vertically-integrated retail + holistic-vision playbook and new-store economics; unproven at the scale the inflection needs — the bull's swing factor.")],
 dom="branding", dur="medium",
 rivals=[("EssilorLuxottica","public","The dominant incumbent — global lens manufacturing + Ray-Ban/LensCrafters/Sunglass Hut retail + the Meta smart-glasses partner Warby's Google glasses must beat.",0.07,0.18,"~28x P/E"),
         ("National Vision (EYE)","public","Value optical-retail operator (America's Best/Eyeglass World); the mass-market, capital-intensive store comp.",0.05,0.04,"~25x EV/EBITDA"),
         ("Zenni / EyeBuyDirect","private","Ultra-low-price online eyewear; the price-led share threat as Warby leans more on price than new customers.",None,None,"private"),
         ("Meta x EssilorLuxottica (Ray-Ban)","public","The AI-smart-glasses leader already in market — the competitor Warby's Google/Gemini program is chasing, not leading.",None,None,"part of EL")],
 threats=[("branding","Zenni/EyeBuyDirect + value optical (price-led share)","Active-customer growth turns price-led and decelerates below ~+4% while gross margin compresses below ~53%."),
          ("process_power","Capital intensity + SBC (the margin inflection)","Adj-EBITDA margin stays stuck near ~12% for 2+ years while FCF margin stalls near 5% — leverage never shows up."),
          ("counter_positioning","Meta-EssilorLuxottica AI glasses","The Google/Gemini glasses slip or launch behind Ray-Ban Meta, so the optionality the bull/ultra-bull rely on fails to read as a real competitor.")],
 take="Warby Parker's brand Power is genuine — a premium, vertically-integrated DTC eyewear name with real pricing power and a nascent process edge from in-house design/lens labs/optometry — but a brand does not convert to free cash flow while the adjusted-EBITDA margin sits near ~12% and GAAP profit flips between a few million dollars and breakeven. The Audit: branding is durable (medium), process_power (store-led vertical integration) is the emerging swing factor, and the live threats are capital/SBC intensity capping the margin inflection plus price-led share loss to Zenni/value optical; the Google AI-glasses program is upside optionality, not the base, and it chases a Meta-EssilorLuxottica leader. At ~3x sales the price already embeds the margin ramp and some of the glasses optionality, so the weighted DCF is -42.1% and the modal case lands -43% — only the ultra-bull's full inflection-plus-second-act clears spot.",
)

if __name__ == "__main__":
    build(SPEC)
