#!/usr/bin/env python3
"""RDDT — Reddit, Inc. (NYSE) mature-company memo spec. Emits data/_intake/rddt.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1713445). IPO Mar 2024 @ $34."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="RDDT", company="Reddit, Inc.", exch="NYSE", spot=162.10, cap=30.22, sh=186.4, cash=0.954, net_debt=0.0, rev_b=2.203,
 wl="fun-speculative", tier="Med", themes=["platform-marketplace-tech"],
 extras=[
   "Net cash +$954M ($954M cash, no debt); ~186.4M shares, but ~12%-of-revenue SBC keeps diluting the count",
   "Revenue $2.20B FY25 (+62%); GAAP op margin turned positive to ~20%; FCF ~$0.70B headline (~32%), but ~half is SBC",
   "~$162, down ~28% YTD; hit ~$300 in 2025 then ~halved; 52-wk ~$106-$283 — extremely volatile post-IPO"],
 cq="Does Reddit's under-monetized ad engine plus a scarce AI-training corpus outgrow its ~43x FCF price, or does Google/AI-search erode the traffic the whole model rests on?",
 thesis="Reddit trades at ~$30.2B (~$162, down ~28% YTD) — ~43x headline FCF on $2.20B revenue growing ~62% at ~91% gross margin, net cash, GAAP-profitable (~20% op margin). The bull is a deeply under-monetized ad engine (ARPU far below Meta) plus high-margin data-licensing/AI-training deals (Google, OpenAI) compounding; the bear is existential — ~40-50% of traffic comes from Google, and AI-search answer-boxes can disintermediate that discovery (a Q4-2025 algorithm change already dented user growth). Modeled on ex-SBC owner FCF (SBC ~12% of revenue is a ~25% haircut to the headline margin) plus dilution, the modal case lands ~-23%: priced for perfection.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[0.46,0.67,0.80,1.30,2.20]),
   ("history_op_margin",[-30,-25.8,-17.4,-43.1,20.1]),
   ("history_fcf",[-0.05,-0.09,-0.09,0.21,0.70]),
   ("history_ev_rev",[10,15,12,20,13.7])],
 p3cfg=[("segment_a","Advertising"),("segment_b","Data licensing & other"),
   ("hist_ent_split",[0.95,0.94,0.93,0.92,0.94]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec  ·  Q1 FY2026 results",
 sources="Sources: SEC XBRL company facts (CIK 1713445; revenue, GAAP operating income/margin, cash flow), Reddit Q1 FY2026 release (revenue $663M/+69%; advertising $625M/+74%; data-licensing & other $39M/+15%; daily active uniques 126.8M/+17%; ARPU $5.23/+44%; adj EBITDA $266M/40% margin; FCF $311M/~47%; SBC ~$79M/qtr, ~12% of revenue). Revenue modeled as a growth-rate path off FY25; FCF = revenue x ex-SBC owner FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs Meta/Pinterest/Snap.",
 ipo="IPO Mar '24", xmin=-2.3,
 points=[[-2.2,34],[-1.8,60],[-1.3,160],[-0.9,230],[-0.5,180],[-0.2,106],[-0.05,162.10]],
 scn={
  "ultra_bear":dict(p=0.16,g=[0.10,0.05,0.05,0.05,0.05],fcfm=[0.18,0.20,0.22,0.23,0.24],opm=[0.15,0.17,0.19,0.20,0.21],wacc=0.115,tg=0.030,fs=195,evr=[8,6,5,4.5,4],evf=[14,13,13,13,13],
    hl="Google/AI traffic erodes the model.",
    narr=["The existential bear lands: AI-search answer-boxes cannibalize the ~40-50% of traffic that arrives via Google, sessions and ad inventory shrink together, and growth collapses to ~10% then ~5%. Reddit Answers and data-licensing can't backfill a structurally smaller front door, and a once-rich growth story de-rates hard to a low-teens FCF multiple.","Ex-SBC FCF margin holds ~18-24% but on a shrinking base; DCF ~$41 (-75%). When the source of discovery is disintermediated, a 91%-gross-margin model still re-rates to a fraction of a price that assumed durable traffic."],
    pr="The Q4-2025 Google-algorithm change already dented user growth and dropped the stock ~15%; AI-answer cannibalization is the live, asymmetric tail. 16% weight on the traffic dependency turning structural."),
  "bear":dict(p=0.27,g=[0.25,0.15,0.10,0.08,0.07],fcfm=[0.22,0.24,0.25,0.26,0.26],opm=[0.20,0.22,0.24,0.25,0.25],wacc=0.105,tg=0.035,fs=192,evr=[11,9,8,7,6.5],evf=[17,16,16,16,16],
    hl="Growth decelerates; AI-search pressure caps it.",
    narr=["Growth fades faster than the bulls hope: user adds keep decelerating off +17%, Google referral softens (not collapses), and ad ARPU gains slow as the inventory stops compounding. Revenue still grows but ~25% then into the teens, and the scarcity premium on the data-licensing corpus gets competed down.","DCF ~$70 (-57%) — a decelerating, traffic-dependent platform at a mid-teens FCF multiple is worth well under today's price. The market's high-growth premium is unwarranted if the front door is even slowly narrowing."],
    pr="Deceleration plus Google-algorithm sensitivity is the plausible 'grows but the engine cools' path; SBC dilution and ad-cyclicality compound it. 27% as the realistic soft outcome."),
  "base":dict(p=0.32,g=[0.40,0.25,0.18,0.13,0.10],fcfm=[0.24,0.26,0.28,0.29,0.30],opm=[0.22,0.25,0.27,0.29,0.30],wacc=0.100,tg=0.040,fs=190,evr=[13,11,10,9,8.5],evf=[20,18,18,18,18],
    hl="Ad engine compounds; traffic holds.",
    narr=["The modal path: Google referral holds, the under-monetized ad engine keeps lifting ARPU toward peers, international scales, and data-licensing/AI-training deals (Google ~$60M/yr, OpenAI ~$70M/yr) compound as a high-margin offset. Revenue compounds ~40% then normalizes toward ~10%, ex-SBC FCF margin grinds to ~30%.","DCF ~$125 (-23%) — even with the ad engine working and traffic intact, an ~18x terminal FCF multiple on the honest ex-SBC cash leaves the modal case below spot. The price embeds the bull, not the base."],
    pr="Requires traffic to hold and monetization to keep climbing — credible given +44% ARPU and the licensing optionality, but it is priced in. 32% as the central, still-negative outcome."),
  "bull":dict(p=0.17,g=[0.55,0.35,0.24,0.17,0.13],fcfm=[0.26,0.28,0.30,0.32,0.33],opm=[0.25,0.28,0.31,0.33,0.34],wacc=0.095,tg=0.045,fs=188,evr=[16,13,12,11,10],evf=[24,22,22,22,22],
    hl="Monetization plus data-licensing inflect.",
    narr=["The ad engine and the corpus both compound: ARPU closes more of the gap to Meta, international monetization inflects, and the scarce human-generated corpus becomes a recurring high-margin AI-training annuity as more labs license it. Revenue compounds ~55% then sustains mid-teens, ex-SBC FCF margin reaches ~33%.","DCF ~$215 (+32%) — if monetization and data-licensing both inflect while traffic holds, the de-rated entry re-rates with the fundamentals; this is the core of the bull and the only path that clears spot comfortably."],
    pr="Under-monetization vs peers leaves real ARPU runway, and the licensing deals show the corpus has scarce, payable value. ~17% weight on both engines firing."),
  "ultra_bull":dict(p=0.08,g=[0.70,0.45,0.30,0.22,0.16],fcfm=[0.28,0.31,0.33,0.35,0.36],opm=[0.27,0.31,0.34,0.36,0.37],wacc=0.090,tg=0.045,fs=186,evr=[19,16,14,12,11],evf=[26,24,24,24,24],
    hl="Platform plus AI-corpus annuity compound.",
    narr=["The full second act: Reddit becomes the default monetized discussion graph, ad ARPU rivals the majors, and the human-generated corpus turns into a durable, escalating AI-training annuity across the major labs — a high-margin stream that grows with AI demand rather than being cannibalized by it. Revenue compounds ~70% early, ex-SBC FCF margin reaches ~36%.","DCF ~$343 (+112%) — both Powers fully monetize and the multiple re-rates to a scarce-platform premium; ~8% probability, the asymmetric upside the volatile entry is buying."],
    pr="Everything works — monetization AND the corpus annuity AND a multiple re-rate, with AI demand making the data more valuable, not less. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 16%","Google/AI-search erodes traffic; the model de-rates; ~$41 (-75%)."),
     ("Bear 27%","Growth decelerates under AI-search pressure; ~$70 (-57%)."),
     ("Base 32%","Ad engine compounds, traffic holds, still priced in; ~$125 (-23%)."),
     ("Bull 17%","Monetization plus data-licensing inflect; ~$215 (+32%)."),
     ("Ultra Bull 8%","Platform plus AI-corpus annuity compound; ~$343 (+112%).")],
 pb=[("~91% gross margin and +62% growth is rare — why is the modal case negative?","Quality isn't the issue; price is. At ~43x headline FCF (and far higher on honest ex-SBC FCF) even strong execution lands the base at ~-23% — the price already embeds the bull."),
     ("Headline FCF overstates the cash.","FCF was ~$0.70B (~32% of revenue) but SBC runs ~$300M+/yr (~12% of revenue); on ex-SBC owner FCF the real margin is ~a quarter lower and the share count keeps diluting — the model uses the honest number."),
     ("Data-licensing is the offsetting wildcard.","Google (~$60M/yr) and OpenAI (~$70M/yr) deals are ~6% of revenue today but high-margin and scaling — a scarce human-generated corpus that AI demand could make more valuable, partly hedging the traffic risk."),
     ("The Google dependency is the whole thesis.","~40-50% of traffic arrives via Google; AI-search answer-boxes that satisfy queries without a click are the existential threat — the Q4-2025 algorithm change already dented user growth and the stock ~15%."),
     ("Net cash, p_fail ~0.","~$954M cash and no debt — no solvency risk; the entire downside is multiple/growth/traffic, not survival.")],
 tr=[("Bull validation","ARPU keeps climbing toward peer levels (+40%+ sustained)  ·  daily uniques re-accelerate or hold despite AI-search  ·  data-licensing revenue scales beyond ~6% of revenue  ·  international monetization inflects"),
     ("Bear validation","daily-unique growth turns negative or stalls for 2+ quarters  ·  Google referral share visibly falls  ·  ARPU gains stop compounding  ·  a further search-algorithm change dents traffic again"),
     ("Reframe needed","if AI-search clearly disintermediates Google-sourced discovery (sustained traffic decline), re-rate the terminal toward a shrinking, traffic-dependent platform — the ultra-bear case becomes the base")],
 gloss=[("Daily active uniques (DAUq)","Unique logged-in + logged-out daily users (~126.8M, +17%) — the traffic base; its deceleration and Google-algorithm sensitivity are the central bear signal."),
        ("ARPU","Average revenue per user (~$5.23, +44%) — far below Meta, so the gap is the bull's monetization runway and the lever that lifts ad revenue without more users."),
        ("Data licensing","High-margin revenue from licensing Reddit's human-generated corpus for AI training (Google ~$60M/yr, OpenAI ~$70M/yr; ~6% of revenue) — a scarce-resource annuity and the offsetting wildcard to traffic risk."),
        ("AI-search cannibalization","AI answer-boxes (Google AI Overviews, ChatGPT) satisfying queries without a click-through to Reddit — the existential threat to the ~40-50% of traffic that arrives via Google."),
        ("FCF margin","Free cash flow / revenue, modeled ex-SBC (owner FCF, not the ~32% headline) — the mature-DCF swing factor; SBC ~12% of revenue is a ~25% haircut to headline plus ongoing dilution.")],
 arena="Digital advertising and the AI-training-data market — Reddit (the community/UGC discussion graph, ~126.8M daily uniques, under-monetized ad engine) vs Meta, Pinterest, Snap for ad dollars and the AI labs (Google, OpenAI) as data-licensing buyers; auditing a network-economies Power against AI-search disintermediation.",
 powers=[("scale_economies",2,"Some ad-infrastructure and content-moderation leverage at ~$2.2B revenue, but small vs Meta/Google; ad-tech scale is years away."),
         ("network_economies",4,"The dominant Power: a self-reinforcing community/UGC graph — more users and subreddits make the content more useful, which draws more users; decades of accumulated discussion are hard to replicate."),
         ("counter_positioning",1,"Pseudonymous, community-moderated, interest-graph format the incumbents don't replicate well, but not a true counter-position they can't follow."),
         ("switching_costs",2,"Karma, communities, and moderator investment create some stickiness for power users, but most traffic is casual/search-sourced with no lock-in."),
         ("branding",2,"A recognized, trusted 'ask Reddit / real-people answers' brand, but discovery is mediated by Google rather than direct, blunting the brand's pull."),
         ("cornered_resource",4,"A scarce, hard-to-replicate human-generated corpus — the live, opinionated discussion data AI labs pay to train on (Google/OpenAI deals); genuinely cornered while licensed exclusively."),
         ("process_power",1,"Emerging ad-tooling and AI features (Reddit Answers) lifting ARPU, but unproven as a durable, hard-to-copy process advantage.")],
 dom="network_economies", dur="medium",
 rivals=[("Meta (META)","public","The ad-monetization benchmark — ARPU and ad-tech Reddit is measured against and far below; the under-monetization gap is the bull.",0.22,0.42,"~22x EV/FCF"),
         ("Pinterest (PINS)","public","Closest comp — a mid-cap interest-graph ad platform, profitable, similar monetization-runway debate.",0.16,0.25,"~18x EV/FCF"),
         ("Snap (SNAP)","public","A scaled social-ad platform that has struggled to monetize and grow profitably — the cautionary comp on the engine cooling.",0.10,None,"~3x EV/sales"),
         ("Google / OpenAI","public","Dual role: the data-licensing buyers paying for the corpus AND, via AI-search, the existential threat to Reddit's referral traffic.",None,None,"n/a (counterparties)")],
 threats=[("network_economies","Google / OpenAI AI-search","Daily-unique growth turns negative as AI answer-boxes satisfy queries without sending traffic to Reddit — the graph stops compounding."),
          ("cornered_resource","AI labs / synthetic data / open scraping","Labs route around paid licensing (open crawls, synthetic data) and the data-licensing premium gets competed down toward zero."),
          ("scale_economies","Meta / Google ad-tech","ARPU gains stall well below peers as Reddit can't match the majors' targeting/ad-tech, capping the monetization runway.")],
 take="Reddit's network-economies Power is real — a self-reinforcing community/UGC graph and a scarce human-generated corpus (cornered_resource) that AI labs pay to train on. But the Audit's tension is that the same corpus is discovered mostly through Google: ~40-50% of traffic is referral, so AI-search answer-boxes can disintermediate the front door even as the data itself gets more valuable (the Q4-2025 algorithm change already dented user growth). Durability is medium, not high — the graph compounds but its discovery layer is rented from a counterparty that is also a competitor. That squares with the DCF: a 91%-gross-margin, +62%-growth franchise priced at ~43x FCF lands the modal case at ~-23%, because the price embeds the bull's monetization-plus-licensing inflection while carrying an existential, observable traffic risk the distribution puts real weight on.",
)

if __name__ == "__main__":
    build(SPEC)
