#!/usr/bin/env python3
"""CAI — Caris Life Sciences (NASDAQ) · MATURE memo. AI precision-oncology molecular diagnostics.
Numbers via /tmp/finish/mature.py (model_mature, SBC-adjusted). Finding: weighted $23.63 vs spot
$18.33 = +28.9% — the anti-TEM: FCF-positive hypergrowth at ~6.5x sales, priced below its IPO."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="CAI", company="Caris Life Sciences", exch="NASDAQ", spot=18.33, cap=5.10, sh=278.0, cash=0.80, net_debt=0.3785, rev_b=0.812,
 wl="asymmetrical-moonshots", tier="Low", themes=["precision-medicine-oncology"],
 extras=["FY25 revenue $812M (+97%!); GM 47%->65%; adj-EBITDA +$138M; FCF-POSITIVE, near GAAP breakeven",
         "IPO Jun-2025 @ $21; now $18.33 (~13% below offer); FY26 guide $1.0-1.02B (+24%); ~$0.42B net cash",
         "Halbert ~42% vote; SBC ~$70M flatters adj-EBITDA; ~$33M of FY25 rev was reimbursement true-ups"],
 cq="Caris trades at ~6.5x sales like Tempus, yet screens positive where Tempus screened rich — is being FCF-positive at GAAP breakeven, with a real 47%-to-65% margin inflection, enough to justify the price?",
 thesis="Caris Life Sciences is an AI precision-oncology diagnostics company — whole-exome and whole-transcriptome tumor profiling plus blood-based testing — that IPO'd June 2025 at $21.00 and now trades $18.33, ~13% below its offer. FY2025 revenue grew 97% to $812M, gross margin expanded 47%->65%, and unlike most diagnostics scalers it is already free-cash-flow positive with +$138M adj-EBITDA, near GAAP breakeven. The DCF asks whether the margin inflection holds as growth steps down to a +24% guide. Weighted fair value $23.63, ~29% above spot — base ~fair, the upside in the data-moat tail.",
 chartref=[("history_years", [2023, 2024, 2025]), ("history_revenue", [0.306, 0.412, 0.812]),
           ("history_op_margin", [-40.0, -25.0, -8.0]), ("history_fcf", [-0.10, -0.05, 0.04]),
           ("history_ev_rev", [8.0, 7.0, 6.0])],
 p3cfg=[("segment_a", "Molecular profiling"), ("segment_b", "Pharma / data (ADAPT)"),
        ("hist_ent_split", [0.95, 0.94, 0.94]), ("chart6_title", "Equity build (Op EV + net cash)"),
        ("chart6_type", "matureEquityBuild")],
 subtitle="FY23-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec 31  ·  FY2025 + Q1'26 results (IPO Jun'25)",
 sources="Sources: Caris Life Sciences FY2025 results + Q1'26 (CIK 2019410), IPO 424B4 (Jun 2025), FY26 guidance. Revenue as a growth-rate path off FY25 ($812M, +97%); FCF = revenue x an SBC-adjusted owner-FCF margin (already positive; SBC ~$70M deducted); Gordon terminal at scenario WACC. Pre-IPO history/EV-rev are notional. EV/sales vs precision-diagnostics peers.",
 ipo="IPO Jun '25", xmin=-1.05,
 points=[[-1.0, 21.0], [-0.85, 42.5], [-0.65, 30.0], [-0.45, 22.0], [-0.25, 16.0], [-0.1, 17.0], [-0.05, 18.33]],
 scn={
  "ultra_bear": dict(p=0.13, g=[0.10,0.08,0.06,0.05,0.04], fcfm=[0.0,0.03,0.06,0.08,0.10], opm=[0.02,0.05,0.08,0.10,0.12], wacc=0.105, tg=0.03, fs=295, evr=[7,6,5,4.5,4], evf=[60,35,26,21,18],
    hl="Growth collapses; true-up reverses",
    narr=["Revenue compounds only ~6.6% as test-volume growth stalls and reimbursement true-ups reverse rather than recur. The ~$33M of 2025 revenue tied to prior-year reimbursement catch-ups proves non-repeatable, and the reported growth rate is exposed as flattered.",
          "Margins barely move off the floor, holding near 0% owner-FCF as price competition from Tempus, Guardant and Foundation erodes the gross-margin gains. The ~6.5x sales multiple compresses hard against a decelerating, low-margin base. DCF lands at $5.25, down 71%."],
    pr="Requires the volume engine to stall near term and the true-up to be a one-off rather than a recurring feature of payer settlements. Possible given the steep step-down already guided, but the cash-positive base makes outright collapse less likely than for a pre-breakeven peer."),
  "bear": dict(p=0.27, g=[0.18,0.14,0.11,0.09,0.08], fcfm=[0.04,0.07,0.10,0.13,0.15], opm=[0.06,0.09,0.12,0.15,0.17], wacc=0.100, tg=0.035, fs=290, evr=[7.5,6.5,6,5.5,5], evf=[55,34,26,21,18],
    hl="Decelerates; multiple ran ahead",
    narr=["Revenue grows ~11.9% — well below the +24% guide — as competition pressures per-test pricing and the easy share gains slow. The margin inflection partly holds, reaching mid-teens owner-FCF, but not fast enough to outrun a contracting multiple.",
          "The market re-rates a ~6.5x-sales name toward something closer to a low-double-digit grower, and the IPO-era premium unwinds. At a 4%-to-15% margin path the DCF is $10.28, down 44%. The setup is a quality business that was simply priced ahead of its delivery."],
    pr="The honest deceleration case — going from +97% to a +24% guide is a steep step, and a further undershoot plus pricing pressure is plausible. Weighted at 27% as the most credible downside if the data moat proves shallower than bulls assume."),
  "base": dict(p=0.33, g=[0.24,0.20,0.16,0.13,0.11], fcfm=[0.06,0.10,0.14,0.18,0.21], opm=[0.08,0.12,0.16,0.20,0.23], wacc=0.095, tg=0.04, fs=288, evr=[8,7,6.5,6,5.5], evf=[50,30,22,17,14],
    hl="Solid growth, the margin inflection holds",
    narr=["Revenue compounds ~16.7%, roughly in line with the guided range, as clinical test volume grows around 20% and Caris Assure and MI Cancer Seek add incremental lives. The 47%-to-65% gross-margin move continues toward 21% owner-FCF as fixed lab and data costs leverage.",
          "This is the modal outcome — a real growth-plus-margin story that delivers, not a moonshot. At $19.41 the DCF sits just above the $18.33 price, so the base case is roughly fair. The market is paying about what the business is worth if it simply executes the plan."],
    pr="Centered on management hitting the FY26 guide and sustaining the volume KPI while margins keep inflecting — the continuation of what the last two years already showed. Carries the plurality 33% weight as the most likely path."),
  "bull": dict(p=0.18, g=[0.30,0.26,0.22,0.18,0.15], fcfm=[0.08,0.14,0.20,0.25,0.29], opm=[0.10,0.16,0.22,0.27,0.31], wacc=0.090, tg=0.045, fs=285, evr=[9,8,7.5,7,6.5], evf=[45,28,20,16,13],
    hl="Hypergrowth + data-moat leverage",
    narr=["Revenue compounds ~22% as the proprietary whole-exome/transcriptome data asset and the ADAPT platform drive both test volume and pharma partnership revenue, while comprehensive profiling takes share from narrower NGS panels.",
          "Operating leverage on a fixed data and lab base pushes owner-FCF toward 29%, software-like for diagnostics. The market rewards durable hypergrowth plus a widening margin with an expanded multiple. DCF reaches $39.65, up 116%, as the data-moat thesis starts to show in the financials."],
    pr="Needs growth to stay above 20% well past the guide and the gross-margin gains to keep compounding into operating leverage. Plausible if the data asset is a genuine cornered resource, but it asks the company to outrun a steep deceleration; 18%."),
  "ultra_bull": dict(p=0.09, g=[0.36,0.32,0.27,0.22,0.18], fcfm=[0.10,0.18,0.25,0.31,0.35], opm=[0.12,0.20,0.27,0.33,0.37], wacc=0.085, tg=0.05, fs=283, evr=[10,9,8,7.5,7], evf=[40,24,17,14,12],
    hl="Becomes the oncology-data standard",
    narr=["Revenue compounds ~27% as Caris establishes its molecular database as the reference standard for oncology decision-making, with comprehensive profiling, blood-based MRD and the ADAPT AI layer compounding into a network where more tests improve the data and the data wins more tests.",
          "Owner-FCF margins reach ~35%, approaching software economics as the data and AI layer scales near-zero-marginal-cost. At $73.64 the DCF is triple the price. This is the platform outcome where the cornered data resource and scale economics fully express."],
    pr="The full platform win — durable hypergrowth, a true data-network effect, and software-like margins together. Each is individually demanding and the combination is a tail, so it carries 9% — meaningful upside optionality, not a central expectation."),
 },
 wr=[("Ultra Bear 13%", "Growth ~6.6%, the reimbursement true-up reverses, margins stay near zero — DCF $5.25."),
     ("Bear 27%", "Decelerates to ~11.9%, pricing pressure bites, the multiple re-rates down — DCF $10.28."),
     ("Base 33%", "~16.7% growth, margin inflection holds to 21% owner-FCF — DCF $19.41, roughly fair at spot."),
     ("Bull 18%", "~22% hypergrowth, the data moat drives operating leverage — DCF $39.65."),
     ("Ultra Bull 9%", "~27% growth, oncology-data standard, software-like 35% margins — DCF $73.64.")],
 pb=[("Already FCF-positive, unlike Tempus", "Caris is FCF-positive at GAAP breakeven with +97% growth, where the similarly-priced Tempus was barely breakeven — same multiple, further along."),
     ("The margin inflection is real", "Gross margin went 47%->65% in a year and Q1'26 posted positive GAAP operating income — observed operating leverage, not promised."),
     ("Comprehensive profiling is differentiated", "Whole-exome + whole-transcriptome is deeper than rivals' pure-NGS panels, and the data asset compounds — a cornered resource as volume scales."),
     ("Priced below the IPO", "At $18.33 versus a $21.00 offer eight months ago, the base case is roughly fair and the hypergrowth and data-moat tails are not richly priced in."),
     ("The true-up flatters the trend", "About $33M of 2025 revenue was prior-year reimbursement catch-ups, and SBC of ~$70M flatters adj-EBITDA — the underlying organic, owner-economics trend is softer than the headlines.")],
 tr=[("Bull validation", "Test volume sustaining ~20%+ past the FY26 guide; gross margin holding 65%+ and converting to rising owner-FCF."),
     ("Bear validation", "Growth undershooting the +24% guide; per-test pricing eroding; the 2025 reimbursement true-up not recurring."),
     ("Reframe needed", "Margin gains reversing, or SBC/dilution making owner-FCF negative despite positive adj-EBITDA — the Tempus 'priced-for-perfection' read.")],
 gloss=[("Comprehensive molecular profiling", "Whole-exome (all coding genes) + whole-transcriptome (all RNA) tumor sequencing — broader than rivals' targeted NGS panels."),
        ("MI Cancer Seek", "Caris's combined DNA/RNA tumor-profiling assay; reimbursement reach is measured in covered lives (>225M)."),
        ("Caris Assure", "The blood-based liquid-biopsy line, including minimal-residual-disease (MRD) monitoring — detecting cancer DNA in blood to track recurrence."),
        ("Test-volume KPI", "Clinical test volume growth (~20% guided) — the operating metric that drives diagnostics revenue, watched independently of price/mix."),
        ("Adj-EBITDA vs owner-FCF", "Adj-EBITDA adds back ~$70M of stock comp; owner-FCF treats SBC as a real cost, so it is the more conservative read of cash economics."),
        ("Reimbursement true-ups", "Catch-up revenue booked when payers settle prior-period claims; ~$33M in 2025 — non-recurring, so it flatters the reported growth rate."),
        ],
 arena="Comprehensive molecular diagnostics and oncology data — Caris competes with Tempus, Guardant, Roche's Foundation Medicine, Natera and Exact Sciences for tumor-profiling and liquid-biopsy volume.",
 powers=[("scale_economies", 2, "Fixed lab and data-platform costs leverage as test volume compounds; +97% growth drove gross margin 47% to 65%."),
         ("network_economies", 2, "More tests enrich the molecular database, which sharpens the ADAPT AI and wins more clinician and pharma demand."),
         ("counter_positioning", 1, "Whole-exome/transcriptome depth is hard for pure-NGS-panel incumbents to match without re-tooling, but not a true business-model trap."),
         ("switching_costs", 1, "Clinician workflow integration and longitudinal patient data create some stickiness, modest versus entrenched EHR or pathway tools."),
         ("branding", 1, "Growing reputation in oncology decision support, but clinical results and reimbursement, not brand, drive adoption."),
         ("cornered_resource", 2, "The proprietary whole-exome/transcriptome dataset plus the ADAPT platform — the deepest differentiator and the basis of the data moat."),
         ("process_power", 1, "Integrated profiling-plus-AI workflow is hard to replicate quickly, but rivals are closing on capability.")],
 dom="cornered_resource", dur="medium",
 rivals=[("Tempus (TEM)", "public", "AI-precision-oncology data peer; near-breakeven, the direct comp", 0.25, None, "~6x sales"),
         ("Guardant Health", "public", "Liquid-biopsy leader, still loss-making, overlaps in blood-based testing", 0.20, -0.10, "~6x sales"),
         ("Foundation Medicine", "private", "Roche-owned tumor-profiling division; deep-pocketed incumbent, not standalone-priced", None, None, "division"),
         ("Natera", "public", "Genetic testing and MRD; faster-growing, ~breakeven, richer multiple", 0.30, None, "~9x sales")],
 threats=[("scale/pricing", "Tempus, Guardant, Foundation", "Per-test reimbursement or list pricing falls under competitive and payer pressure, halting the gross-margin inflection."),
          ("cornered_resource", "Tempus, Roche, Natera", "A rival assembles a comparable comprehensive-profiling dataset, commoditizing the data moat before scale and network effects lock in."),
          ("network_economies", "well-capitalized incumbents", "Volume growth stalls below ~20%, so the data and scale flywheel never reaches the operating leverage the bull case needs.")],
 take="Caris is originating a plausible cornered resource — a proprietary whole-exome/transcriptome dataset feeding the ADAPT AI — with scale and network economics building as volume compounds, already visible in the 47%-to-65% gross-margin move. Durability is medium, not high — Foundation has Roche's balance sheet, Tempus and Natera are building comparable data, and reimbursement pricing is the shared vulnerability. The falsifier the bull must clear is sustained ~20%+ volume growth with the gross margin holding 65%+; if growth decelerates below that or pricing erodes margin, the moat commoditizes before it locks in.",
)
build(SPEC)
