#!/usr/bin/env python3
"""DAL — Delta Air Lines (NYSE) mature-company memo spec. Emits data/_intake/dal.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 27904)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="DAL", company="Delta Air Lines", exch="NYSE", spot=83.06, cap=54.25, sh=653.1, cash=4.31, net_debt=13.31, rev_b=63.36,
 wl="fcf-plus-plus-growth", tier="Med", themes=["travel-mobility-services"],
 extras=[
   "$4.31B cash vs $13.31B gross debt+leases -> ~$9.0B net debt (adjusted net debt below 2019, investment-grade at all 3 agencies); ~653M shares",
   "Revenue $63.4B FY25 (GAAP, grossed up by third-party refinery sales); GAAP op margin ~9.2%; FCF ~$3.8B",
   "Down ~6% YTD, up ~79% TTM (52-wk $45.28-$83.83); FY26 guide EPS $6.50-7.50 (+20%), FCF $3-4B"],
 cq="Does the premium-cabin + Amex loyalty mix durably de-cyclicalize Delta toward a higher-margin consumer/payments business, or does it revert to commoditized, fuel-and-cycle airline economics?",
 thesis="Delta trades at ~$54.25B equity (~$83.06, ~+79% TTM) -> ~14x FCF on $63.4B GAAP revenue, ~9.2% operating margin, ~$3.8B FCF, but ~$9B net debt drags the equity. The bull is the premium-cabin + SkyMiles-Amex loyalty annuity (premium revenue +14%, Amex remuneration >$2B toward a $10B target) re-rating earnings toward a lower-beta consumer/payments mix; the bear is reversion to fuel-and-cycle airline economics with a soft, K-shaped main cabin. The DCF asks which mix wins - and the modal case lands ~fair (-3%), so cheap-on-FCF is offset by cyclicality and the debt bridge.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[29.9,50.6,58.0,61.6,63.4]),
   ("history_op_margin",[6.3,7.2,9.5,9.7,9.2]),
   ("history_fcf",[0.0,-0.0,1.1,2.9,3.8]),
   ("history_ev_rev",[1.2,0.9,0.9,0.9,1.0])],
 p3cfg=[("segment_a","Passenger"),("segment_b","Cargo + other (loyalty/refinery)"),
   ("hist_ent_split",[0.82,0.84,0.85,0.85,0.84]),
   ("chart6_title","Equity build (Op EV − net debt)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  Q1 FY2026 results + FY26 guidance",
 sources="Sources: SEC XBRL company facts (CIK 27904; revenue, GAAP operating income/margin, cash flow, debt), Delta Q1 FY2026 release (adjusted revenue $14.2B/+9.4%, premium revenue +14% ~ main cabin, Amex remuneration >$2B/+10% toward $10B, FCF $1.2B, adjusted net debt $13.5B, fuel $2.62/gal), FY2026 guide EPS $6.50-7.50 / FCF $3-4B. Revenue modeled as a growth-rate path off FY25 GAAP revenue (grossed up by the refinery's third-party sales, so FCF margin is on GAAP revenue); FCF = revenue x FCF margin; Gordon terminal at scenario WACC; ~$9B net debt nets out of equity. EV/sales & EV/FCF vs network-carrier peers (UAL/AAL/LUV).",
 ipo="NYSE since '07", xmin=-5.5,
 points=[[-5.5,30],[-5.0,40],[-4.2,45],[-3.3,28],[-2.5,40],[-1.5,50],[-0.8,68],[-0.3,60],[-0.1,83],[-0.05,83.06]],
 scn={
  "ultra_bear":dict(p=0.16,g=[-0.08,0.02,0.03,0.03,0.03],fcfm=[0.01,0.02,0.03,0.03,0.03],opm=[0.05,0.06,0.07,0.07,0.07],wacc=0.110,tg=0.020,fs=660,evr=[0.8,0.7,0.7,0.6,0.6],evf=[12,12,11,11,11],
    hl="Recession air-pocket; cyclical reversion.",
    narr=["A recession hits travel: a demand air-pocket drops revenue ~8% in year one, fuel spikes against the cycle, and the premium/loyalty mix can't offset a collapsing main cabin. Operating margin reverts to the mid-single digits of a commoditized carrier and FCF margin falls near 1-3% as the capital-intensive fleet still has to be funded.","A fuel-and-cycle airline with ~$9B net debt and a low-single-digit terminal earns a depressed ~11-12x FCF multiple -> DCF ~$14 (-83%); the debt bridge turns a cyclical earnings shock into an outsized equity drawdown."],
    pr="The genuine cyclical bear: airlines carry operating + financial leverage, Q1 already printed a GAAP pre-tax loss on investment marks, and main cabin is 'struggling.' 16% weight on a recession/fuel air-pocket inside the 5-year window."),
  "bear":dict(p=0.28,g=[0.02,0.03,0.03,0.03,0.03],fcfm=[0.04,0.045,0.05,0.05,0.05],opm=[0.07,0.075,0.08,0.08,0.08],wacc=0.100,tg=0.025,fs=655,evr=[1,0.95,0.9,0.9,0.85],evf=[14,14,13,13,13],
    hl="K-shaped softness; margins stay airline-like.",
    narr=["No recession, but the main cabin stays soft (K-shaped demand) and the premium/loyalty re-rate stalls: revenue grows ~3% while fuel and labor hold operating margin near 7-8% - solidly airline, not consumer. FCF margin sits ~5%.","DCF ~$52 (-38%) - a cyclical carrier whose earnings haven't de-cyclicalized is worth meaningfully below today's price once ~$9B net debt is netted; the market's airline discount is warranted if the mix doesn't shift."],
    pr="Capacity discipline holds the floor but the premium/Amex annuity doesn't durably lift the blended margin; soft main-cabin traffic + fuel keep it cyclical. 28% as the plausible 'stays an airline' path."),
  "base":dict(p=0.33,g=[0.04,0.04,0.04,0.03,0.03],fcfm=[0.05,0.055,0.06,0.06,0.065],opm=[0.08,0.085,0.09,0.09,0.095],wacc=0.095,tg=0.025,fs=650,evr=[1.1,1.05,1,1,0.95],evf=[15,15,14,14,14],
    hl="Premium/loyalty hold; margins grind up.",
    narr=["The modal path: premium revenue and Amex remuneration keep growing toward the $10B target, capacity stays disciplined, and the blended operating margin grinds from ~9% toward ~9.5% as the higher-margin mix partly offsets a flat main cabin. Revenue compounds ~4% to ~$77B at ~6% FCF margin.","DCF ~$80 (-3%) - roughly fair. The loyalty/premium annuity is genuinely valuable, but at a ~14x FCF multiple and with ~$9B net debt the modal case only recovers to about today's price; cheap-on-FCF is offset by the cycle and the debt bridge."],
    pr="Requires the premium/loyalty mix to hold and margins to grind up modestly without a recession - consistent with the FY26 guide (+20% EPS, $3-4B FCF) but not a full re-rate. 33% as the central, near-fair outcome."),
  "bull":dict(p=0.15,g=[0.05,0.05,0.05,0.04,0.04],fcfm=[0.06,0.07,0.075,0.08,0.08],opm=[0.09,0.10,0.105,0.11,0.11],wacc=0.090,tg=0.030,fs=645,evr=[1.3,1.25,1.2,1.15,1.1],evf=[18,17,17,17,17],
    hl="Loyalty annuity de-cyclicalizes the earnings.",
    narr=["The de-cyclicalization lands: premium + SkyMiles-Amex grow into a durable, higher-margin earnings core, falling rates cut interest expense on the deleveraging balance sheet, and operating margin steps up toward ~11% with FCF margin ~8%. The market starts valuing Delta partly as a consumer/payments annuity rather than a pure carrier, lifting the multiple.","DCF ~$128 (+54%) - if a real chunk of earnings re-rates toward a lower-beta loyalty/premium business, the airline discount narrows and the de-rated entry re-rates with the fundamentals; this is the core of the bull."],
    pr="Premium revenue already ~ main cabin and Amex remuneration >$2B/+10% toward $10B; an investment-grade, deleveraging balance sheet supports the re-rate. ~15% weight on the loyalty/premium mix durably shifting the multiple."),
  "ultra_bull":dict(p=0.08,g=[0.06,0.06,0.05,0.05,0.04],fcfm=[0.07,0.08,0.09,0.095,0.10],opm=[0.10,0.11,0.12,0.125,0.13],wacc=0.088,tg=0.030,fs=640,evr=[1.5,1.45,1.4,1.35,1.3],evf=[20,19,18,18,18],
    hl="Consumer/payments re-rate; full multiple shift.",
    narr=["The full second act: the premium-cabin + loyalty/Amex annuity becomes the dominant earnings driver, the main cabin is a stable utility beneath it, operating margin reaches ~13% at ~10% FCF margin, and the balance sheet de-levers through the cycle. Delta re-rates toward a higher-margin consumer/payments multiple rather than a carrier multiple. Revenue compounds ~5% to ~$80B.","DCF ~$174 (+109%) - the structural re-rate from 'airline' to 'travel/payments annuity'; ~8% probability, the asymmetric upside the de-cyclicalization thesis is buying."],
    pr="Everything works - premium AND loyalty/Amex AND deleveraging AND a multiple shift toward consumer/payments, the durable lower-beta outcome. ~8%, the long-duration tail on the mix winning."),
 },
 wr=[("Ultra Bear 16%","Recession air-pocket; cyclical reversion + debt drag; ~$14 (-83%)."),
     ("Bear 28%","K-shaped softness; stays airline-like; ~$52 (-38%)."),
     ("Base 33%","Premium/loyalty hold; margins grind up; ~$80 (-3%)."),
     ("Bull 15%","Loyalty annuity de-cyclicalizes earnings; ~$128 (+54%)."),
     ("Ultra Bull 8%","Consumer/payments re-rate; ~$174 (+109%).")],
 pb=[("~14x FCF looks cheap, but the modal DCF is still ~-3%.","Cyclicality + ~$9B net debt, not the headline multiple, are the constraint - the debt bridge and an airline terminal hold the modal case to roughly fair."),
     ("GAAP revenue is grossed up by the refinery.","The Monroe refinery's third-party fuel sales inflate GAAP revenue (~$63.4B) above the airline's adjusted top line; FCF margin is modeled on GAAP revenue, so the % margin reads low - the cash flows are what matter, not the ratio."),
     ("The premium/loyalty annuity is real and growing.","Premium revenue already ~ main cabin and Amex remuneration >$2B/+10% toward a $10B target - the genuine de-cyclicalizing engine and the bull's mechanism."),
     ("Investment-grade and deleveraging.","IG at all 3 agencies, adjusted net debt below 2019; falling rates cut interest expense and the equity bridge improves as debt comes down."),
     ("It is still a fuel-and-cycle airline.","Q1 printed a GAAP pre-tax loss on investment marks, fuel is $2.62/gal/+7%, and the main cabin is 'struggling' - operating + financial leverage cuts both ways, which is the ultra-bear.")],
 tr=[("Bull validation","premium + loyalty revenue keep outgrowing main cabin  ·  Amex remuneration compounds toward $10B  ·  blended operating margin rises above ~10%  ·  net debt keeps falling / IG affirmed"),
     ("Bear validation","main-cabin traffic stays negative as premium can't offset it  ·  fuel/labor compress operating margin back toward ~7%  ·  FCF undershoots the $3-4B guide  ·  capacity discipline breaks across the industry"),
     ("Reframe needed","if a recession air-pocket hits demand or the premium/loyalty re-rate stalls, the earnings stay cyclical - re-rate the terminal toward a commoditized, fuel-and-cycle carrier multiple, and the ~$9B net debt amplifies the equity hit")],
 gloss=[("Premium revenue","Sales from premium cabins/products (first, Delta One, Comfort+, premium economy); now ~ main cabin and growing +14% - the higher-margin, less price-elastic mix shift at the heart of the bull."),
        ("SkyMiles / Amex remuneration","Cash Delta receives from American Express for co-brand cards and miles (>$2B/quarter, +10%, toward a $10B annual target) - a high-margin, lower-beta payments annuity that de-cyclicalizes earnings."),
        ("Main cabin / K-shaped demand","Economy seats serving price-sensitive flyers; 'K-shaped' = premium holding up while main cabin softens - the central bear signal of a bifurcated consumer."),
        ("Monroe refinery / GAAP gross-up","Delta's wholly-owned refinery sells fuel to third parties; those sales inflate GAAP revenue above the airline's adjusted top line, so the GAAP FCF margin reads artificially low."),
        ("FCF margin","Free cash flow / revenue (~6% FY25 on GAAP revenue); the mature-DCF swing factor - whether premium/loyalty lift the blended margin or fuel-and-cycle economics cap it.")],
 arena="Network airlines + travel/payments - Delta (premium-cabin + SkyMiles-Amex loyalty) vs United, American, Southwest, and the low-cost carriers; auditing scale economies and a loyalty/branding annuity against cyclicality, fuel, and main-cabin commoditization.",
 powers=[("scale_economies",3,"Hub-and-spoke density (ATL and the major hubs), fleet/maintenance scale, and a global JV/alliance network give real cost-per-seat and schedule advantages vs LCCs - the strongest classic airline Power."),
         ("network_economies",2,"The SkyMiles-Amex-partner ecosystem (more partners -> more value -> more members) is a genuine network, but membership doesn't lock a flyer onto Delta metal."),
         ("counter_positioning",1,"The premium-heavy, full-service model is hard for LCCs to copy without abandoning their cost structure, but it isn't true counter-positioning - the legacy peers run it too."),
         ("switching_costs",2,"Elite status, miles balances, and Amex card ties create real but surmountable stickiness; a determined flyer still switches for price/schedule."),
         ("branding",3,"A genuine premium/operational-reliability brand (on-time, premium cabins, loyalty) that supports a fare premium - the consumer/payments leg the bull is underwriting."),
         ("cornered_resource",3,"Slots/gates at constrained hubs and the long-term Amex co-brand economics are quasi-cornered - scarce, contracted, and hard for a rival to replicate."),
         ("process_power",2,"Operational reliability and revenue-management/segmentation execution that peers chase but don't fully match; real, but imitable over time.")],
 dom="scale_economies", dur="medium",
 rivals=[("United (UAL)","public","The closest network-carrier peer; premium/international push and a similar loyalty/co-brand engine - the direct mix-and-margin comp.",0.05,0.08,"~7x EV/FCF"),
         ("American (AAL)","public","Network peer carrying heavier debt; the more-cyclical, weaker-balance-sheet end of the legacy three.",0.03,0.05,"~8x EV/FCF"),
         ("Southwest (LUV)","public","Low-cost domestic leader, point-to-point; the value/main-cabin pressure on Delta's economy fares.",0.04,0.06,"~12x EV/FCF"),
         ("American Express (AXP)","public","Not a flight rival but the loyalty counterparty whose remuneration is the de-cyclicalizing annuity; the payments business Delta is partly valued against.",0.09,0.21,"~18x P/E")],
 threats=[("scale_economies","Fuel spikes + recession demand air-pocket","A cyclical downturn compresses operating margin back to mid-single digits while ~$9B net debt amplifies the equity hit - the ultra-bear."),
          ("branding","K-shaped main-cabin softness / LCC value wars","Main-cabin traffic stays negative and premium can't offset it, so the blended margin stays airline-like instead of re-rating."),
          ("cornered_resource","Amex renegotiation / co-brand competition","Amex remuneration growth stalls short of the $10B target, removing the loyalty annuity that the de-cyclicalization thesis depends on.")],
 take="Delta's strongest Power is classic airline scale economies - hub density, fleet/maintenance scale, and a global network that LCCs can't match on cost-per-seat - reinforced by quasi-cornered slots/gates and a genuine premium brand. The differentiated bet is the SkyMiles-Amex loyalty annuity (network + cornered-resource): a high-margin, lower-beta payments stream (>$2B/quarter toward $10B) that, with the growing premium cabin, could de-cyclicalize the earnings toward a consumer/payments business. The Audit: scale economies are durable (medium), but the loyalty re-rate is the live, unproven swing factor, and the threats are cyclicality/fuel + a soft, K-shaped main cabin - all amplified by ~$9B net debt. That tension is exactly the DCF finding: cheap at ~14x FCF, but the modal case lands ~-3% (fair) because the cycle and the debt bridge offset the multiple until the mix durably shifts.",
)

if __name__ == "__main__":
    build(SPEC)
