#!/usr/bin/env python3
"""Batch-B group 3: YETI, DASH, ILMN. Reuses build() from gen_b1."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPECS=[
# ============================== YETI ==============================
dict(ticker="YETI",company="YETI Holdings",exch="NYSE",spot=48.0,cap=3.6,sh=75.7,cash=0.114,rev_b=1.868,
 wl="fcf-plus-plus-growth",tier="Med",themes=["premium-consumer-brands"],
 extras=["~$114M net cash; ~76M shares; $500M buyback authorization (no dividend)","Revenue $1.87B FY25 (+2% trough; Q1'26 +8%); ~14% adj op margin (tariff-compressed), ~$212M FCF","Stanley/Owala/dupe pressure in US drinkware; China <5% of COGS post de-risking"],
 cq="Is YETI a durable premium brand re-accelerating via international + new categories — or a saturated, fad-cyclical US drinkware brand whose +2% trough caps the multiple?",
 thesis="YETI trades at ~$3.6B (≈$48/sh) — ~17x FCF on $1.87B revenue, net cash, a $500M buyback. Growth troughed at +2% in FY2025 (US drinkware saturation + Stanley/Owala/dupes) and re-accelerated to +8% in Q1'26 on wholesale + international; tariffs compressed margins (~16.5%->14.4% adj op) but China is now <5% of COGS. The mature DCF asks whether international (20%->25% target) + new categories (bags via Mystery Ranch, cookware) + margin recovery offset the saturating core. The finding: roughly fair — the modal growth/margin-recovery path lands near spot.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),("history_revenue",[1.41,1.595,1.658,1.834,1.868]),("history_op_margin",[19.5,7.9,13.6,13.4,11.4]),("history_fcf",[0.10,0.05,0.20,0.18,0.212]),("history_ev_rev",[5.0,3.5,2.5,2.5,1.9])],
 p3cfg=[("segment_a","Drinkware"),("segment_b","Coolers & Equipment"),("hist_ent_split",[0.62,0.61,0.60,0.59,0.58]),("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  52/53-week fiscal year  ·  FY2025 (Jan'26) + Q1'26 results",
 sources="Sources: YETI FY2025 results (year ended Jan 3, 2026; revenue $1.87B, FCF $212M, net cash ~$114M), Q1'26 (+8.3%). Revenue as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal. EV/FCF vs Helen of Troy (Hydro Flask) + Newell.",
 ipo="IPO Oct '18",xmin=-7.5,points=[[-7.0,17.0],[-6.0,30.0],[-5.0,80.0],[-4.5,100.0],[-4.0,55.0],[-3.0,45.0],[-2.0,38.0],[-1.0,30.0],[-0.5,40.0],[-0.05,48.0]],
 scn={
  "ultra_bear":dict(p=0.15,g=[-0.02,-0.02,-0.01,0.0,0.0],fcfm=[0.09,0.09,0.09,0.10,0.10],opm=[0.11,0.11,0.12,0.12,0.13],wacc=0.11,tg=0.0,fs=73,evr=[1.0,0.9,0.8,0.7,0.7],evf=[9,9,9,9,9],
    hl="Fad fades; dupes win; US drinkware shrinks.",
    narr=["The viral tumbler trend rotates away (Stanley->Owala->next), RTIC/private-label dupes arbitrage the premium, and the international/category bets don't offset a shrinking US core. Revenue declines; margins stay tariff-pressured.","DCF ~$23 (-52%) — a fad-exposed brand losing its core earns a distressed multiple."],
    pr="The fad-cyclical bear: drinkware is ~58% of sales and brand heat rotates fast. 15% weight on the trend turning against YETI."),
  "bear":dict(p=0.30,g=[0.01,0.02,0.02,0.03,0.03],fcfm=[0.10,0.11,0.11,0.12,0.12],opm=[0.12,0.13,0.13,0.14,0.14],wacc=0.10,tg=0.015,fs=73,evr=[1.4,1.3,1.2,1.2,1.1],evf=[11,11,11,11,11],
    hl="US saturated; modest; tariff drag lingers.",
    narr=["The US core stays saturated and tariffs keep margins below peak; international + categories grow but only enough to keep the total roughly flat-to-low.","DCF ~$38 (-20%) — a dominant-but-stalled brand at ~11x FCF, below today's price."],
    pr="US drinkware stays saturated and the trend doesn't reverse. 30% weight — the plausible 'stalls' path given the +2% trough."),
  "base":dict(p=0.33,g=[0.03,0.05,0.05,0.05,0.05],fcfm=[0.11,0.12,0.12,0.13,0.13],opm=[0.13,0.14,0.14,0.15,0.15],wacc=0.095,tg=0.02,fs=72,evr=[2.0,1.9,1.8,1.8,1.7],evf=[13,13,13,13,13],
    hl="International + categories offset US; margin recovers.",
    narr=["The modal path: international (toward 25% of revenue) + bags/cookware offset a stabilizing US core, and margins recover as tariffs annualize and China-sourcing exits. Revenue compounds ~5%.","DCF ~$52 (+8%) — roughly fair; the growth/margin-recovery the Q1'26 +8% hints at, priced about right."],
    pr="Requires international + new categories + margin recovery, consistent with Q1'26's +8% and China <5% of COGS. 33% as the central, near-spot outcome."),
  "bull":dict(p=0.17,g=[0.05,0.08,0.08,0.07,0.07],fcfm=[0.12,0.13,0.14,0.14,0.15],opm=[0.14,0.15,0.16,0.16,0.17],wacc=0.09,tg=0.025,fs=71,evr=[2.6,2.5,2.4,2.3,2.3],evf=[15,15,15,15,15],
    hl="International ramps; bags/cookware traction.",
    narr=["International scales past 25%, Mystery Ranch bags + cookware become real categories, and margins recover toward mid-teens — the brand proves durable beyond fad-cyclical drinkware.","DCF ~$75 (+56%) — category + geographic diversification re-rates the brand."],
    pr="International + new categories deliver and margins recover. ~17%; the diversification strategy is credible but unproven at scale."),
  "ultra_bull":dict(p=0.05,g=[0.07,0.10,0.11,0.10,0.09],fcfm=[0.13,0.14,0.15,0.15,0.16],opm=[0.15,0.16,0.17,0.17,0.18],wacc=0.085,tg=0.025,fs=70,evr=[3.2,3.1,3.0,2.9,2.9],evf=[17,17,17,17,17],
    hl="Durable multi-category global brand.",
    narr=["YETI becomes a durable multi-category premium-outdoor brand (drinkware + coolers + bags + cookware) with international as a second engine, compounding ~10% at recovered margins.","DCF ~$97 (+103%) — the brand transcends the drinkware fad; ~5% probability."],
    pr="Full category + geographic diversification works and the brand de-fads. ~5%, the asymmetric upside.")},
 wr=[("Ultra Bear 15%","Fad fades; dupes win; ~$23 (-52%)."),("Bear 30%","US saturated; tariff drag; ~$38 (-20%)."),("Base 33%","Intl + categories offset US; ~$52 (+8%)."),("Bull 17%","Intl ramps; bags/cookware; ~$75 (+56%)."),("Ultra Bull 5%","Durable multi-category global brand; ~$97 (+103%).")],
 pb=[("Net cash, ~$212M FCF, $500M buyback.","Debt-light, cash-generative, shrinking the float at ~17x FCF — capital return is real."),
     ("China sourcing de-risked.","China now <5% of COGS (Vietnam/Philippines/Mexico) — the tariff drag (~$0.35/sh) is largely an annualization headwind, not structural."),
     ("International is the engine.","~20% of revenue growing mid-teens, Japan greenfield (2025), 25%-by-2027 target — a runway the US-saturation view misses."),
     ("New categories extend the brand.","Mystery Ranch bags ($9B+ premium-bag TAM) + Butter Pat cookware diversify beyond fad-cyclical drinkware."),
     ("Q1'26 re-accelerated to +8%.","Wholesale +19% (best in 3 years) + international suggest the +2% FY25 was a trough, not a new normal.")],
 tr=[("Bull validation","international passes 25% of revenue  ·  bags/cookware become reported needle-movers  ·  adj op margin recovers above 16%  ·  wholesale rebound sustains"),
     ("Bear validation","US drinkware stays soft  ·  Owala/Stanley/dupes keep taking share  ·  margins stay tariff-compressed  ·  new categories stall"),
     ("Reframe needed","if drinkware brand heat structurally rotates away (the fad ends), re-rate the core toward a commodity-housewares multiple")],
 gloss=[("Drinkware","YETI's tumbler/bottle core (~58% of sales, higher margin) — the fad-cyclical, most-contested category."),
        ("Mystery Ranch / Butter Pat","2024 acquisitions: technical bags (premium-bag TAM $9B+) + cast-iron cookware — the new-category diversification bets."),
        ("Dupes","Lower-priced look-alikes (RTIC, private label) + viral challengers (Stanley, Owala) eroding the drinkware premium."),
        ("Branding","Helmer Power: premium pricing + community/ambassadors + durability reputation — durable in outdoor, contestable in faddish tumblers."),
        ("FCF margin","Free cash flow / revenue (~11% FY25, tariff-compressed); the mature-DCF lever as margins recover.")],
 arena="Premium outdoor drinkware + gear — YETI (brand, ~60% DTC, drinkware + coolers + new bags/cookware) vs Stanley, Owala, Hydro Flask (Helen of Troy), RTIC, Newell; defending a premium brand Power in a fad-cyclical core.",
 powers=[("scale_economies",2,"Sourcing/marketing leverage at ~$1.9B revenue; modest vs housewares conglomerates."),
         ("network_economies",1,"Community/ambassador affinity, not a hard network."),
         ("counter_positioning",1,"Premium incumbent; dupes counter-position on price."),
         ("switching_costs",1,"Weak — drinkware is a discretionary, swappable purchase."),
         ("branding",2,"The dominant Power: premium pricing + outdoor credibility — durable in coolers/gear, contestable in viral tumblers."),
         ("cornered_resource",2,"Brand IP + design + durability reputation; real but copyable."),
         ("process_power",1,"Design/sourcing learning curve; modest.")],
 dom="branding",dur="medium",
 rivals=[("Stanley (PMI/HAVI)","private","US unit leader; viral surge cooling (~50% search decline 2025).",None,None,"private"),
         ("Owala","private","Fastest-growing brand (+~60% search); took the viral baton from Stanley.",None,None,"private"),
         ("Hydro Flask (Helen of Troy)","public","Cleanest public peer; Home/Outdoor segment declining (~-7%).",-0.05,0.10,"~9x P/E"),
         ("RTIC / private label","private","Explicit price-dupe of YETI; arbitrages the premium.",None,None,"private")],
 threats=[("branding","Owala / Stanley / dupes","US drinkware revenue declines while viral share rotates to challengers."),
          ("scale_economies","Tariffs / sourcing","Margins stay compressed below 14% adj op for 2+ years."),
          ("counter_positioning","Private label / RTIC","Sustained price competition forces YETI off its full-price model.")],
 take="YETI's brand Power is durable in coolers/outdoor gear but genuinely contestable in its fad-cyclical drinkware core (~58% of sales), where viral heat rotates (Stanley->Owala) and dupes arbitrage the premium. International (toward 25%) + new categories (bags/cookware) + margin recovery (China <5% of COGS) are the diversification offsets. At ~17x FCF the modal growth/margin-recovery path lands near spot — roughly fair, with the sign hinging on whether the +2% FY25 was a trough (Q1'26 +8%) or a new normal."),

# ============================== DASH ==============================
dict(ticker="DASH",company="DoorDash",exch="NASDAQ",spot=159.0,cap=66.0,sh=415.0,cash=5.5,rev_b=13.72,
 wl="fcf-plus-plus-growth",tier="Med-High",themes=["platform-marketplace-tech"],
 extras=["~$5.5B net cash; ~415M basic / ~442M diluted shares (SBC dilutes ~$1.3B/yr)","GOV $102B / revenue $13.72B FY25 (+27% GOV); $1.8B FCF; first +FY GAAP income 2024","Down ~40% from highs; advertising ~$1B run-rate, Deliveroo+Wolt international, ~33x EV/FCF"],
 cq="Is DoorDash a dominant local-commerce network whose profitability is about to inflect — or a high-SBC, ~33x-FCF delivery business punished for spending ahead of returns?",
 thesis="DoorDash trades at ~$66B (≈$159/sh, down ~40% from $285) — ~33x EV/FCF on $1.8B FCF, but GOV is still compounding +27% ($102B) and adj-EBITDA hit $2.8B (~2.7% of GOV). The crash is a margin/SBC problem, not a growth one. The mature DCF asks whether advertising (~$1B run-rate) + New-Verticals (grocery) unit economics + international (Deliveroo/Wolt) inflect the 2.4%-of-GOV margin upward, against ~$1.3B/yr SBC dilution. The finding: roughly fair — the 20%+ growth + margin inflection are offset by the premium FCF multiple + dilution.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),("history_revenue",[4.89,6.58,8.6,10.7,13.72]),("history_op_margin",[-9.2,-17.1,-6.7,-0.4,5.3]),("history_fcf",[0.4,0.4,1.35,1.8,1.8]),("history_ev_rev",[12.0,5.0,5.0,5.0,4.4])],
 p3cfg=[("segment_a","US Restaurants"),("segment_b","New Verticals + Intl"),("hist_ent_split",[0.90,0.85,0.80,0.75,0.70]),("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  calendar fiscal year  ·  FY2025 10-K + Q1'26",
 sources="Sources: DoorDash FY2025 10-K (GOV $102B, revenue $13.72B, adj EBITDA $2.8B, FCF $1.8B, net cash $5.5B), Q1'26 (GOV +37% incl. Deliveroo). Revenue as a growth-rate path off FY25; FCF = revenue x FCF margin; SBC modeled via rising final_shares (dilution); Gordon terminal. EV/FCF vs UBER/Instacart.",
 ipo="IPO Dec '20",xmin=-5.5,points=[[-5.4,180.0],[-5.0,250.0],[-4.0,75.0],[-3.0,55.0],[-2.0,110.0],[-1.0,180.0],[-0.6,285.0],[-0.3,150.0],[-0.05,159.0]],
 scn={
  "ultra_bear":dict(p=0.15,g=[0.08,0.07,0.06,0.05,0.05],fcfm=[0.12,0.12,0.13,0.13,0.13],opm=[0.04,0.05,0.06,0.07,0.07],wacc=0.105,tg=0.025,fs=475,evr=[3.0,2.5,2.2,2.0,1.8],evf=[16,15,15,15,15],
    hl="Growth slows; margin stalls; SBC dilutes.",
    narr=["US restaurant delivery saturates, New Verticals stay margin-dilutive, Uber Eats presses, and ~$1.3B/yr SBC keeps diluting. GOV growth decays toward high-single while the 2.4%-of-GOV margin stalls.","DCF ~$67 (-58%) — a no-margin-inflection, SBC-heavy delivery business at a premium multiple de-rates hard."],
    pr="The bear: the margin inflection stalls and SBC dilution + Uber competition cap returns. 15% weight on spending-ahead-of-returns persisting."),
  "bear":dict(p=0.27,g=[0.12,0.11,0.10,0.09,0.08],fcfm=[0.14,0.15,0.16,0.16,0.16],opm=[0.06,0.08,0.10,0.11,0.11],wacc=0.10,tg=0.03,fs=470,evr=[3.6,3.3,3.1,2.9,2.8],evf=[18,17,17,17,17],
    hl="Decelerates; modest margin inflection.",
    narr=["GOV decelerates to low-double-digits and the margin inflects only modestly as ads scale but New Verticals stay competitive; SBC dilution continues.","DCF ~$103 (-35%) — still below spot; the premium FCF multiple isn't covered by a modest inflection."],
    pr="Growth decelerates and the margin ramp is slower than the bull case. 27% weight — a plausible 'grows but stays expensive' path."),
  "base":dict(p=0.33,g=[0.15,0.14,0.12,0.11,0.10],fcfm=[0.16,0.18,0.19,0.20,0.20],opm=[0.08,0.11,0.13,0.15,0.15],wacc=0.095,tg=0.035,fs=465,evr=[4.4,4.1,3.9,3.7,3.7],evf=[20,19,19,19,19],
    hl="Margin inflects; ads scale; ~15% growth.",
    narr=["The modal path: advertising scales past $1B, New-Verticals (grocery) unit economics turn positive in 2H'26, and the network compounds GOV mid-teens — lifting the FCF margin toward 20%.","DCF ~$158 (-1%) — roughly fair; the 20%+ growth + margin inflection just cover the ~33x FCF entry after the de-rate."],
    pr="Requires the guided 2H'26 margin inflection + ads scaling + mid-teens GOV. 33% as the central, near-spot outcome — but SBC caps the per-share."),
  "bull":dict(p=0.18,g=[0.18,0.17,0.15,0.13,0.12],fcfm=[0.18,0.20,0.22,0.23,0.23],opm=[0.10,0.14,0.17,0.19,0.19],wacc=0.09,tg=0.04,fs=458,evr=[5.2,4.9,4.6,4.4,4.4],evf=[23,22,22,22,22],
    hl="Ads + grocery scale; margin to ~5% of GOV.",
    narr=["Advertising + grocery + international (Deliveroo/Wolt) drive the GOV margin toward 4-5%, GOV compounds high-teens, and SBC moderates as a share of revenue.","DCF ~$238 (+50%) — the local-commerce network re-rates as the margin inflection proves durable."],
    pr="The margin inflection compounds (ads + grocery + international) and growth stays high-teens. ~18%; the bull the de-rate is discounting away."),
  "ultra_bull":dict(p=0.07,g=[0.22,0.20,0.18,0.16,0.14],fcfm=[0.20,0.23,0.25,0.26,0.26],opm=[0.12,0.16,0.20,0.22,0.22],wacc=0.085,tg=0.04,fs=452,evr=[6.0,5.7,5.4,5.2,5.2],evf=[26,25,25,25,25],
    hl="Dominant local-commerce platform.",
    narr=["DoorDash becomes the dominant local-commerce platform (restaurants + grocery + retail + ads + autonomy optionality) compounding GOV ~20% at peak network margins.","DCF ~$338 (+113%) — the local-commerce 'everything' platform; ~7% probability."],
    pr="Full local-commerce dominance + a high-margin ad/autonomy mix. ~7%, the asymmetric upside.")},
 wr=[("Ultra Bear 15%","Growth slows; margin stalls; SBC; ~$67 (-58%)."),("Bear 27%","Decel; modest inflection; ~$103 (-35%)."),("Base 33%","Margin inflects; ads scale; ~$158 (-1%)."),("Bull 18%","Ads+grocery scale; ~$238 (+50%)."),("Ultra Bull 7%","Dominant local-commerce platform; ~$338 (+113%).")],
 pb=[("GOV still compounding +27%.","Down 40% on a margin/SBC concern, not a growth one — GOV $102B (+27%), Q1'26 +37%; the network keeps scaling."),
     ("US #1 with network + scale density.","~60% US restaurant share, >2x Uber Eats; logistics density is a genuine cost moat."),
     ("Advertising is the high-margin lever.","~$1B run-rate, near-100% incremental margin — the single biggest margin-inflection driver."),
     ("Net cash $5.5B; first +FY GAAP income 2024.","Profitability inflected ($123M 2024 -> $935M 2025); self-funding, buying back stock."),
     ("New Verticals + international optionality.","Grocery unit economics guided positive 2H'26; Deliveroo/Wolt add 9 countries — TAM expansion.")],
 tr=[("Bull validation","grocery/retail unit economics turn positive (2H'26)  ·  advertising passes $1.5B run-rate  ·  GOV margin rises above 3.5%  ·  GOV stays mid-teens+"),
     ("Bear validation","US restaurant share falls below 58%  ·  grocery stays margin-negative past 2026  ·  SBC stays >$1.3B/yr  ·  Uber Eats gains share"),
     ("Reframe needed","if gig-worker reclassification structurally raises the Dasher cost base, re-rate the unit economics + terminal margin")],
 gloss=[("GOV / take rate","Gross order value (~$102B FY25) x ~13.4% take = revenue; the two metrics that drive the model."),
        ("New Verticals","Grocery / convenience / retail delivery — the fastest-growing, margin-dilutive-today segment guided to positive unit economics 2H'26."),
        ("Network economies","Helmer Power: more consumers -> more merchants/Dashers -> density -> speed/selection; the core moat."),
        ("SBC dilution","Stock-based comp ~$1.3-1.4B/yr (> GAAP net income) — modeled here as a rising share count; the sharpest bear point."),
        ("FCF margin","Free cash flow / revenue (~13% FY25, inflecting); the mature-DCF lever as ads + New Verticals scale.")],
 arena="Local commerce / food delivery — DoorDash (US #1, ~60% restaurant share, New Verticals + ads + Wolt/Deliveroo) vs Uber Eats, Instacart (grocery), Grubhub; defending a network + scale Power as it spends to inflect margins.",
 powers=[("scale_economies",3,"#1 US volume; logistics density lowers cost/delivery; fixed ad/tech spread over the largest GOV base."),
         ("network_economies",3,"The dominant Power: two-sided consumer<->merchant<->Dasher density flywheel."),
         ("counter_positioning",1,"Was the suburban-first disruptor; incumbents have matched."),
         ("switching_costs",2,"DashPass + habit + saved data; modest (multi-homing is easy)."),
         ("branding",2,"Strong US verb-status, not pricing-power branding."),
         ("cornered_resource",1,"No durable exclusive asset; the Dasher network is replicable."),
         ("process_power",2,"Logistics/ML routing + ETA accuracy — a real operational edge.")],
 dom="network_economies",dur="medium-high",
 rivals=[("Uber Eats","public","US #2 restaurants + global; bundles with mobility; richer EV/EBITDA.",0.18,None,"~16x EV/FCF"),
         ("Instacart (CART)","public","US grocery-delivery leader; high-margin ads, slower GOV growth.",0.10,None,"cheaper"),
         ("Grubhub","private","Distant #3 in US restaurants (<10% share); declining.",-0.05,None,"n/a"),
         ("Amazon / Walmart","incumbent","Grocery/retail-delivery scale — the New-Verticals threat.",None,None,"varies")],
 threats=[("scale_economies","Uber Eats (US share)","DoorDash US restaurant share falls below 58% or Uber bundling erodes take rate."),
          ("network_economies","Instacart (grocery)","DASH grocery unit economics stay negative past 2026."),
          ("counter_positioning","Gig-worker regulation","A major-state reclassification ruling structurally raises the Dasher cost base.")],
 take="DoorDash's network-economies + scale (logistics density) are dominant and durable in US restaurants (~60% share, >2x Uber Eats), and GOV is still compounding +27% — the 40% drawdown is a margin/SBC story, not a growth one. The terminal multiple hinges on whether advertising + New-Verticals scale lift the 2.4%-of-GOV margin without a price war, net of ~$1.3B/yr SBC dilution. At ~33x EV/FCF the 20%+ growth + margin inflection roughly cover the entry — fair, with the sign on the 2H'26 inflection."),

# ============================== ILMN ==============================
dict(ticker="ILMN",company="Illumina",exch="NASDAQ",spot=144.83,cap=21.9,sh=151.0,cash=1.16,net_debt=1.99,rev_b=4.34,
 wl="fcf-plus-plus-growth",tier="Med",themes=["omics-life-science-infrastructure"],
 extras=["~$0.83B net debt; ~151M shares; ~$700M/yr buyback (no dividend)","Revenue $4.34B FY25 (~flat 4yrs; Q1'26 +4.8% re-accel); ~23% non-GAAP op margin, ~70% gross, ~$0.9-1.0B FCF","Rallied ~80% off lows on the clinical/NovaSeq-X turnaround; ~5x EV/sales, ~22x FCF"],
 cq="Is Illumina's ~80% rally + ~5x EV/sales pricing a durable clinical/NovaSeq-X re-acceleration — or is flat revenue + low-cost-entrant (Ultima/Element) + Roche erosion the reality?",
 thesis="Illumina trades at ~$22B (≈$145/sh, up ~80% off the lows) — ~5x EV/sales, ~22x FCF on $4.34B revenue (flat for four years, Q1'26 +4.8%), ~70% gross margin, ~$1B FCF. The mature DCF asks whether the NovaSeq-X consumables pull-through + clinical mix (>65% of sequencing consumables, +20% ex-China) re-accelerate the franchise toward a ~26% margin, against low-cost entrants (Ultima/Element $100 genome), Roche's 2026 SBX re-entry, China decline, and NIH cuts. The finding: the rally has priced the re-acceleration — only the bull-or-better clears spot; the base (modest re-accel) sits ~27% below. The TXG mirror.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),("history_revenue",[4.53,4.58,4.5,4.33,4.34]),("history_op_margin",[-2.7,-91.2,-23.7,-19.1,18.6]),("history_fcf",[0.6,0.5,0.7,1.07,0.95]),("history_ev_rev",[12.0,7.0,5.0,4.0,5.0])],
 p3cfg=[("segment_a","Consumables"),("segment_b","Instruments + services"),("hist_ent_split",[0.68,0.70,0.71,0.71,0.72]),("chart6_title","Equity build (Op EV - net debt)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  calendar fiscal year  ·  FY2025 10-K + Q1'26 (Core Illumina, post-GRAIL)",
 sources="Sources: Illumina FY2025 results (Core revenue $4.34B, ~23% non-GAAP op margin, ~$1B FCF, net debt ~$0.83B), Q1'26 (+4.8%, raised guide). GRAIL divested Jun 2024 -> Core-only. Revenue as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal. EV/sales vs life-science-tools peers.",
 ipo="IPO Jul '00",xmin=-5.5,points=[[-5.4,400.0],[-5.0,500.0],[-4.5,300.0],[-4.0,200.0],[-3.0,180.0],[-2.0,130.0],[-1.2,80.0],[-0.7,110.0],[-0.3,150.0],[-0.05,144.83]],
 scn={
  "ultra_bear":dict(p=0.12,g=[-0.02,-0.02,-0.01,0.0,0.0],fcfm=[0.16,0.15,0.15,0.16,0.16],opm=[0.18,0.18,0.19,0.20,0.20],wacc=0.105,tg=0.01,fs=148,evr=[2.5,2.2,2.0,1.8,1.8],evf=[11,11,11,11,11],
    hl="Low-cost entrants + China + NIH crush.",
    narr=["Ultima/Element ($100 genome) compress consumables pricing/share, Roche's SBX re-entry bites, China keeps declining, and NIH cuts freeze research demand. Revenue declines and the consumables annuity erodes.","DCF ~$40 (-73%) — a shrinking franchise losing its pricing Power earns a distressed multiple."],
    pr="The bear: the SBS patent estate ages, low-cost entrants design around it, and the academic base shrinks. 12% weight on real erosion."),
  "bear":dict(p=0.30,g=[0.0,0.01,0.02,0.02,0.02],fcfm=[0.18,0.18,0.19,0.19,0.19],opm=[0.20,0.21,0.22,0.22,0.22],wacc=0.10,tg=0.02,fs=148,evr=[3.2,3.0,2.9,2.8,2.8],evf=[13,13,13,13,13],
    hl="Flat; clinical offsets erosion; rally unwinds.",
    narr=["Clinical growth roughly offsets China + entrant erosion, leaving revenue ~flat at a recovering margin; the franchise is dominant but ex-growth.","DCF ~$92 (-37%) — well below the rallied price; flat revenue doesn't justify ~5x sales."],
    pr="Flat revenue (the FY22-25 reality) with clinical offsetting erosion. 30% weight — the rally priced more than this."),
  "base":dict(p=0.35,g=[0.04,0.05,0.05,0.05,0.04],fcfm=[0.20,0.21,0.22,0.22,0.22],opm=[0.23,0.24,0.25,0.26,0.26],wacc=0.09,tg=0.025,fs=146,evr=[4.0,3.8,3.7,3.6,3.6],evf=[15,15,15,15,15],
    hl="Modest re-accel; NovaSeq-X pull-through; ~26% margin.",
    narr=["The modal path: the NovaSeq-X installed base matures into a consumables acceleration, clinical compounds, and the margin marches to ~26% (management's 2027 target). Revenue grows ~4-5%.","DCF ~$106 (-27%) — even a successful modest re-acceleration doesn't justify the ~80% rally; the entry has run ahead of the fundamentals."],
    pr="NovaSeq-X pull-through + clinical + the ~26% margin target, consistent with Q1'26's +4.8% and raised guide. 35% as the central outcome — but priced in."),
  "bull":dict(p=0.18,g=[0.06,0.08,0.08,0.07,0.07],fcfm=[0.22,0.24,0.25,0.25,0.25],opm=[0.25,0.27,0.28,0.28,0.28],wacc=0.085,tg=0.03,fs=144,evr=[4.6,4.4,4.3,4.2,4.2],evf=[17,17,17,17,17],
    hl="Clinical compounds; multiomics; margin >26%.",
    narr=["Clinical sequencing compounds high-single-digits, multiomics/proteomics (SomaLogic) cross-sells, and the margin pushes past 26% as NovaSeq-X pull-through accelerates in 2H'26+.","DCF ~$162 (+12%) — the durable re-acceleration the rally is pricing actually materializes."],
    pr="The clinical-led re-acceleration is durable + multiomics adds growth. ~18%; the bull the rally is discounting in."),
  "ultra_bull":dict(p=0.05,g=[0.08,0.11,0.11,0.10,0.10],fcfm=[0.24,0.26,0.27,0.28,0.28],opm=[0.27,0.29,0.30,0.30,0.30],wacc=0.08,tg=0.03,fs=142,evr=[5.2,5.0,4.9,4.8,4.8],evf=[19,19,19,19,19],
    hl="Sequencing super-cycle; dominant + multiomics.",
    narr=["A genomics super-cycle (clinical at scale + multiomics) re-accelerates ILMN to low-double-digits at ~30% margins, defending its ~80% share against entrants.","DCF ~$230 (+59%) — the dominant-platform-re-rates outcome; ~5% probability."],
    pr="Sequencing super-cycle + ILMN defends its Power. ~5%, the asymmetric upside.")},
 wr=[("Ultra Bear 12%","Entrants + China + NIH crush; ~$40 (-73%)."),("Bear 30%","Flat; clinical offsets; ~$92 (-37%)."),("Base 35%","Modest re-accel; ~26% margin; ~$106 (-27%)."),("Bull 18%","Clinical compounds; multiomics; ~$162 (+12%)."),("Ultra Bull 5%","Sequencing super-cycle; ~$230 (+59%).")],
 pb=[("~80% share, >90% of clinical genomics.","Dominant installed base + consumables lock-in (validated clinical assays don't re-validate cheaply) — a real scale + switching Power."),
     ("~70% gross margin, ~$1B FCF.","A razor/blade annuity (consumables ~72% of revenue) with a clear path to a ~26% operating margin (2027 target)."),
     ("NovaSeq-X pull-through is coming.","~890 installed (end-FY25); ~6-month pull-through lag -> a 2H'26 consumables acceleration the base is just starting to price."),
     ("Clinical mix is the durable engine.",">65% of sequencing consumables, +20% ex-China — less funding-exposed than the academic/research side."),
     ("GRAIL overhang is gone.","Divested Jun 2024; Core-only reporting, EU fine/impairments behind it; new CEO running the cost-out + clinical pivot.")],
 tr=[("Bull validation","total revenue growth sustains >6%  ·  NovaSeq-X consumables accelerate (2H'26)  ·  non-GAAP op margin reaches ~26%  ·  clinical stays +20% ex-China"),
     ("Bear validation","revenue stays flat-to-down  ·  Ultima/Element take material share  ·  Roche SBX gains clinical traction  ·  China/NIH drag deepens"),
     ("Reframe needed","if a low-cost entrant or Roche SBX structurally breaks the SBS consumables-pricing Power, re-rate toward a commoditized-sequencing multiple")],
 gloss=[("Consumables (razor/blade)","Reagents/flow-cells that run on the installed base (~72% of revenue, ~70% margin) — the recurring annuity and the moat."),
        ("NovaSeq X","Illumina's flagship high-throughput sequencer; its installed-base ramp drives the consumables pull-through (the re-acceleration mechanism)."),
        ("Clinical mix",">65% of sequencing consumables, +20% ex-China — the durable, less-funding-exposed demand engine vs academic/research."),
        ("Low-cost entrants","Ultima (~$80-100 genome) + Element (Vitari) + Roche SBX (2026) attacking the sequencing-by-synthesis franchise on price."),
        ("FCF margin","Free cash flow / revenue (~21% FY25); the mature-DCF lever as the margin marches to the ~26% 2027 target.")],
 arena="DNA sequencing — Illumina (~80% share, NovaSeq-X installed base, ~70%-margin consumables annuity) vs Ultima, Element, Roche (SBX, 2026), PacBio, Thermo, MGI/Complete Genomics; defending a scale + switching Power against low-cost entrants. (Supplies 10x Genomics/TXG; the two are IP litigants.)",
 powers=[("scale_economies",3,"~80% share + huge installed base -> manufacturing/R&D cost advantage on consumables; the dominant Power."),
         ("network_economies",1,"Published-protocol/citation network is mild."),
         ("counter_positioning",1,"Incumbent; low-cost entrants counter-position on price-per-genome."),
         ("switching_costs",3,"Validated clinical assays + DRAGEN pipelines on Illumina chemistry won't re-validate cheaply (regulatory friction)."),
         ("branding",2,"The 'gold standard' in clinical NGS."),
         ("cornered_resource",2,"Sequencing-by-synthesis patent estate — established but contested/aging (litigated vs Element/BGI)."),
         ("process_power",2,"Chemistry/manufacturing learning curve.")],
 dom="scale_economies",dur="medium",
 rivals=[("Ultima Genomics","private","UG 100, ~$80-100 genome (high-throughput) — the low-cost price attack.",None,None,"private"),
         ("Element Biosciences","private","AVITI + Vitari ($100 30x genome); mutual IP litigation with Illumina.",None,None,"private"),
         ("Roche (SBX)","incumbent-division","Re-entering with sequencing-by-expansion (2026); diagnostics channel — the credible long-term threat.",None,None,"diversified"),
         ("PacBio / Thermo / MGI","public","Long-read niche / Ion Torrent / China (MGI blocked from US by BIOSECURE).",None,None,"varies")],
 threats=[("scale_economies","Ultima / Element ($100 genome)","Low-cost entrants take material high-throughput share; consumables pricing compresses."),
          ("cornered_resource","Roche SBX (2026)","Roche's SBX gains clinical traction, breaking the SBS franchise."),
          ("switching_costs","NIH / China","NIH cuts + China decline shrink the academic installed base the annuity depends on.")],
 take="Illumina's scale + switching-cost Power is genuine and durable — ~80% share, >90% of clinical genomics, a ~70%-margin consumables annuity, and clinical labs that won't cheaply re-validate. But the Power is being audited: revenue was flat for four years, China collapsed, NIH froze research demand, low-cost entrants (Ultima/Element $100 genome) attack pricing, and Roche's SBX re-enters in 2026. The ~80% rally to ~5x EV/sales has priced the NovaSeq-X/clinical re-acceleration; only the bull-or-better clears spot, and the modal base sits ~27% below — the entry, not the franchise, is the problem (the TXG mirror)."),
]
for sp in SPECS: build(sp)
