#!/usr/bin/env python3
"""SYM — Symbotic (NASDAQ) · MATURE memo. AI warehouse-automation systems, Walmart-anchored.
Numbers via /tmp/moon/mature.py (model_mature, SBC-adjusted, on the ~591M Up-C economic base).
Finding: weighted $13.32 vs spot $41.63 = -68.0% — richest; thin-margin systems priced like software."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="SYM", company="Symbotic", exch="NASDAQ", spot=41.63, cap=24.60, sh=591.0, cash=1.20, net_debt=0.0, rev_b=2.247,
 wl="asymmetrical-moonshots", tier="Low", themes=["real-economy-hard-assets"],
 extras=["$2.247B revenue FY25 (+26%) but GM only 18.8% (systems/construction-like); ~$22.5B backlog",
         "SBC $184M > adj-EBITDA $147M -> ex-SBC owner-FCF ~0 (the $867M OCF is customer-funded billings, not owner cash)",
         "Walmart >84% of revenue (extreme concentration); GreenBox JV; Nov'24 restatement; ~591M Up-C units, net cash $1.2B"],
 cq="Is a 19%-gross-margin systems integrator priced at ~11x sales worth that multiple on owner cash flow, or only with a software-margin transformation?",
 thesis="Symbotic sells AI-powered warehouse-automation systems, installed and Walmart-anchored (>84% of FY25 revenue). Revenue is $2.25B (+26%), backlog ~$22.5B, net cash ~$1.2B, and Q2 FY26 turned GAAP-positive. But the $867M operating cash flow is customer-funded milestone billings (working capital), not owner cash; SBC of $184M exceeds the $147M adj-EBITDA, so ex-SBC owner FCF is roughly zero. At $41.63 (~591M Up-C units) the market pays a software multiple for a thin-margin integrator. The DCF asks whether margins inflect; weighted fair value $13.32, −68% to spot.",
 chartref=[("history_years", [2023, 2024, 2025]), ("history_revenue", [1.18, 1.79, 2.247]),
           ("history_op_margin", [-12.0, -8.0, -5.0]), ("history_fcf", [-0.10, 0.0, 0.10]),
           ("history_ev_rev", [15.0, 12.0, 11.0])],
 p3cfg=[("segment_a", "Systems (Walmart)"), ("segment_b", "GreenBox WaaS"),
        ("hist_ent_split", [0.95, 0.92, 0.88]), ("chart6_title", "Equity build (Op EV + net cash)"),
        ("chart6_type", "matureEquityBuild")],
 subtitle="FY23-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Sept  ·  FY2025 + Q2 FY2026 results",
 sources="Sources: Symbotic FY2025 (ended 9/27/25) + Q2 FY2026 results (CIK 1837240). Revenue as a growth-rate path off FY25; FCF = revenue x an SBC-adjusted owner-FCF margin (thin — gross margin is ~19%; the $867M operating cash flow is customer-funded milestone-billing timing, not owner cash); Gordon terminal at scenario WACC. Per-share on the ~591M Up-C economic unit base, not the Class A float. EV/sales vs automation peers.",
 ipo="SPAC Jun '22", xmin=-4.0,
 points=[[-3.9, 10.0], [-3.0, 20.0], [-2.0, 45.0], [-1.5, 60.0], [-1.0, 88.0], [-0.5, 50.0], [-0.05, 41.63]],
 scn={
  "ultra_bear": dict(p=0.13, g=[0.08,0.06,0.05,0.04,0.04], fcfm=[-0.04,-0.02,0.0,0.02,0.03], opm=[-0.06,-0.04,-0.02,0.0,0.01], wacc=0.115, tg=0.03, fs=615, evr=[9,7,5,4,3], evf=[200,80,40,28,20],
    hl="Margin never inflects; Walmart bites",
    narr=["Revenue grows only ~5% to FY30 as Walmart slows new-system orders and renegotiates terms. The 19% gross margin holds or compresses under construction-like execution risk, and SBC keeps owner FCF near zero through the period.",
          "GreenBox stalls, recurring mix never materializes, and the business stays a low-return integrator dependent on one buyer. At a thin terminal FCF margin the equity is worth $2.89 per share, ~93% below spot."],
    pr="Requires Walmart to throttle deployments and margins to stay systems-like. Backed by the restatement history and the structural 19% gross margin, but the $22.5B backlog makes a near-flat path a tail outcome."),
  "bear": dict(p=0.27, g=[0.14,0.12,0.10,0.08,0.07], fcfm=[-0.01,0.02,0.04,0.05,0.06], opm=[-0.03,0.0,0.02,0.03,0.04], wacc=0.105, tg=0.035, fs=610, evr=[10,8,7,6,5], evf=[120,50,32,24,18],
    hl="Backlog converts slowly; thin margins",
    narr=["Revenue compounds ~10% as backlog converts on a slow cadence, but gross margin stays in the high teens and only modest operating leverage appears. SBC continues to absorb most of the gain, so owner FCF inches up but stays thin.",
          "Walmart remains the overwhelming customer and GreenBox adds little recurring economics within the window. A slow-converting, low-margin integrator discounts to $5.79 per share, ~86% below spot."],
    pr="The path if execution is fine but the economics never improve. The labor-automation tailwind and visible backlog support double-digit growth; the thin margin and concentration cap the value."),
  "base": dict(p=0.33, g=[0.20,0.17,0.14,0.12,0.10], fcfm=[0.0,0.03,0.06,0.08,0.10], opm=[-0.02,0.01,0.04,0.06,0.08], wacc=0.100, tg=0.04, fs=605, evr=[11,9,8,7,6], evf=[80,40,26,20,16],
    hl="Backlog converts; margins improve",
    narr=["Revenue compounds ~14.5% as the $22.5B backlog converts on schedule and modest scale lifts the owner-FCF margin toward 10% by FY30. GreenBox begins contributing recurring warehouse-as-a-service revenue alongside the systems business.",
          "This is solid operational execution, but a ~19%-gross-margin systems business compounding in the mid-teens is worth far less than ~11x sales on owner cash flow. The DCF settles at $11.09 per share, ~73% below spot."],
    pr="The modal case: backlog converts, the labor tailwind holds, GreenBox helps at the margin. It carries the most weight because the contracted backlog makes mid-teens growth the central expectation."),
  "bull": dict(p=0.18, g=[0.26,0.22,0.18,0.15,0.13], fcfm=[0.02,0.06,0.10,0.13,0.15], opm=[0.0,0.04,0.08,0.11,0.13], wacc=0.095, tg=0.045, fs=600, evr=[12,10,9,8,7], evf=[60,32,22,17,14],
    hl="Margins inflect; GreenBox recurs",
    narr=["Revenue compounds ~18.7% and the owner-FCF margin climbs toward 15% as systems standardize, software content rises, and GreenBox shifts the mix toward recurring WaaS economics. Operating leverage finally outruns SBC.",
          "The labor-automation demand is structural and the backlog funds the ramp, so a genuine margin inflection becomes visible. At a richer terminal margin the equity is worth $22.02 per share, still ~47% below spot."],
    pr="Requires margins to begin the transformation, not just revenue to grow. Plausible given backlog visibility and rising recurring mix, but it asks the integrator economics to start behaving like a platform."),
  "ultra_bull": dict(p=0.09, g=[0.32,0.27,0.22,0.18,0.15], fcfm=[0.04,0.09,0.14,0.18,0.20], opm=[0.02,0.07,0.12,0.16,0.18], wacc=0.090, tg=0.05, fs=595, evr=[13,11,10,9,8], evf=[45,26,18,14,12],
    hl="Platform; software-like margins",
    narr=["Revenue compounds ~22.6% and gross margin expands from ~19% toward 30%+ as Symbotic becomes the standard warehouse-automation platform, with high-margin software and recurring GreenBox WaaS dominating the mix. The owner-FCF margin reaches ~20%.",
          "This is a full economic transformation, not just scale: the systems integrator turns into a software-economics platform. Only this outcome justifies the price, reaching $41.78 per share, ~flat to spot."],
    pr="The lowest-weight tail because it requires gross margin to roughly double from a systems base. The structural tailwind and backlog make platform scale conceivable, but software-like margins are unproven here."),
 },
 wr=[("Ultra Bear 13%", "Margin never inflects; Walmart bites."),
     ("Bear 27%", "Backlog converts slowly; high-teens margin persists."),
     ("Base 33%", "Backlog converts; ~10% owner-FCF margin; GreenBox helps."),
     ("Bull 18%", "Margins inflect toward 15%, recurring WaaS mix grows; $22.02."),
     ("Ultra Bull 9%", "Software-like margins; gross margin toward 30%+.")],
 pb=[("Backlog gives rare visibility", "A ~$22.5B backlog (Walmart + GreenBox) is multiples of revenue, an unusually contracted forward book that de-risks the growth path."),
     ("Labor automation is structural", "Warehouse-labor scarcity and rising fulfillment volume make AI automation a durable, multi-decade demand tailwind, not a cycle."),
     ("GAAP just turned positive", "Q2 FY26 net income of +$9M marks the inflection from years of losses; operating leverage may now compound."),
     ("GreenBox adds recurring mix", "The SoftBank WaaS JV (~$11.6B backlog) shifts the model toward recurring, higher-margin revenue versus one-time system sales."),
     ("Cash flow is real cash", "Operating cash flow was +$867M; even if milestone-timed, it funds the ramp without dilution or debt.")],
 tr=[("Bull validation", "Gross margin climbing above the low-20s; GreenBox recurring revenue scaling; a second large anchor customer beyond Walmart."),
     ("Bear validation", "Walmart order cadence slowing or terms renegotiated; gross margin stuck near 19%; another restatement or control deficiency."),
     ("Reframe needed", "Sustained software-like gross margin (30%+) with ex-SBC owner FCF turning durably positive would move this from systems integrator to platform.")],
 gloss=[("Systems-integrator model / gross margin", "Designs, builds, and installs automation systems; margins are construction-like (~19% here), not software-like, because hardware and integration dominate cost."),
        ("Backlog", "Contracted but not-yet-recognized revenue (~$22.5B), giving forward visibility; converts to revenue as systems are deployed over multiple years."),
        ("Up-C dual-class economic units", "An Up-C structure: economic ownership spans Class A plus Class V units (~591M total), so per-share value uses ~591M, not the smaller Class A float."),
        ("GreenBox (warehouse-as-a-service)", "SoftBank JV offering automated warehousing as an outsourced, recurring service (~$11.6B of backlog) rather than a one-time system sale."),
        ("Adj-EBITDA vs owner FCF; customer-funded OCF", "Adj-EBITDA ($147M) excludes SBC ($184M); the $867M operating cash flow is customer milestone prepayments (working capital), not sustainable owner cash."),
        ("SBC (stock-based compensation)", "Non-cash pay in stock ($184M, exceeding adj-EBITDA); it dilutes owners and is the main driver of the GAAP operating loss.")],
 arena="Warehouse-automation systems for large retailers and 3PLs; Symbotic competes with incumbent material-handling integrators and in-house programs from the largest buyers.",
 powers=[("scale_economies", 2, "Largest dedicated automation deployments fund R&D and standardization, but a 19% gross margin shows limited cost advantage so far."),
         ("network_economies", 1, "Some data and operational learning across sites, but no cross-customer network effect that compounds value as installs grow."),
         ("counter_positioning", 1, "Full-stack AI-robotics integrator differs from legacy hardware vendors, but incumbents can adopt similar AI without a business-model conflict."),
         ("switching_costs", 2, "Installed multi-year systems are deeply embedded and costly to rip out, but that locks the customer, not new wins."),
         ("branding", 1, "Credibility from the Walmart reference, but enterprise buyers procure on proof and economics, not brand."),
         ("cornered_resource", 2, "The Walmart relationship and contracted backlog are a privileged asset, but the same dependence is the concentration risk."),
         ("process_power", 1, "Integration and software know-how exist, but a thin gross margin and the restatement history argue the process advantage is not yet durable.")],
 dom="cornered_resource", dur="medium",
 rivals=[("Amazon Robotics", "private", "In-house automation at the largest buyer; not for sale but sets the build-vs-buy bar.", None, None, "deep parent balance sheet"),
         ("Dematic (KION)", "public", "Established material-handling integrator, low-margin hardware-led model.", 0.08, 0.06, "~6-8% division margin"),
         ("Honeywell Intelligrated", "private", "Division of a diversified industrial; scaled integrator with broad install base.", 0.05, 0.07, "industrial-conglomerate margins"),
         ("AutoStore", "public", "Higher-margin modular ASRS vendor, mid-teens growth, software-like economics.", 0.14, 0.40, "~40% EBITDA margin")],
 threats=[("cornered_resource", "Walmart", "Walmart in-sources automation or renegotiates terms, collapsing the >84% revenue concentration."),
          ("process_power", "execution / controls", "Another restatement, deployment delay, or material-weakness recurrence signals integration is not yet a durable advantage."),
          ("scale_economies", "margin structure", "Gross margin stays near 19% through scale, proving the model never reaches software-like, platform economics.")],
 take="A cornered-resource relationship with Walmart plus the largest contracted backlog is real Power, but it cuts both ways: the same dependence is an extreme concentration risk, and a 19% gross margin shows scale has not yet produced a durable cost or process advantage. Durability is medium at best. The falsifier the bull must clear is margin: gross margin expanding well beyond the high teens with ex-SBC owner FCF turning durably positive, ideally alongside a second large anchor customer.",
)
build(SPEC)
