#!/usr/bin/env python3
"""CMG — Chipotle Mexican Grill (NYSE) mature-company memo spec. Emits data/_intake/cmg.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP (us-gaap:OperatingIncomeLoss / revenue) from SEC XBRL (CIK 1058090)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="CMG", company="Chipotle Mexican Grill", exch="NYSE", spot=32.23,
 cap=41.96, sh=1302.4, cash=1.05, net_debt=0.0, rev_b=11.93,
 wl="fcf-plus-plus-growth", tier="Med", themes=["premium-consumer-brands"],
 extras=[
   "Net cash ~$1.05B, no funded debt; ~1.30B fully-diluted shares (50:1 split-adjusted) — solvency a non-issue",
   "Revenue $11.93B FY25 (+6%); GAAP op margin 16.2% (off the 16.9% peak); FCF ~$1.4B (~12%), capex ~11-12% on new units",
   "Down ~14% YTD / ~36% TTM near the 52-week low ($29.75-$58.42); ~30x FCF, cheapest in years"],
 cq="As comps inflect barely positive while restaurant-level margin compresses, does the 4,100->7,000 unit runway re-rate the stock, or is ~30x FCF already full?",
 thesis="Chipotle trades at ~$41.96B (~$32.23, down ~14% YTD / ~36% TTM, near the 52-week low) — ~30x FCF on $11.93B revenue, net cash, GAAP op margin 16.2% off a 16.9% peak. Q1'26 comps just turned positive (+0.5%, traffic-led, no price), but restaurant-level margin fell 250bps as management declines to fully price mid-single-digit inflation to defend value. The bull is the unit runway (~4,100 -> 7,000 NA) plus throughput/automation; the bear is a maturing concept with structurally low-single-digit same-store growth at a premium multiple. The weighted DCF lands -4.8% — the modal base (-5.5%) only reaches about today's price; the runway is real, the multiple already pays for it.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[7.5,8.6,9.9,11.3,11.93]),
   ("history_op_margin",[10.7,13.4,15.8,16.9,16.2]),
   ("history_fcf",[0.8,0.8,1.2,1.5,1.4]),
   ("history_ev_rev",[6.5,5.0,4.5,4.5,3.5])],
 p3cfg=[("segment_a","Restaurant sales"),("segment_b","Delivery/digital"),
   ("hist_ent_split",[0.50,0.55,0.62,0.65,0.65]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end Dec  ·  Q1 FY2026 results",
 sources="Sources: SEC XBRL company facts (CIK 1058090; revenue, GAAP operating income/margin, cash flow, debt), Chipotle Q1 FY2026 release (Apr 29 2026: revenue $3.1B/+7.4%, comps +0.5% traffic-led, restaurant-level margin 23.7% (-250bps), 49 openings to ~4,100 units, ~7,000-unit NA target, Hyphen automated-makeline testing). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs fast-casual / QSR peers (SHAK/CAVA/WING/MCD).",
 ipo="IPO Jan '06", xmin=-5.2,
 points=[[-5.0,13],[-4.0,20],[-3.0,28],[-2.0,45],[-1.2,58],[-0.5,42],[-0.05,32.23]],
 scn={
  "ultra_bear":dict(p=0.13,g=[0.03,0.03,0.03,0.03,0.03],fcfm=[0.10,0.10,0.10,0.11,0.11],opm=[0.14,0.14,0.14,0.145,0.145],wacc=0.100,tg=0.025,fs=1300,evr=[3,2.5,2.2,2,1.8],evf=[14,13,13,13,13],
    hl="Comps roll over; margin keeps sliding.",
    narr=["Value-perception softness wins: traffic gives back the +0.5% inflection, same-store sales go flat-to-negative, and beef/freight/labor inflation that management won't price keeps restaurant-level margin grinding below 23% toward a low-14% company op margin. The unit machine keeps opening but de-levers a softening top line, so FCF margin slips toward ~10%.","A maturing premium QSR whose comps and margins are both eroding earns a low-single-digit-growth, ~13x terminal FCF multiple -> DCF ~$14.66 (-54%). Net cash floors the equity but cannot offset a stalled same-store engine."],
    pr="The genuine bear: comps were negative three straight quarters into Q1'26, the +0.5% carries no price, and the 250bps margin cut shows inflation isn't being recovered. 13% on the inflection failing and value-wars biting."),
  "bear":dict(p=0.27,g=[0.06,0.06,0.05,0.05,0.05],fcfm=[0.11,0.115,0.12,0.12,0.12],opm=[0.15,0.155,0.16,0.16,0.16],wacc=0.090,tg=0.030,fs=1290,evr=[3.5,3.2,3,2.8,2.6],evf=[18,17,16,16,16],
    hl="Units grow; same-store stays sluggish.",
    narr=["Units keep opening toward the 7,000 runway but same-store sales stay low-single-digit and traffic-led, while inflation the brand won't fully price holds restaurant-level margin around recent levels rather than recovering. Revenue compounds ~5% to ~$15B at a ~12% FCF margin — the runway is real, the comp engine and margin lift are not.","DCF ~$21.83 (-32%) — a slowing-comp grower at a still-rich multiple is worth meaningfully below today's price; the discount is warranted if same-store growth stays structurally low and margins don't re-expand."],
    pr="Unit growth continues but soft comps + value-perception drag + unrecovered inflation keep the P&L flat. 27% as the plausible 'opens stores but doesn't re-accelerate' path, given the comp history and the guide-to-flat."),
  "base":dict(p=0.34,g=[0.09,0.08,0.08,0.07,0.07],fcfm=[0.12,0.125,0.13,0.135,0.14],opm=[0.16,0.165,0.17,0.17,0.175],wacc=0.085,tg=0.030,fs=1280,evr=[4,3.7,3.4,3.2,3],evf=[22,20,19,19,19],
    hl="Runway delivers; comps low-single-digit.",
    narr=["The modal path: openings run at the high end (~350-370/yr) toward the 7,000 NA target, comps settle low-single-digit, and restaurant-level margin stabilizes near current levels as throughput and the Hyphen makeline offset some inflation, lifting FCF margin toward ~14%. Revenue compounds ~8% to ~$17B.","DCF ~$30.47 (-5.5%) — roughly fair. A ~10% unit runway is genuinely valuable, but at ~14% terminal FCF margin and a ~19x EV/FCF the modal case only recovers to about today's spot; ~30x FCF already prices the runway in."],
    pr="Requires the unit runway to convert at roughly today's unit economics with low-single-digit comps — consistent with the 'Recipe for Growth' plan, not a step-change re-acceleration. 34% as the central, near-fair outcome."),
  "bull":dict(p=0.18,g=[0.11,0.11,0.10,0.09,0.09],fcfm=[0.13,0.14,0.145,0.15,0.155],opm=[0.17,0.175,0.18,0.185,0.19],wacc=0.080,tg=0.035,fs=1270,evr=[4.5,4.2,4,3.8,3.6],evf=[26,24,23,23,23],
    hl="Throughput inflects; comps and margin lift.",
    narr=["The traffic inflection holds and compounds: digital, the Hyphen automated makeline, and throughput initiatives lift transactions and restaurant-level margin back toward the high-25s even before price, units accelerate toward 7,000, and FCF margin climbs past 15%. Revenue compounds ~10% to ~$18-19B.","DCF ~$44.77 (+39%) — if comps re-accelerate and automation widens unit margins as the base expands, the franchise re-rates with its fundamentals; this is the core of the bull."],
    pr="Throughput/automation plus a sustained traffic turn is credible given the brand's ~$3M AUV and the makeline tests. ~18% on the operational lift compounding rather than fading."),
  "ultra_bull":dict(p=0.08,g=[0.13,0.13,0.12,0.11,0.10],fcfm=[0.14,0.15,0.16,0.165,0.17],opm=[0.18,0.185,0.19,0.195,0.20],wacc=0.078,tg=0.035,fs=1260,evr=[5,4.7,4.4,4.2,4],evf=[28,26,25,25,25],
    hl="Full runway plus automation; FCF machine.",
    narr=["The full second act: the 7,000 NA runway plays out at high-end unit economics, automation (Hyphen) and digital structurally lift margins past 19% op / ~17% FCF, and international (Mexico, Korea/Singapore JV) opens a fresh capital-light leg. Revenue compounds ~12% to ~$20B and Chipotle reclaims a premium-compounder multiple.","DCF ~$55.75 (+73%) — best-in-class brand, automation-led margins, and a global runway re-rated together; ~8% probability, the asymmetric upside the de-rated entry is buying."],
    pr="Everything works — comps AND automation margins AND the full unit runway AND international, the premium-compounder outcome. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 13%","Comps roll over and margin slides; ~$14.66 (-54%)."),
     ("Bear 27%","Units grow but same-store stays sluggish; ~$21.83 (-32%)."),
     ("Base 34%","Runway delivers at low-single-digit comps; ~$30.47 (-5.5%)."),
     ("Bull 18%","Throughput inflects, comps and margin lift; ~$44.77 (+39%)."),
     ("Ultra Bull 8%","Full runway plus automation; ~$55.75 (+73%).")],
 pb=[("Comps finally turned positive — isn't that the inflection?","+0.5% is traffic-led with no price after three down quarters; the modal DCF is still -5.5% because ~30x FCF already embeds a re-acceleration, and the +0.5% doesn't yet clear it."),
     ("The 7,000-unit runway is a long compounding machine.","~4,100 -> 7,000 NA is ~10% unit growth, but the base lands ~fair because same-store growth is structurally low-single-digit and the multiple pays for the runway up front."),
     ("Margin compression is the live risk, not the runway.","Restaurant-level margin fell 250bps to 23.7% as management won't fully price mid-single inflation to defend value — the swing is whether unit economics (~25%+ RLM) hold while scaling."),
     ("It's the cheapest Chipotle has been in years.","True on the multiple (~30x FCF vs history), but cheap-vs-itself isn't cheap-vs-DCF; the distribution still centers slightly negative unless comps or margins re-accelerate."),
     ("Net cash, p_fail ~0.","~$1.05B cash and no funded debt — no solvency risk; the downside here is multiple/comp/margin, not survival.")],
 tr=[("Bull validation","comps re-accelerate above low-single-digit with traffic (not price)  ·  restaurant-level margin recovers toward 25%+  ·  Hyphen/automation rolls out and lifts throughput  ·  openings hold 350-370/yr toward 7,000"),
     ("Bear validation","comps slide back to flat/negative 2+ quarters  ·  restaurant-level margin falls further below ~23%  ·  inflation stays unpriced and op margin drifts toward 14%  ·  value-perception softness persists"),
     ("Reframe needed","if same-store growth stays structurally low-single-digit AND restaurant-level margin can't hold ~25%, the runway compounds at low unit economics - re-rate the terminal toward a maturing, low-single-digit-comp QSR multiple")],
 gloss=[("Comparable restaurant sales (comps)","Same-store sales growth at restaurants open 13+ months; Q1'26 +0.5%, traffic-led with no price after three negative quarters - the central swing signal."),
        ("Restaurant-level margin (RLM)","Restaurant-level operating margin (non-GAAP, 23.7% Q1'26, -250bps YoY) before corporate G&A - the unit-economics gauge that must hold ~25%+ as units scale 4,100->7,000."),
        ("AUV","Average unit volume (~$3M per restaurant) - the per-store sales base, well above QSR, that against build cost sets new-unit returns and underwrites the runway."),
        ("Hyphen / makeline automation","Automated digital makeline being tested to speed throughput and lift restaurant margin - the process lever in the 'Recipe for Growth' plan and the bull's margin path."),
        ("FCF margin","Free cash flow / revenue (~12% FY25); the mature-DCF swing factor - whether the unit runway and automation convert to expanding free cash flow against ~11-12% growth capex.")],
 arena="Premium fast-casual / fast food — Chipotle (the premium QSR brand, ~$3M AUV, ~4,100 company-owned units) vs Cava, Shake Shack, Wingstop and the QSR value set (McDonald's, Taco Bell); auditing a brand Power against QSR value-wars and value-perception softness.",
 powers=[("scale_economies",4,"~$12B revenue, ~4,100 company-owned units -> real sourcing/marketing/G&A leverage and a self-funded build; second only to branding here."),
         ("network_economies",0,"None - restaurants aren't networks; the app/loyalty is a channel, not a network effect."),
         ("counter_positioning",1,"Was the 'food with integrity' fast-casual disruptor; now the scaled incumbent, so this has faded."),
         ("switching_costs",1,"Near-zero - dining is promiscuous; loyalty/digital nudges repeat but every meal is a fresh decision."),
         ("branding",5,"The dominant Power: a best-in-class premium QSR brand with ~$3M AUV well above peers and genuine pricing power - though it's choosing not to fully exercise it to defend value."),
         ("cornered_resource",1,"Prime real estate, supply relationships and recipe/operations IP; valuable but not truly cornered."),
         ("process_power",2,"Throughput discipline and Hyphen makeline automation - a real emerging lever but unproven at the 7,000-unit scale; the bull's swing factor.")],
 dom="branding", dur="high",
 rivals=[("Cava (CAVA)","public","The fast-casual growth darling; richest multiple in the set, the unit-growth comp Chipotle is benchmarked against.",0.25,0.12,"~46x EV/EBITDA"),
         ("Shake Shack (SHAK)","public","Premium 'better burger', smaller and thinner-FCF; a same-archetype premium-brand unit-growth comp.",0.06,0.04,"~13x EV/EBITDA"),
         ("Wingstop (WING)","public","Asset-light franchise compounder; richly valued but wobbling - Q1'26 domestic SSS -8.7%.",0.11,0.25,"~37x EV/EBITDA"),
         ("McDonald's (MCD)","public","The QSR value benchmark; the value-wars/trade-down pressure on Chipotle's premium pricing.",0.05,0.45,"~25x P/E")],
 threats=[("branding","QSR value-wars / trade-down (McDonald's, Taco Bell value menus)","Comps stay flat-to-negative as premium pricing loses to value in a soft consumer and value-perception softens."),
          ("scale_economies","Beef/freight/labor inflation management won't fully price","Restaurant-level margin falls further below ~23%, rolling back the unit economics the runway needs."),
          ("process_power","Cava / a crowded fast-casual field + throughput limits","Same-store traffic fades and automation doesn't lift margin, so the 7,000-unit build compounds at low unit economics.")],
 take="Chipotle's brand Power is dominant and durable - a best-in-class premium QSR with ~$3M AUV, real scale economies across ~4,100 company-owned units, and pricing power it is deliberately not fully using to defend value. The Audit: branding is durable (high), process_power (throughput, Hyphen automation) is the emerging swing factor, and the live threats are QSR value-wars / value-perception softness plus unrecovered beef/labor inflation that just cut restaurant-level margin 250bps. The franchise quality isn't in question; the price is. Comps barely turned positive (+0.5%, no price) while the stock still trades ~30x FCF, and the weighted DCF lands -4.8% - the unit runway is real and the brand is excellent, but the modal case (-5.5%) shows the multiple already pays for the runway, leaving the upside in the bull/ultra automation-and-comps re-acceleration.",
)

if __name__ == "__main__":
    build(SPEC)
