#!/usr/bin/env python3
"""AAPL — Apple (NASDAQ) mature-company memo spec. Emits data/_intake/aapl.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 320193)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="AAPL", company="Apple", exch="NASDAQ", spot=291.13, cap=4302.0, sh=14776.4, cash=54.7, net_debt=90.7, rev_b=416.2,
 wl="fcf-megacap", tier=None, themes=["premium-consumer-brands","consumer-experience"],
 extras=[
   "Net debt ~$36B ($54.7B cash vs ~$90.7B total debt); ~14.78B shares, shrinking on a fresh $100B buyback + dividend raise",
   "Revenue $416B FY25 (+6%); GAAP op margin ~32%; FCF ~$99B; Services ~$31B/quarter at ~70%+ gross margin",
   "~$291 (Jun 2026), +56% TTM, near the ~$315 ATH; iPhone ~50% of revenue, Greater China reaccelerating (+28%)"],
 cq="Does a mid-single-digit grower at ~43x FCF, with AI outsourced to Gemini and a ~$20B/yr Google-search-payment cliff in Services, justify a quality premium the modal case can't underwrite?",
 thesis="Apple trades at ~$4.30T (~$291/sh, +56% TTM) - about 43x ~$99B FCF on $416B revenue growing mid-single-digits, with ~$36B net debt. Services compounds mid-teens at ~70%+ gross margin on a 2.5B+ base, but iPhone is still ~50% of revenue, Apple Intelligence is now outsourced to Gemini, and a ~$20B/yr Google search payment faces a DOJ annual rebid. The DCF resolves whether quality justifies the multiple: the weighted finding is -34.5% - the modal lands ~$188 (-35%): the price embeds safety beyond what FCF growth pays for.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[365.8,394.3,383.3,391.0,416.2]),
   ("history_op_margin",[29.8,30.3,29.8,31.5,32.0]),
   ("history_fcf",[93.0,111.4,99.6,108.8,98.8]),
   ("history_ev_rev",[6.8,6.1,7.0,8.7,9.4])],
 p3cfg=[("segment_a","Products"),("segment_b","Services"),
   ("hist_ent_split",[0.82,0.81,0.78,0.76,0.74]),
   ("chart6_title","Equity build (Op EV − net debt)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Sept  ·  FQ2 2026 (Apr-2026) results",
 sources="Sources: SEC XBRL company facts (CIK 320193; revenue, GAAP operating income/margin, cash flow, debt), Apple FQ2 2026 release (revenue $111.2B +17%, iPhone $56.99B +22%, Services $30.98B +16% at an all-time high, Greater China $20.5B +28%, gross margin 49.3% guided down to 47.5-48.5% on higher memory cost). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs mega-cap peers (MSFT/GOOGL/NVDA).",
 ipo="IPO Dec '80", xmin=-6.2,
 points=[[-6.0,75],[-5.0,130],[-4.0,180],[-3.3,130],[-2.5,190],[-1.5,230],[-0.5,250],[-0.1,315],[-0.02,291.13]],
 scn={
  "ultra_bear":dict(p=0.13,g=[0.02,0.02,0.02,0.02,0.02],fcfm=[0.20,0.20,0.21,0.21,0.21],opm=[0.30,0.30,0.30,0.31,0.31],wacc=0.09,tg=0.025,fs=14600,evr=[5,4.5,4,3.8,3.6],evf=[18,17,16,16,16],
    hl="iPhone stalls; Services tails crystallize.",
    narr=["The hardware engine flattens and the twin regulatory tails land: iPhone revenue stagnates as the upgrade super-cycle pays back, the ~$20B/yr Google search payment is cut or competed away, and EU/US App Store fee erosion bites high-margin Services. Revenue grows ~2%/yr and FCF margin compresses toward ~20% as the mix shifts away from the most profitable dollars.","A flat hardware franchise losing its richest Services rents re-rates to a mid-teens FCF multiple -> DCF ~$89 (-69%). Net debt offers no cushion here; the de-rate is the multiple meeting the growth."],
    pr="The genuine bear: iPhone is ~50% of revenue and partly pulled forward, the search payment must be rebid annually under the DOJ ruling, and App Store fees face regulatory pressure on two continents. 13% weight on the tails crystallizing together."),
  "bear":dict(p=0.27,g=[0.05,0.05,0.04,0.04,0.04],fcfm=[0.22,0.22,0.23,0.23,0.23],opm=[0.31,0.31,0.32,0.32,0.32],wacc=0.085,tg=0.03,fs=14400,evr=[6,5.5,5,4.8,4.6],evf=[22,20,19,19,19],
    hl="Low-single-digit growth; multiple compresses.",
    narr=["Apple keeps the ecosystem but the growth stays muted: iPhone replacement cycles lengthen, Services compounds but off a base partly funded by the at-risk search payment, and tariff/India cost drag (~5-8% premium) trims gross margin. Revenue compounds ~4% at a ~23% FCF margin.","DCF ~$129 (-55%) — a durable but slow-growing franchise at ~19x terminal FCF is worth well below 43x; the gap between today's multiple and mid-single-digit growth is the whole bear."],
    pr="Share and ecosystem hold, but mid-single-digit growth can't carry a premium multiple while the search-payment and fee tails hang over Services. 27% as the plausible 'durable but slow' path."),
  "base":dict(p=0.33,g=[0.07,0.07,0.06,0.06,0.05],fcfm=[0.23,0.24,0.24,0.25,0.25],opm=[0.32,0.32,0.33,0.33,0.33],wacc=0.08,tg=0.035,fs=14100,evr=[7,6.5,6,5.8,5.6],evf=[26,24,23,23,23],
    hl="Services compounds; iPhone steady; still rich.",
    narr=["The modal path: Services compounds mid-teens at ~70%+ gross margin on a 2.5B+ installed base, the iPhone 17 cycle and China reacceleration keep hardware steady, and the Gemini-powered Siri keeps users locked in. Revenue compounds ~6% to ~$555B at a ~25% FCF margin, with buybacks shrinking the share count.","DCF ~$188 (-35%) — even crediting durable Services growth and a defended ecosystem, a ~23x terminal FCF multiple lands well below the ~43x paid today; the modal case says the price embeds quality and safety beyond what the cash flows underwrite."],
    pr="Requires Services to keep compounding and the iPhone base to stay sticky through the AI-platform shift — consistent with FQ2's record Services and China rebound, but not a re-acceleration. 33% as the central, still-rich outcome."),
  "bull":dict(p=0.19,g=[0.09,0.09,0.08,0.08,0.07],fcfm=[0.24,0.25,0.26,0.27,0.27],opm=[0.33,0.33,0.34,0.34,0.35],wacc=0.076,tg=0.04,fs=13800,evr=[8,7.5,7,6.8,6.6],evf=[30,29,29,29,29],
    hl="AI-era ecosystem deepens; search risk fades.",
    narr=["The ecosystem wins the AI era on someone else's model: the Gemini-powered Apple Intelligence raises engagement and Services attach, the search payment survives the rebid intact, and the installed base feeds a higher-margin Services mix. Revenue compounds ~8% to ~$600B and FCF margin lifts toward ~27%.","DCF ~$279 (-4%) — even the bull only reaches roughly today's price; an upper-single-digit grower at a sustained high-20s FCF multiple essentially validates spot rather than beating it."],
    pr="Services + the AI-era ecosystem stay sticky, the search payment holds, and China momentum continues — the FQ2 trends extended. ~19% weight on the franchise compounding without the tails biting."),
  "ultra_bull":dict(p=0.08,g=[0.11,0.11,0.10,0.09,0.09],fcfm=[0.25,0.26,0.28,0.29,0.30],opm=[0.33,0.34,0.35,0.35,0.36],wacc=0.074,tg=0.04,fs=13500,evr=[9,8.5,8,7.8,7.6],evf=[32,31,31,31,31],
    hl="Services step-change; FCF/share compounds hard.",
    narr=["The full upside: Services reaccelerates on AI features and new monetization, hardware finds a fresh wedge (wearables, new categories), gross margin holds near 49%, and the ~$100B buyback compounds FCF/share on a shrinking count. Revenue compounds ~10% to ~$640B at a ~30% FCF margin.","DCF ~$362 (+25%) — the only scenario that clears spot, and only if Services takes a genuine step-change and the multiple stays in the low-30s. ~8% probability, the asymmetric upside the premium is paying for."],
    pr="Everything compounds — Services AND margins AND buyback leverage AND no regulatory hit — the quality-compounder outcome. ~8%, the long-duration tail that justifies the premium if it lands."),
 },
 wr=[("Ultra Bear 13%","iPhone stalls and the Services tails crystallize; ~$89 (-69%)."),
     ("Bear 27%","Low-single-digit growth; the multiple compresses; ~$129 (-55%)."),
     ("Base 33%","Services compounds, iPhone steady, but still rich; ~$188 (-35%)."),
     ("Bull 19%","AI-era ecosystem deepens and search risk fades; ~$279 (-4%)."),
     ("Ultra Bull 8%","Services step-change; FCF/share compounds; ~$362 (+25%).")],
 pb=[("The de-rate is the multiple, not the franchise.","Apple is a genuine quality compounder, but a mid-single-digit grower at ~43x FCF prices safety beyond growth — even the bull only reaches ~$279 (-4%)."),
     ("The ~$20B Google payment is a discrete cliff.","It is near-pure-margin Services that must be rebid annually under the DOJ ruling; losing it directly cuts the highest-quality earnings, and the bear/ultra-bear weight it."),
     ("AI is outsourced, not owned.","A custom Gemini behind the revamped Siri (~$1B/yr to Google) makes Apple a fast-follower on foundation models; the bull needs the ecosystem to win the AI era on someone else's stack."),
     ("Services + installed base are the quality.","~$31B/quarter of Services at ~70%+ gross margin on 2.5B+ devices is durable recurring earnings — the base/bull lean on it compounding mid-teens."),
     ("iPhone is ~half the revenue and partly pulled forward.","FQ2 iPhone +22% rode pent-up demand from ~315M users on 4+yr phones; a payback air-pocket is the bear's mechanism once the super-cycle clears.")],
 tr=[("Bull validation","Services growth holds mid-teens+  ·  iPhone upgrade cycle sustains (not payback)  ·  the Google search payment survives the rebid  ·  gross margin defends ~47%+ through memory/tariff cost  ·  China revenue keeps reaccelerating"),
     ("Bear validation","Services decelerates below ~10%  ·  the search payment is cut or competed away  ·  EU/US App Store fee remedies take hold  ·  iPhone revenue goes flat-to-down in a payback air-pocket  ·  gross margin slips below ~46%"),
     ("Reframe needed","if the AI-platform shift cedes the next interface (a Gemini/agent layer that disintermediates iOS) or Services growth structurally stalls, re-rate the terminal toward a flat-hardware multiple - the ultra-bear's ~16x")],
 gloss=[("Services","Apple's recurring high-margin revenue (App Store, AppleCare, advertising, payments, subscriptions; ~$31B/quarter at ~70%+ gross margin) on a 2.5B+ device installed base - the quality engine the bull leans on."),
        ("Installed base","The >2.5B active Apple devices that drive Services attach and switching costs; its growth and stickiness, not unit sales, anchor the mid-teens Services compounding."),
        ("Google search payment","The ~$20B/yr Google pays to be the default Safari search engine - near-pure-margin Services that must be rebid annually under the DOJ antitrust ruling; a discrete near-term cliff."),
        ("Apple Intelligence","Apple's AI feature set; the revamped Siri now runs a custom Google Gemini model (~$1B/yr), staggered across iOS 26.4/26.5/27 - i.e. AI capability is partnered, not in-house."),
        ("FCF margin","Free cash flow / revenue (~24% FY25); the mature-DCF swing factor - whether a mid-single-digit grower defends ~70%+-margin Services dollars against the search-payment and App Store tails.")],
 arena="Premium consumer hardware + a high-margin Services ecosystem - Apple vs Samsung/Google (phones), Microsoft/Google (platforms/AI), and the App Store/payments field; auditing a branding + switching-costs Power against the AI-platform shift.",
 powers=[("scale_economies",4,"Massive purchasing/manufacturing and R&D scale across ~$416B revenue; among the deepest in consumer tech, though not the single dominant Power."),
         ("network_economies",2,"iMessage/FaceTime/AirDrop and the developer ecosystem create modest network pull, but the lock-in is more switching cost than true network effect."),
         ("counter_positioning",1,"Largely the incumbent now; the privacy-and-integration stance differentiates but rivals can and do copy it - not a structural counter-position."),
         ("switching_costs",4,"Deep ecosystem lock-in: iCloud, App Store purchases, Watch/AirPods/Mac continuity, iMessage - leaving means abandoning a connected device estate; a core durable Power."),
         ("branding",5,"The strongest Power: the premium global brand commands pricing power and ~49% gross margin and anchors a 2.5B+ installed base; decades-durable."),
         ("cornered_resource",2,"In-house silicon (A/M-series) is a real edge and the developer base is sticky, but neither is a fully cornered, irreplaceable resource."),
         ("process_power",3,"World-class supply-chain and silicon-design execution (Cook's operational machine); a genuine but partly replicable advantage.")],
 dom="branding", dur="high",
 rivals=[("Samsung","public","The premium-Android hardware rival; competes on phones/wearables but lacks Apple's Services ecosystem and margin.",0.05,0.10,"~12x P/E"),
         ("Alphabet (GOOGL)","public","Owns Android + Gemini; the AI-platform threat and Apple's ~$20B search-payment counterparty all at once.",0.15,0.32,"~24x P/E"),
         ("Microsoft (MSFT)","public","The other quality mega-cap compounder; the platform/AI peer Apple's multiple is benchmarked against.",0.13,0.45,"~33x P/E"),
         ("Samsung Electronics / Xiaomi","public","High-volume Android OEMs pressuring iPhone share in China/India at lower price points.",0.08,0.08,"~10x P/E")],
 threats=[("switching_costs","The AI-platform shift (Gemini/agent layer)","An AI agent layer that disintermediates the iOS interface and erodes ecosystem lock-in - measurable as Services attach/engagement flattening."),
          ("branding","Regulators (DOJ search remedy + EU/US App Store)","The ~$20B Google search payment is cut on rebid and App Store fee remedies take hold, draining the highest-margin Services dollars."),
          ("scale_economies","Tariffs + India supply shift","Gross margin slips below ~46% as the ~5-8% India cost premium and tariff drag (~$900M/quarter) outrun price.")],
 take="Apple's brand is the strongest single Power in this set - a premium global franchise with ~49% gross margin and pricing power - reinforced by deep ecosystem switching costs and immense scale; durability is high. But the live threat is the AI-platform shift: with Apple Intelligence outsourced to Gemini, the next interface may run on someone else's model, and that same counterparty anchors a ~$20B/yr search payment now exposed to a DOJ rebid. The Powers are durable; the question the DCF presses is price, not moat. A mid-single-digit grower at ~43x FCF carries a premium even the bull (~$279, -4%) barely justifies, and the modal case lands ~$188 (-35%).",
)

if __name__ == "__main__":
    build(SPEC)
