#!/usr/bin/env python3
"""DE — Deere & Company (NYSE) mature-company memo spec. Emits data/_intake/de.yml
via the reusable Batch-B builder (gen_b1.build). Numerics modeled in model_mature;
op-margin history is GAAP (us-gaap:OperatingIncomeLoss / revenue) from SEC XBRL (CIK 315189)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="DE", company="Deere & Company", exch="NYSE", spot=577.48, cap=156.15, sh=270.4, cash=8.28, net_debt=13.80, rev_b=45.68,
 wl="fcf-plus-plus-growth", tier="Med", themes=["real-economy-hard-assets","robotics-automation"],
 extras=[
   "$8.28B cash; ~$13.8B modeled equipment-ops debt (EXCLUDES ~$45B Deere Capital captive borrowings, offset by finance receivables); ~270M shares",
   "Revenue $45.7B FY25 (-12%, third down-year off the FY23 $61.3B peak); GAAP op margin 14.0% (trough); FCF ~$6.1B (~13%)",
   "~$577, YTD ~+10.5%, TTM ~+19%; 52-week $433-$674 (ATH $660 Feb 2026), ~26x trough FCF"],
 cq="Has Deere's stock already priced the ag-cycle recovery off the trough, or does the precision-ag recurring-revenue mix structurally lift mid-cycle margins beyond what ~26x trough FCF embeds?",
 thesis="Deere trades at ~$156B (~$577, +10.5% YTD into the cycle low) — ~26x trough FCF (~17x nearer the bottom) on $45.7B revenue down 12% in the third year of an ag down-cycle, GAAP operating margin compressed to 14.0%, FCF ~$6.1B. The mature DCF asks whether the recovery is already in the price: the modal case says largely yes (base -23%), because a full multiple on trough earnings already discounts the upturn. The bull is the cycle turning plus precision ag (See & Spray, autonomy, JDLink) de-cyclicalizing margins; the ultra-bear is a deeper, longer ag recession. The finding: -21.8% weighted — quality bought at a rich price near a trough.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[44.0,52.6,61.3,51.7,45.7]),
   ("history_op_margin",[18.2,18.1,21.2,17.5,14.0]),
   ("history_fcf",[6.9,3.6,7.1,7.6,6.1]),
   ("history_ev_rev",[4.0,3.3,2.6,3.0,3.4])],
 p3cfg=[("segment_a","Equipment operations"),("segment_b","Financial services"),
   ("hist_ent_split",[0.90,0.91,0.92,0.91,0.90]),
   ("chart6_title","Equity build (Op EV − net debt)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Oct  ·  FQ2 FY2026 (ended May 3) results",
 sources="Sources: SEC XBRL company facts (CIK 315189; revenue, GAAP operating income/margin, cash flow, debt), Deere FQ2 FY2026 release (revenue $13.37B/+5%, EPS $6.55, Production & Precision Ag sales -14%/op profit -39% = the trough, Small Ag & Turf +16%, Construction & Forestry +29%/+48%, FY26 net-income guide $4.5-5.0B maintained, ~$1.2B FY tariff headwind). NOTE: modeled debt ($13.8B equipment ops) EXCLUDES Deere's ~$45B captive-finance (Deere Capital) borrowings, which are offset by finance receivables -> the consolidated-FCF DCF is a simplification of a company with a large captive lender. Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs CNH, AGCO, CAT, Kubota.",
 ipo="NYSE listed", xmin=-5.5,
 points=[[-5.5,170],[-5.0,300],[-4.2,360],[-3.3,290],[-2.5,420],[-1.5,400],[-0.8,480],[-0.3,660],[-0.1,577],[-0.05,577.48]],
 scn={
  "ultra_bear":dict(p=0.14,g=[-0.05,0.00,0.03,0.04,0.04],fcfm=[0.10,0.11,0.12,0.12,0.13],opm=[0.10,0.11,0.12,0.12,0.13],wacc=0.105,tg=0.020,fs=272,evr=[2,1.8,1.7,1.6,1.5],evf=[12,12,12,12,12],
    hl="Deeper, longer ag recession.",
    narr=["The down-cycle extends rather than bottoms: large-ag (Production & Precision Ag) keeps falling past the guided -15-20% as farm income stays depressed, used-equipment inventories overhang new sales, and tariffs (~$1.2B FY) compound the squeeze. Revenue declines again before a shallow late-decade recovery; operating margin troughs near 10-13% and the recurring-revenue mix is too small to cushion the drop.","A capital-goods cyclical caught a year early in a worse-than-feared recession earns a low-teens trough multiple -> DCF ~$219 (-62%). The captive-lender complexity and a richer-than-peer starting valuation amplify the downside."],
    pr="The genuine bear: large-ag is already guided -15-20% with weak farm income, the FY26 net-income guide ($4.5-5.0B) is roughly half the peak, and a full multiple on trough earnings has no cushion if the trough deepens. 14% weight on a deeper/longer recession."),
  "bear":dict(p=0.27,g=[0.02,0.05,0.05,0.04,0.04],fcfm=[0.12,0.13,0.13,0.14,0.14],opm=[0.13,0.14,0.14,0.15,0.15],wacc=0.095,tg=0.025,fs=270,evr=[2.5,2.3,2.2,2.1,2],evf=[15,14,14,14,14],
    hl="Recovery is slow; trough margins stick.",
    narr=["The cycle bottoms but the recovery is muted: large-ag stabilizes rather than snaps back, Construction & Forestry and small-ag carry the early upturn, and net price discipline holds, but tariffs and a soft farm economy keep operating margin in the mid-teens. Precision ag grows but stays a small share. Revenue recovers low-single-digit to ~$56B by FY30.","DCF ~$342 (-41%) — a slow, margin-capped recovery doesn't support a full multiple on trough FCF; the de-rate toward a normal mid-cycle valuation is warranted if the mix doesn't shift."],
    pr="The cycle turns but a weak farm economy + the ~$1.2B tariff drag keep margins near trough levels and the precision-ag mix immaterial. 27% as the plausible 'recovers but slowly' path given the maintained-but-halved FY26 guide."),
  "base":dict(p=0.34,g=[0.05,0.08,0.07,0.06,0.05],fcfm=[0.13,0.14,0.15,0.15,0.15],opm=[0.15,0.16,0.17,0.17,0.18],wacc=0.090,tg=0.025,fs=268,evr=[3,2.8,2.7,2.6,2.5],evf=[17,16,16,16,16],
    hl="Cycle recovers as priced; mix nudges margins.",
    narr=["The modal path: 2026 is the bottom (per CEO John May), the ag cycle recovers along its normal arc, and structurally higher trough margins plus a growing precision-ag recurring-revenue stream (See & Spray, autonomy, JDLink ARR) lift operating margin back toward 17-18% by FY30. Revenue compounds mid-single-digit off the trough to ~$60B.","DCF ~$447 (-23%) — the recovery the bull narrates is largely what today's price already embeds; at a full multiple on trough FCF the modal mid-cycle outcome lands below spot. Roughly the expected normalization, already priced."],
    pr="Requires the cycle to recover on a normal timeline with the mix nudging mid-cycle margins higher - consistent with management calling 2026 the bottom and the C&F/small-ag recovery already underway. 34% as the central outcome; the recovery is real but discounted."),
  "bull":dict(p=0.17,g=[0.08,0.11,0.09,0.07,0.06],fcfm=[0.14,0.15,0.16,0.16,0.17],opm=[0.17,0.18,0.19,0.20,0.20],wacc=0.085,tg=0.030,fs=265,evr=[3.5,3.3,3.1,3,2.9],evf=[20,19,19,19,19],
    hl="Cycle turns + precision ag de-cyclicalizes.",
    narr=["The cycle inflects with operating leverage and the precision-ag thesis lands: See & Spray, autonomous tractors and JDLink convert into a meaningful recurring software/ARR stream that lifts structural margins and dampens the boom-bust swing. Operating margin reaches ~20% on a faster recovery; revenue compounds high-single-digit.","DCF ~$655 (+13.5%) - if recurring precision-ag revenue genuinely de-cyclicalizes the mix and the cycle turns with leverage, the full multiple is justified and the stock re-rates above spot. The core of the bull."],
    pr="The cycle bottom + operating leverage on recovery + a precision-ag recurring-revenue mix structurally lifting mid-cycle margins - the swing factor playing out. ~17% weight on the de-cyclicalization being real."),
  "ultra_bull":dict(p=0.08,g=[0.10,0.13,0.11,0.09,0.07],fcfm=[0.15,0.16,0.17,0.18,0.18],opm=[0.18,0.19,0.20,0.21,0.22],wacc=0.082,tg=0.030,fs=262,evr=[4,3.8,3.6,3.4,3.2],evf=[22,21,20,20,20],
    hl="Precision-ag platform re-rates the cycle away.",
    narr=["The full second act: autonomy and a See & Spray / JDLink software platform scale into a high-margin recurring layer large enough that the market re-rates Deere from a cyclical toward a precision-agriculture technology compounder, while a strong cycle recovery adds leverage on top. Operating margin pushes past 22%.","DCF ~$810 (+40%) - the platform mix earns a premium multiple and the cyclicality discount compresses; ~8% probability, the asymmetric upside above a justified full price.","An equipment cyclical that becomes a recurring-revenue ag-tech platform escapes the trough-multiple trap entirely - the long-duration tail."],
    pr="Everything works - cycle recovery AND operating leverage AND precision-ag recurring revenue scaling into a platform re-rate. ~8%, the long-duration tail."),
 },
 wr=[("Ultra Bear 14%","Deeper, longer ag recession; trough deepens; ~$219 (-62%)."),
     ("Bear 27%","Recovery is slow; trough margins stick; ~$342 (-41%)."),
     ("Base 34%","Cycle recovers as priced; mix nudges margins; ~$447 (-23%)."),
     ("Bull 17%","Cycle turns + precision ag de-cyclicalizes; ~$655 (+13.5%)."),
     ("Ultra Bull 8%","Precision-ag platform re-rates the cycle away; ~$810 (+40%).")],
 pb=[("Modeled debt EXCLUDES the ~$45B captive lender.","The DCF carries only ~$13.8B equipment-ops debt; Deere Capital's ~$45B borrowings (offset by finance receivables) are left out - the consolidated-FCF DCF is a simplification of a company with a large captive lender, so read the equity bridge as approximate."),
     ("A full multiple on trough earnings already prices the recovery.","~26x trough FCF (~17x near the bottom) embeds the upturn; buying a cyclical at the trough is right, but paying a full price for it leaves the modal case at -23%."),
     ("Precision ag is the de-cyclicalizing bull, not yet the base.","See & Spray / autonomy / JDLink build recurring ARR, but the mix is still small (PPA op profit -39% this quarter); it lifts the bull, and only structurally shifts margins if it scales."),
     ("2026 is management's called bottom.","CEO John May calls 2026 the cycle bottom; C&F (+29%/+48%) and small-ag (+16%) are already recovering while large-ag (-14%) troughs - the leading legs are turning first."),
     ("Tariffs are a real, sized drag.","~$200M/qtr (~$1.2B FY) tariff headwind, partly mitigated via reshoring/USMCA, but it caps the near-term margin recovery the recovery thesis needs.")],
 tr=[("Bull validation","large-ag (Production & Precision Ag) returns to order-book growth  ·  operating margin recovers toward 18-20% on leverage  ·  precision-ag recurring/ARR revenue grows to a disclosed, material share  ·  net price holds +1.5-2% with lean field inventories"),
     ("Bear validation","large-ag declines worsen past -20% as farm income stays weak  ·  used-equipment inventories overhang new-equipment sales  ·  operating margin stays stuck in the low-teens  ·  tariff drag widens beyond ~$1.2B"),
     ("Reframe needed","if the precision-ag recurring mix fails to scale and margins keep reverting to the boom-bust equipment cycle, re-rate the terminal toward a normal mid-cycle capital-goods multiple - not a de-cyclicalized platform")],
 gloss=[("Production & Precision Ag (PPA)","Deere's largest segment - large tractors, combines, planters + the precision-ag tech layer; -14%/op profit -39% this quarter, the cycle trough and the swing-factor segment."),
        ("Precision ag / recurring revenue","Software-and-service layer (See & Spray targeted spraying, autonomous tractors, JDLink connectivity/ARR) that adds recurring revenue and, the bull argues, de-cyclicalizes equipment margins."),
        ("Ag down-cycle","The boom-bust farm-equipment cycle driven by crop prices and farm income; revenue fell from a $61.3B FY23 peak to $45.7B FY25 - the trough this memo prices off."),
        ("Captive finance (Deere Capital)","Deere's in-house lender financing dealer/customer equipment purchases; ~$45B of borrowings offset by finance receivables, EXCLUDED from the modeled debt - the memo's required caveat."),
        ("FCF margin","Free cash flow / revenue (~13% FY25 at the trough); the mature-DCF swing factor - whether cycle recovery + the precision-ag mix lift it durably above the trough.")],
 arena="Farm + construction equipment - Deere (scale leader, dealer network + installed base, emerging precision-ag tech) vs CNH Industrial, AGCO, Kubota in ag and Caterpillar/Komatsu in construction; auditing a scale + cornered-resource Power against the ag cycle and tariffs.",
 powers=[("scale_economies",4,"Dominant Power: #1 global ag-equipment maker with R&D, manufacturing and parts scale peers can't match; structurally higher trough margins than prior cycles."),
         ("network_economies",1,"JDLink/Operations Center data network is growing but not yet a hard network effect; emerging with precision ag."),
         ("counter_positioning",1,"The incumbent, not the disruptor; precision-ag autonomy is more extension than counter-position."),
         ("switching_costs",3,"Real: an installed fleet, dealer service relationships, JDLink data lock-in and operator familiarity make a farmer's next purchase sticky."),
         ("branding",3,"The green brand commands a price premium and resale value, but doesn't override the ag cycle."),
         ("cornered_resource",3,"The exclusive franchised dealer network + the largest installed base - hard to replicate, the distribution moat under the scale Power."),
         ("process_power",2,"Nascent: precision-ag/autonomy (See & Spray, autonomous tractors) is a building manufacturing+software capability, unproven as a durable margin shifter at scale.")],
 dom="scale_economies", dur="high",
 rivals=[("CNH Industrial","public","Case IH / New Holland - the #2 full-line ag player; the direct large-ag share comp, also cycle-pressured.",0.0,0.10,"~10x P/E"),
         ("AGCO","public","Fendt/Massey Ferguson - pure-play ag, smaller and more cyclical; the precision-ag (PTx) challenger.",0.0,0.08,"~12x P/E"),
         ("Caterpillar (CAT)","public","Construction/mining scale leader; overlaps Deere's C&F segment, the construction-cycle comp.",0.05,0.20,"~18x P/E"),
         ("Kubota","private","Strong in compact/small-ag and Asia; smaller-equipment share pressure, not the large-ag core.",None,None,"~12x P/E")],
 threats=[("scale_economies","The ag down-cycle + tariffs","Large-ag declines worsen and operating margin stays stuck in the low-teens, showing the trough is deeper/longer than priced."),
          ("process_power","CNH PTx / AGCO precision-ag challengers","A rival's precision-ag platform wins data/autonomy share, capping the recurring-revenue mix that the bull needs to de-cyclicalize margins."),
          ("cornered_resource","Direct-to-farmer / dealer-model disruption","Right-to-repair pressure or new distribution erodes the dealer-network + JDLink lock-in that anchors switching costs.")],
 take="Deere's scale Power is durable (high) - the #1 ag-equipment maker with a cornered dealer network, the largest installed base, and real switching costs from fleets and JDLink data; the structurally higher trough margins this cycle are evidence the moat is widening. The Audit: the live threats are the ag cycle itself plus ~$1.2B of tariffs (which compress margins regardless of moat), and the contest over whether precision ag (See & Spray, autonomy) scales into a recurring-revenue layer that de-cyclicalizes the mix - or whether rivals (CNH PTx, AGCO) split that prize. That squares with the -21.8% finding: the franchise is excellent, but bought at ~26x trough FCF the modal recovery is already priced, and only the bull's de-cyclicalization (or a strong cycle turn) justifies the full multiple.",
)

if __name__ == "__main__":
    build(SPEC)
