#!/usr/bin/env python3
"""YOU — Clear Secure (NYSE) mature-company memo spec. Emits data/_intake/you.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 1856314; IPO Jun 2021). Numbers copied VERBATIM from
NUM["YOU"] in /tmp/funspec/numbers.py — DO NOT CHANGE ANY NUMBER."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="YOU", company="Clear Secure", exch="NYSE", spot=50.25,
 cap=4.77, sh=95.0, cash=0.80, net_debt=0.0, rev_b=0.901,
 wl="fun-speculative", tier="Low", themes=["identity-trust-security"],
 extras=[
   "Net cash ~$0.80B (~$171M cash + ~$629M marketable securities), no debt; ~95M economic shares (estimate)",
   "Revenue $0.901B FY25 (+19.7% in Q1'26); GAAP op margin 20.7%; FCF ~$0.30B (~30% margin) off the deferred-revenue model",
   "~$50, YTD ~+55% / TTM ~+41% (52-wk $24.06-$62.73); ~13x EV/FCF; quarterly + special dividend + buyback"],
 cq="Is Clear Secure a maturing airport-lane subscription decelerating to terminal growth, or a horizontal identity-verification network expanding past the airport?",
 thesis="Clear Secure trades at ~$4.77B (~$50.25, up ~55% YTD / ~41% TTM) — about 13x EV/FCF on $0.901B revenue growing ~20%, with a deferred-revenue membership model that throws off a ~30% FCF margin, net cash ~$0.80B and no debt. Capital return is aggressive (quarterly + special dividends plus a buyback). The fork the DCF resolves: airport CLEAR Plus saturating against a US frequent-flyer ceiling (with TSA's own free touchless ID commoditizing the lane) versus the identity platform — TSA PreCheck enrollment, biometric eGates, enterprise verification — extending the network. The modal case lands ~+40%, so the distribution leans to cheap quality despite the run.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[0.30,0.40,0.60,0.77,0.90]),
   ("history_op_margin",[-45.3,-29.5,3.3,16.0,20.7]),
   ("history_fcf",[0.02,0.10,0.20,0.30,0.30]),
   ("history_ev_rev",[10,6,5,4.5,4.4])],
 p3cfg=[("segment_a","CLEAR Plus (airport)"),("segment_b","Platform / identity"),
   ("hist_ent_split",[0.95,0.95,0.93,0.92,0.90]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  Q1 FY2026 results",
 sources="Sources: SEC XBRL company facts (CIK 1856314; revenue, GAAP operating income/margin, cash flow), Clear Secure Q1 FY2026 release (revenue $253.0M/+19.7%, total CLEAR Members 40.99M/+31.3%, active CLEAR Plus 8.17M/+13.0%, FCF $185.5M/+103%, total bookings $291.7M/+40.8%, adj EBITDA $80.6M/31.9% margin). Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs subscription/identity peers (Okta, deferred-revenue SaaS). Share count ~95M economic is an estimate (XBRL did not tag a clean consolidated count); net cash ~$0.80B (the cash tag understated marketable securities); dual-class governance gives the founder voting control over minority economic holders.",
 ipo="IPO Jun '21", xmin=-4.7,
 points=[[-4.7,31],[-4.0,40],[-3.3,18],[-2.5,15],[-1.5,30],[-0.8,40],[-0.3,62],[-0.05,50.25]],
 scn={
  "ultra_bear":dict(p=0.14,g=[0.03,0.03,0.02,0.02,0.02],fcfm=[0.24,0.25,0.26,0.26,0.27],opm=[0.18,0.19,0.20,0.20,0.21],wacc=0.105,tg=0.020,fs=95,evr=[3,2.7,2.5,2.4,2.3],evf=[11,11,11,11,11],
    hl="Airport saturates; TSA commoditizes the lane.",
    narr=["CLEAR Plus hits the US frequent-flyer ceiling and TSA's own free touchless-ID rollout commoditizes the value prop: active members flatten, pricing power fades, and the platform never carries the load. Revenue creeps ~2-3%/yr and FCF margin slips toward ~24% as growth spend persists against a stalled base.","A maturing single-product subscription that has stopped compounding earns a low-growth, ~11x EV/FCF terminal -> DCF ~$39 (-22%). Net cash sets a floor but can't offset a saturated airport network."],
    pr="The genuine bear: CLEAR Plus growth already decelerated to +13% while total members grew +31%, and TSA owns the airport checkpoint and is fielding its own biometric ID. 14% weight on saturation plus regulatory commoditization."),
  "bear":dict(p=0.27,g=[0.08,0.07,0.06,0.05,0.05],fcfm=[0.27,0.28,0.29,0.30,0.30],opm=[0.21,0.22,0.23,0.24,0.24],wacc=0.100,tg=0.025,fs=94,evr=[3.5,3.3,3.1,3.0,2.9],evf=[13,13,13,13,13],
    hl="Members grow slowly; platform stays optional.",
    narr=["Membership keeps adding at a decelerating pace on price and modest lane growth, but the identity platform (PreCheck, eGates, enterprise) stays a small adjacency rather than a second engine. Revenue compounds ~6% to ~$1.2B at a steady ~28-30% FCF margin.","DCF ~$54 (+8%) — a high-margin, net-cash subscription that grows but doesn't break out is worth modestly above today's price; most of the return is the FCF yield plus capital return, not re-rating."],
    pr="Lane growth and pricing continue but the platform doesn't inflect; a durable cash machine that decelerates toward terminal growth. 27% as the plausible 'compounds slowly' path."),
  "base":dict(p=0.34,g=[0.13,0.11,0.10,0.08,0.07],fcfm=[0.29,0.30,0.31,0.32,0.32],opm=[0.23,0.25,0.26,0.27,0.28],wacc=0.095,tg=0.025,fs=93,evr=[4,3.8,3.6,3.5,3.4],evf=[15,15,15,15,15],
    hl="Members compound; platform begins to carry.",
    narr=["The modal path: CLEAR Plus keeps adding members at ~13% with pricing, eGates roll past 50% of the network, the new TSA PreCheck enrollment channel scales, and the platform starts contributing — blending to ~10% revenue growth at a defended ~30%+ FCF margin. Revenue compounds toward ~$1.4B.","DCF ~$70 (+40%) — a ~20%-FCF-margin compounder at ~15x EV/FCF, net cash, returning capital, is mispriced if the modal case plays out; this is the core of the finding."],
    pr="Requires continued member/pricing growth and the platform beginning to carry (PreCheck, eGates) — consistent with Q1 bookings +41% and the raised FCF outlook, not a step-change. 34% as the central outcome."),
  "bull":dict(p=0.17,g=[0.17,0.15,0.13,0.11,0.10],fcfm=[0.31,0.32,0.33,0.34,0.34],opm=[0.25,0.27,0.29,0.31,0.32],wacc=0.090,tg=0.030,fs=92,evr=[4.5,4.3,4.1,4.0,3.9],evf=[18,18,18,18,18],
    hl="Identity platform becomes the second act.",
    narr=["The platform expansion lands: CLEAR's enrolled biometric identity becomes a horizontal verification layer beyond airport lanes — PreCheck enrollment at scale, eGates across the network, stadiums and enterprise/everyday identity verification — so the platform segment grows into a real second revenue stream on top of the membership base. Revenue compounds ~13% to ~$1.7B at a ~33% FCF margin.","DCF ~$96 (+92%) — if the enrolled-identity network extends past airports, it re-rates toward a platform multiple; this is the genuine ultra_bull second act, not a lift to the airport business."],
    pr="The platform optionality is real and observable (3rd authorized PreCheck enroller, eGates >50% of airports, CLEAR Plus opened to 40+ more countries, enterprise verification). ~17% weight on it becoming a second engine."),
  "ultra_bull":dict(p=0.08,g=[0.21,0.18,0.16,0.14,0.12],fcfm=[0.32,0.34,0.35,0.36,0.36],opm=[0.27,0.29,0.32,0.34,0.35],wacc=0.088,tg=0.030,fs=91,evr=[5,4.8,4.6,4.5,4.4],evf=[20,19,19,19,19],
    hl="Horizontal identity network; platform re-rate.",
    narr=["The full second act: the enrolled biometric identity becomes the default verification rail across travel, venues and enterprise, the platform out-scales the airport base, and CLEAR re-rates to a network-platform multiple at a peak ~36% FCF margin. Revenue compounds ~16% to ~$1.9B.","DCF ~$118 (+136%) — the enrolled-identity network compounds as a horizontal platform; ~8% probability, the asymmetric upside the entry is buying."],
    pr="Everything works — members AND pricing AND a horizontal identity platform AND a multiple re-rate. ~8%, the long-duration tail on the network becoming the verification standard."),
 },
 wr=[("Ultra Bear 14%","Airport saturates; TSA commoditizes; ~$39 (-22%)."),
     ("Bear 27%","Members grow slowly; platform optional; ~$54 (+8%)."),
     ("Base 34%","Members compound; platform carries; ~$70 (+40%)."),
     ("Bull 17%","Identity platform second act; ~$96 (+92%)."),
     ("Ultra Bull 8%","Horizontal identity network; ~$118 (+136%).")],
 pb=[("~13x EV/FCF for a ~30%-margin, net-cash compounder.","A deferred-revenue model throwing off ~30% FCF margin growing ~20%, net cash ~$0.80B, returning capital — priced cheaply for the quality; the modal DCF is +40%."),
     ("The deferred-revenue model is the FCF engine.","Members pay upfront, so bookings (+41% in Q1) lead revenue and FCF (~$186M, +103% YoY) runs well ahead of accrual earnings — the cash machine, not the GAAP line, is the asset."),
     ("Saturation is the real bear, not solvency.","Net cash, no debt, ~30% FCF margin — there is no survival risk; the downside is a US frequent-flyer ceiling plus free TSA touchless ID, i.e. terminal growth and multiple, not failure."),
     ("The platform is a genuine second act.","3rd authorized TSA PreCheck enroller, eGates in 30+ airports (>50% of the network), 40+ more countries, stadiums/enterprise — observable expansion of the enrolled-identity network beyond airport lanes."),
     ("Dual-class governance is a flag.","Founder voting control over minority economic holders, plus a ~95M economic share count that is an estimate (XBRL did not tag a clean consolidated count) — a governance/disclosure caveat to size against, not a fundamentals input.")],
 tr=[("Bull validation","platform/identity revenue scales as a distinct stream  ·  PreCheck enrollment + eGates ramp network-wide  ·  enterprise/everyday verification wins land  ·  CLEAR Plus active members re-accelerate above mid-teens"),
     ("Bear validation","CLEAR Plus active-member growth decays toward flat  ·  TSA's free touchless ID rolls out broadly and pricing power fades  ·  platform revenue stays an immaterial adjacency  ·  bookings growth converges down to revenue growth"),
     ("Reframe needed","if the airport network saturates and the platform never carries, re-rate the terminal toward a low-growth single-product subscription; separately, the dual-class governance + estimated share count are standing caveats on any per-share read")],
 gloss=[("CLEAR Plus","The paid airport-security membership (~8.17M active, +13%) that gives expedited identity verification in airport lanes — the core, mature revenue base and the saturation question."),
        ("Total CLEAR Members","All enrolled identities (~40.99M, +31%), most free, spanning airports, venues and the platform — the top of the funnel CLEAR aims to convert and monetize via the identity network."),
        ("Deferred revenue / bookings","Members prepay, so cash bookings (~$291.7M, +41%) are collected ahead of recognized revenue — the mechanism behind the ~30% FCF margin and FCF (~$186M) running ahead of GAAP earnings."),
        ("TSA PreCheck / eGates","Government expedited-screening enrollment (CLEAR is the 3rd authorized provider) and biometric airport gates (>50% of the network) — the rails through which the identity platform expands beyond CLEAR Plus lanes."),
        ("FCF margin","Free cash flow / revenue (~30% FY25, lifted by deferred-revenue prepayment); the mature-DCF swing factor — whether membership and the platform sustain ~30% cash conversion at scale.")],
 arena="Identity verification / expedited airport security — Clear Secure (CLEAR Plus lanes + an enrolled biometric identity network, ~$0.9B revenue) vs TSA PreCheck (and TSA's own free touchless ID), Idemia/airport biometrics, and identity-verification platforms (Okta, Onfido, Yoti, government eID); auditing switching costs + a cornered-resource identity network against saturation and regulatory commoditization.",
 powers=[("scale_economies",2,"Enrollment/marketing leverage over a ~41M-member base, but airport infrastructure spend is real and the absolute scale is small."),
         ("network_economies",2,"More enrolled identities make CLEAR more useful to venues/partners, but it is one-sided (users, not a true two-sided market) — emerging, not dominant."),
         ("counter_positioning",1,"Was the consumer-paid fast-lane disruptor; now the incumbent, and TSA's free touchless ID counter-positions the paid value prop."),
         ("switching_costs",3,"A dominant Power: enrolled biometrics + the renewing membership habit make re-enrolling elsewhere a friction, sticky once a frequent flyer is in the network."),
         ("branding",2,"Recognized travel brand (the visible airport lanes), but it is a convenience brand, not pricing-power-defining the way a premium consumer brand is."),
         ("cornered_resource",3,"The other dominant Power: the enrolled biometric identity dataset + secured airport real-estate footprint — hard for a new entrant to replicate, though contingent on airport/TSA contracts."),
         ("process_power",2,"Biometric enrollment + verification operations and the deferred-revenue engine; real but replicable.")],
 dom="cornered_resource", dur="medium",
 rivals=[("TSA PreCheck (incl. free touchless ID)","public","The government incumbent at the checkpoint; its own free biometric ID is the central commoditization threat to the paid lane.",None,None,"government"),
         ("Idemia / airport biometrics","private","Supplies biometric checkpoint hardware/ID to TSA and airports; an infrastructure competitor to CLEAR's lane economics.",None,None,"private"),
         ("Okta","public","Enterprise identity/verification platform; the comp if CLEAR's platform becomes a horizontal identity layer, and a margin/multiple benchmark.",0.13,0.22,"~30x EV/FCF"),
         ("Onfido / Yoti / government eID","private","Identity-verification challengers and national digital-ID schemes; pressure on the platform's everyday-verification ambition.",None,None,"private")],
 threats=[("cornered_resource","TSA's own free touchless ID","CLEAR Plus active-member growth decays toward flat as the free government biometric lane commoditizes the paid value prop."),
          ("switching_costs","US frequent-flyer saturation","The addressable frequent-flyer base is exhausted; net active CLEAR Plus members plateau despite pricing."),
          ("network_economies","Identity-verification platforms (Okta/Onfido/government eID)","The platform/identity segment stays an immaterial adjacency while rivals own enterprise/everyday verification.")],
 take="Clear Secure's Powers are switching costs (an enrolled biometric identity + the renewing membership habit) and a cornered resource (the enrolled-identity dataset + secured airport footprint) — genuine but airport-contingent. The Audit: the cornered resource is durable (medium) only as long as the airport network holds and the platform extends it; the live threats are US frequent-flyer saturation and, more pointedly, TSA's own free touchless ID commoditizing the paid lane. That fork drives the terminal growth rate, and the DCF prices both sides — a saturating single-product subscription in the ultra-bear (-22%) against a horizontal identity network in the bull/ultra-bull (+92% / +136%). The modal case has members compounding while the platform begins to carry (+40%), so a ~30%-FCF-margin, net-cash, capital-returning compounder at ~13x EV/FCF screens as cheap quality despite the YTD run. Standing caveats on any per-share read: dual-class governance (founder voting control over minority economic holders) and a ~95M economic share count that is an estimate.",
)

if __name__ == "__main__":
    build(SPEC)
