#!/usr/bin/env python3
"""ADSK — Autodesk (NASDAQ) mature-company memo spec. Emits data/_intake/adsk.yml
via the reusable builder (gen_b1.build). Numerics LOCKED in model_mature; op-margin
history GAAP from SEC XBRL (CIK 769397). Fiscal year ends ~late January (FY22-FY26)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="ADSK", company="Autodesk", exch="NASDAQ", spot=198.43,
 cap=41.87, sh=211.0, cash=2.60, net_debt=2.50, rev_b=7.206,
 wl="fcf-plus-plus-growth", tier="Low", themes=["creator-design-software"],
 extras=[
   "$2.60B cash vs $2.50B debt — roughly net-cash-neutral (~$0.1B net cash); ~211M shares; ~$448M buyback in Q1 FY27",
   "Revenue $7.21B FY26 (+18% as-reported); GAAP op margin ~21.9%, non-GAAP ~39%; FCF $2.4B; ~98% subscription/recurring",
   "Down ~31% YTD to ~$198, near the 52-week low (~$205-$329 range); Starboard (~$500M, proxy fight) pushing margins"],
 cq="Does mission-critical CAD lock-in plus a Starboard-forced margin expansion to ~45% offset a maturing top line — or has growth matured into the price?",
 thesis="Autodesk trades at ~$41.9B (~$198, down ~31% YTD near the 52-week low) — ~17x FCF on $7.21B revenue, a ~98%-recurring CAD/design franchise, roughly net-cash-neutral. The +18% as-reported growth is flattered by an agency->direct billing change; underlying (cc, model-adjusted) growth is nearer ~8-12%. The bull is durable switching-cost lock-in plus a Starboard-forced lift toward ~45% operating margin by FY28; the bear is maturing growth and activist/execution noise. The weighted finding is +53.6%: even the bear is +9% and the modal case lands +53%, so on the lower underlying growth the de-rate looks like cheap quality with a margin catalyst.",
 chartref=[("history_years",[2022,2023,2024,2025,2026]),
   ("history_revenue",[4.4,5.0,5.5,6.1,7.21]),
   ("history_op_margin",[14.1,19.8,20.5,22.1,21.9]),
   ("history_fcf",[1.5,2.0,1.3,1.6,2.4]),
   ("history_ev_rev",[12,9,8,7,5.8])],
 p3cfg=[("segment_a","AEC + Manufacturing"),("segment_b","Media & Other"),
   ("hist_ent_split",[0.85,0.86,0.87,0.88,0.88]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY22-FY26 history + FY26-FY30 scenario projections  ·  fiscal years end late Jan  ·  FQ1 FY2027 (Apr'26) results",
 sources="Sources: SEC XBRL company facts (CIK 769397; revenue, GAAP operating income/margin, cash flow, debt), Autodesk FQ1 FY2027 release (revenue $1.93B/+18% cc +16%, billings $2.13B/+18%, non-GAAP operating margin ~39%, FCF $876M/+58% seasonal peak, RPO $7.81B/+9%, ~$448M buyback), Starboard ~$500M stake / ~45% FY28 operating-margin push. Revenue modeled as a growth-rate path off FY26 (base uses underlying cc/model-adjusted ~8-12%, NOT the +18% headline); FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/sales & EV/FCF vs design/SaaS peers (PTC, ANSS, ADBE, DASSY).",
 ipo="IPO '85", xmin=-5.5,
 points=[[-5.5,280],[-5.0,300],[-4.2,200],[-3.3,180],[-2.5,200],[-1.5,250],[-0.8,290],[-0.3,329],[-0.1,205],[-0.05,198.43]],
 scn={
  "ultra_bear":dict(p=0.13,g=[0.04,0.04,0.04,0.04,0.04],fcfm=[0.24,0.25,0.26,0.26,0.27],opm=[0.20,0.21,0.22,0.22,0.23],wacc=0.095,tg=0.030,fs=214,evr=[4,3.5,3.2,3,2.8],evf=[16,15,15,15,15],
    hl="Growth stalls; activist fizzles.",
    narr=["Underlying growth keeps fading toward ~4% as construction/manufacturing softens and the model-transition tailwind rolls off, while the Starboard campaign stalls: margins inch up but never approach the ~45% target. The franchise holds but compounds slowly off a flat top line.","A slow-growth, ~mid-20s% FCF-margin software franchise de-rates to a ~15x terminal FCF multiple -> DCF ~$149 (-25%). The recurring base and near-net-cash balance sheet set the floor, but a stalled catalyst caps the value below today's price."],
    pr="The genuine bear: growth is already maturing (decelerating mid-teens before the billing flatter), activist campaigns can stall, and a construction/manufacturing cycle can bite. 13% weight on growth stalling with the margin lift fizzling."),
  "bear":dict(p=0.26,g=[0.07,0.07,0.06,0.06,0.06],fcfm=[0.27,0.28,0.29,0.30,0.30],opm=[0.23,0.24,0.25,0.26,0.27],wacc=0.090,tg=0.035,fs=212,evr=[5,4.5,4.2,4,3.8],evf=[19,18,18,18,18],
    hl="Underlying ~6%; partial margin lift.",
    narr=["Underlying growth settles around ~6% as AEC and cloud (Forma/Fusion) only partly offset a maturing core, and Starboard wins a partial cost program — operating margin grinds from low-20s toward ~27%, well short of ~45%. FCF margin firms toward ~30% but the re-rate is muted.","DCF ~$216 (+9%) — even a 'matures but defends, margins only partly improve' path clears today's price modestly. The switching-cost lock-in keeps the multiple from collapsing; the upside is capped without the full margin program."],
    pr="Lock-in holds and Starboard extracts some efficiency, but growth deceleration and execution noise keep the lift partial. 26% as the plausible 'defends but under-delivers the activist plan' path."),
  "base":dict(p=0.34,g=[0.10,0.10,0.09,0.08,0.08],fcfm=[0.29,0.31,0.32,0.33,0.34],opm=[0.25,0.27,0.29,0.31,0.33],wacc=0.085,tg=0.035,fs=210,evr=[6,5.5,5.2,5,4.8],evf=[22,21,21,21,21],
    hl="Underlying ~8-12%; margins march to mid-30s.",
    narr=["The modal path: underlying (cc, model-adjusted) growth holds ~8-12% as AEC/construction and cloud/AI (Fusion, Forma, agentic AI) compound on a mission-critical, ~98%-recurring base, while Starboard-driven cost discipline lifts operating margin from ~22% toward the mid-30s en route to the ~45% goal. FCF margin expands toward ~34%.","DCF ~$304 (+53%) — durable lock-in plus a credible margin program at ~21x terminal FCF re-rates the de-rated entry. On the lower underlying growth (not the +18% headline) the modal case still recovers well above spot; this is the core of the finding."],
    pr="Requires lock-in to hold ~8-12% underlying growth AND Starboard to push margins materially higher over FY27-FY28 — consistent with the ~$500M stake, the comp realignment, and the under-earned margin gap. 34% as the central outcome."),
  "bull":dict(p=0.19,g=[0.12,0.11,0.10,0.10,0.09],fcfm=[0.31,0.33,0.35,0.36,0.37],opm=[0.28,0.31,0.34,0.36,0.38],wacc=0.080,tg=0.040,fs=208,evr=[7,6.5,6.2,6,5.8],evf=[26,26,26,26,26],
    hl="Activist delivers; margins near 45%.",
    narr=["Starboard's program lands close to plan: operating margin marches toward ~38% by FY30 (the ~45% adjusted target on a non-GAAP basis) on sales-optimization, headcount, and capital return, while AEC/construction + cloud/AI keep underlying growth low-teens. FCF margin inflects toward ~37%.","DCF ~$437 (+120%) - if the under-earned margin gap closes against a still-growing, locked-in franchise, the entry re-rates to a high-quality compounder multiple. This is the activist-success core of the bull."],
    pr="Starboard's record plus a genuinely under-earned margin structure make a large lift credible; lock-in protects growth while costs are cut. ~19% weight on the activist plan substantially landing."),
  "ultra_bull":dict(p=0.08,g=[0.14,0.13,0.12,0.11,0.10],fcfm=[0.32,0.35,0.37,0.39,0.40],opm=[0.30,0.34,0.38,0.41,0.43],wacc=0.078,tg=0.040,fs=206,evr=[8,7.5,7,6.8,6.6],evf=[28,27,27,27,27],
    hl="Margins hit ~45%; AI/cloud re-accelerate.",
    narr=["The full second act: Starboard's ~45% operating margin is reached, AI/cloud (Fusion, Forma, agentic design) re-accelerate underlying growth into the low-to-mid-teens, and Autodesk compounds as both a margin and a platform story. FCF margin reaches ~40%.","DCF ~$537 (+171%) - the franchise re-rates to a premium design-platform multiple as growth AND margins both inflect; ~8% probability, the long-duration tail the depressed entry is buying."],
    pr="Everything works - the full activist margin target AND an AI/cloud growth re-acceleration AND a multiple re-rate. ~8%, the asymmetric upside."),
 },
 wr=[("Ultra Bear 13%","Growth stalls; activist fizzles; ~$149 (-25%)."),
     ("Bear 26%","Underlying ~6%; partial margin lift; ~$216 (+9%)."),
     ("Base 34%","Underlying ~8-12%; margins to mid-30s; ~$304 (+53%)."),
     ("Bull 19%","Activist delivers; margins near 45%; ~$437 (+120%)."),
     ("Ultra Bull 8%","~45% margin + AI/cloud re-accel; ~$537 (+171%).")],
 pb=[("The +18% growth is a billing-model mirage.","The agency->direct 'new transaction model' inflates as-reported revenue/billings/FCF; the base case uses the lower underlying (cc, model-adjusted) ~8-12%, and still lands +53%."),
     ("Switching costs are the real moat.","CAD/file-format lock-in (.dwg/.rvt, trained workforces, BIM mandates) makes Autodesk mission-critical and sticky — the durability the multiple rests on, not the growth rate."),
     ("Starboard is forcing an under-earned margin.","A ~$500M stake and proxy fight pushing ~45% operating margin by FY28 (~1,000bps) against ~22% today is the explicit margin catalyst — a process-power lever, not a growth bet."),
     ("Maturing growth is the live risk.","Decelerating mid-teens (before the billing flatter), cyclical construction/manufacturing exposure, and execution/CEO noise are why the bear (+9%) and ultra-bear (-25%) stay in play."),
     ("Roughly net-cash-neutral, p_fail ~0.","$2.60B cash vs $2.50B debt (~$0.1B net cash) on $2.4B FCF — no solvency risk; the downside is the multiple and the margin execution, not survival.")],
 tr=[("Bull validation","Starboard margin program ratified, operating margin steps toward mid-30s+  ·  underlying (cc/model-adjusted) growth holds >=8%  ·  RPO/billings re-accelerate ex-model-change  ·  AEC/construction + cloud keep outperforming"),
     ("Bear validation","underlying growth decelerates below ~6% ex-billing-change  ·  the activist program is rebuffed or stalls and margins stay near ~22%  ·  construction/manufacturing cycle turns down  ·  CEO/execution disruption from the proxy fight"),
     ("Reframe needed","if the lock-in cracks (a credible cloud-CAD challenger or open file formats erode .dwg/.rvt switching costs) OR Starboard exits with margins unchanged, re-rate the terminal toward a slow-growth, mid-20s-margin software multiple")],
 gloss=[("Switching costs","Helmer Power: CAD/file-format lock-in (.dwg/.rvt), trained workforces, and BIM mandates that make leaving Autodesk costly — the dominant, durable moat the multiple rests on."),
        ("AEC","Architecture, Engineering & Construction — Autodesk's largest segment (Revit, AutoCAD, Construction Cloud); the outperforming end-market plus Manufacturing (Fusion) drives the top line."),
        ("New transaction model","The agency->direct billing change that inflates as-reported revenue/billings/FCF growth; the base case strips it out to the lower underlying (cc, model-adjusted) ~8-12% rate."),
        ("Starboard / activist","Starboard Value's ~$500M stake and proxy fight pushing ~45% adjusted operating margin by FY28, comp realignment, and a CEO reassessment — the explicit margin catalyst (a process-power story)."),
        ("FCF margin","Free cash flow / revenue (~33% FY26 as-reported); the mature-DCF swing factor — whether the activist-forced operating-margin lift toward ~45% converts to free cash flow.")],
 arena="Design/engineering software — Autodesk (CAD/BIM franchise: AutoCAD, Revit, Fusion, Construction Cloud) vs PTC, Dassault, Ansys, Bentley, Adobe, and emerging cloud-CAD; auditing a switching-cost Power against maturing growth and an activist-forced margin reset.",
 powers=[("scale_economies",3,"R&D and go-to-market leverage across a ~$7.2B, ~98%-recurring base; large vs CAD peers, the cost base Starboard is targeting."),
         ("network_economies",2,"File-format + ecosystem effects (.dwg/.rvt as industry standards, partner/plug-in ecosystem) — real but more standard than two-sided network."),
         ("counter_positioning",1,"Was the desktop-CAD disruptor; now the subscription incumbent, with cloud-CAD challengers counter-positioning against it."),
         ("switching_costs",4,"The dominant Power: CAD/file-format lock-in (.dwg/.rvt), trained workforces, BIM mandates and deep workflow integration make migration costly and rare."),
         ("branding",3,"AutoCAD/Revit are category-defining, mission-critical brands with pricing power across architecture/engineering/manufacturing."),
         ("cornered_resource",2,"The installed file-format standards + decades of drawing data are a quasi-cornered asset, though not legally exclusive."),
         ("process_power",2,"Emerging via the Starboard cost program (sales-optimization, comp realignment) and cloud/AI delivery — the margin-expansion lever, unproven at the ~45% target.")],
 dom="switching_costs", dur="high",
 rivals=[("PTC","public","CAD/PLM peer (Creo, Windchill); recurring-software comp on growth and margin.",0.10,0.27,"~30x EV/FCF"),
         ("Dassault Systemes","public","CAD/PLM scale leader (SolidWorks, CATIA, 3DEXPERIENCE); the closest large-cap design franchise.",0.08,0.30,"~30x P/E"),
         ("Ansys","public","Simulation leader (now Synopsys-owned); adjacency in engineering software.",0.11,0.40,"~30x EV/FCF"),
         ("Bentley Systems","public","Infrastructure-engineering software; direct AEC competitor in civil/infrastructure.",0.10,0.28,"~35x P/E")],
 threats=[("switching_costs","Cloud-CAD challengers / open file formats","A credible browser-native CAD platform or open .dwg/.rvt interoperability erodes lock-in and lifts churn."),
          ("scale_economies","Maturing growth + construction/manufacturing cycle","Underlying (ex-billing-change) growth decelerates below ~6% as end-markets soften, de-levering the operating model."),
          ("process_power","Starboard rebuffed / margin program stalls","Operating margin stays near ~22% and the ~45% target slips, confirming the under-earned gap won't close.")],
 take="Autodesk's dominant Power is switching costs — CAD/file-format lock-in (.dwg/.rvt), trained workforces, BIM mandates, and deep workflow integration make its ~98%-recurring base sticky and mission-critical, durability high — reinforced by category-defining branding and real scale. The live audit question is not whether the moat holds but whether two things stack on top of it: a maturing top line (the +18% as-reported figure is flattered by the billing change; underlying is ~8-12%) and a Starboard-forced lift toward ~45% operating margin, a process-power catalyst that is unproven at target. The threats are a cloud-CAD/open-format challenge to lock-in, a construction/manufacturing cycle, and the activist program stalling. The ~31% de-rate to ~17x FCF prices maturing growth heavily; the DCF tests lock-in plus the margin catalyst, and even the bear is +9% with the modal case +53% on the lower underlying growth — cheap quality with a catalyst, with activist/execution noise the watch-out.",
)

if __name__ == "__main__":
    build(SPEC)
