#!/usr/bin/env python3
"""SHAK — Shake Shack (NYSE) mature-company memo spec. Emits data/_intake/shak.yml
via the reusable Batch-B builder (gen_b1.build). Numerics modeled in model_mature;
op-margin history is GAAP (us-gaap:OperatingIncomeLoss / revenue) from SEC XBRL."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from gen_b1 import build

SPEC = dict(
 ticker="SHAK", company="Shake Shack", exch="NYSE", spot=54.70, cap=2.34, sh=42.78, cash=0.314, net_debt=0.250, rev_b=1.4453,
 wl="fcf-plus-plus-growth", tier="Med", themes=["premium-consumer-brands"],
 extras=[
   "Net cash +$64M ($314M cash vs $250M 0% convert, out-of-the-money); ~42.8M fully-diluted shares",
   "Revenue $1.445B FY25 (+15%); GAAP op margin back to 4.3%; FCF +$57M (~4%); capex ~11.5% of revenue",
   "Down ~55% YoY, near the 52-week low after the June-2026 guidance cut"],
 cq="Did Shake Shack's ~55% crash to ~13x EV/EBITDA correct an excess to fair value — or overshoot a long-runway, new-CEO unit-growth compounder?",
 thesis="Shake Shack trades at ~$2.34B (~$54.70, down ~55% YoY after a June-2026 guidance cut) — ~13x EV/EBITDA on $1.445B revenue growing ~15%, net cash, operating margin back to 4.3%, FCF positive (~$57M, ~4%). The bull is a 4x US unit runway (~373 -> 1,500), a sub-$2.0M build cost, a new CEO (Rob Lynch, ex-Wingstop); the bear is capital intensity keeping FCF thin while traffic is barely positive. The DCF asks whether the runway converts to free cash flow — the modal case lands ~fair (-9%), so the crash corrected the excess, not created a bargain.",
 chartref=[("history_years",[2021,2022,2023,2024,2025]),
   ("history_revenue",[0.740,0.901,1.088,1.253,1.445]),
   ("history_op_margin",[-2.1,-3.0,0.5,0.2,4.3]),
   ("history_fcf",[-0.043,-0.066,-0.014,0.036,0.057]),
   ("history_ev_rev",[3.5,2.5,2.8,4.0,1.6])],
 p3cfg=[("segment_a","Shack sales"),("segment_b","Licensing"),("hist_ent_split",[0.95,0.96,0.96,0.96,0.963]),
   ("chart6_title","Equity build (Op EV + net cash)"),("chart6_type","matureEquityBuild")],
 subtitle="FY21-FY25 history + FY26-FY30 scenario projections  ·  fiscal years end late Dec  ·  FY2025 results + Jun-2026 guidance",
 sources="Sources: SEC XBRL company facts (CIK 1620533; revenue, GAAP operating income/margin, cash flow, debt), Shake Shack Q4/FY2025 + Q1 FY2026 releases (restaurant-level margin 22.6%, AUV ~$4.0M, ~373 company-operated units, ~$2.0M build cost, 1,500 US long-term target), June-2-2026 guidance cut. Revenue modeled as a growth-rate path off FY25; FCF = revenue x FCF margin; Gordon terminal at scenario WACC. EV/EBITDA vs fast-casual peers (CMG/WING/CAVA/PTLO).",
 ipo="IPO Jan '15", xmin=-11.6,
 points=[[-11.4,45.0],[-10.9,92.0],[-9.0,38.0],[-7.0,50.0],[-6.2,35.0],[-5.0,138.0],[-3.7,38.0],[-2.5,80.0],[-1.5,110.0],[-1.2,144.0],[-0.5,90.0],[-0.05,54.70]],
 scn={
  "ultra_bear":dict(p=0.12,g=[0.05,0.04,0.03,0.03,0.03],fcfm=[0.02,0.03,0.035,0.04,0.04],opm=[0.035,0.035,0.04,0.04,0.04],wacc=0.115,tg=0.0,fs=46,evr=[1.2,1.0,0.9,0.8,0.8],evf=[9,8,8,8,8],
    hl="Traffic stalls; FCF never inflects.",
    narr=["The consumer cracks and the better-burger trade-down bites: same-Shack sales go negative, AUV slides off its ~$4.0M peak, and the accelerating build pace (55-60 units/yr) keeps capex ahead of operating cash. FCF margin stays stuck near 3-4% as a soft top line de-levers the restaurant P&L.","A capital-intensive restaurant that isn't compounding FCF earns a low-single-digit-growth, ~9x terminal multiple -> DCF ~$13 (-76%). Net cash sets a floor but can't offset a stalled unit machine."],
    pr="The genuine bear: traffic is already barely positive (FY26 SSS guided +2.5-3.0%, mostly price), beef inflation just forced a margin cut, and management missed its own FY25 EBITDA. 12% weight on the runway failing to convert."),
  "bear":dict(p=0.30,g=[0.09,0.08,0.07,0.06,0.06],fcfm=[0.04,0.045,0.05,0.05,0.055],opm=[0.04,0.045,0.05,0.055,0.06],wacc=0.105,tg=0.015,fs=46,evr=[1.6,1.5,1.4,1.3,1.3],evf=[12,11,11,11,11],
    hl="Units grow; FCF stays thin.",
    narr=["Units keep opening but same-Shack sales stay low-single-digit and price-led, while heavy growth capex (~11-12% of revenue) holds FCF margin near 5%. The unit runway is real but the cash conversion isn't — revenue compounds ~7% to ~$2.0B at a still-thin ~5.5% FCF margin.","DCF ~$25 (-54%) — a capital-hungry grower whose free cash flow lags its revenue is worth well below today's price; the market's discount is warranted if FCF doesn't inflect."],
    pr="Share gains continue but the capital intensity + soft urban/tourism traffic keep FCF suppressed. 30% as the plausible 'grows but doesn't convert' path, given the guidance cut and the FY25 miss."),
  "base":dict(p=0.33,g=[0.13,0.12,0.11,0.10,0.09],fcfm=[0.045,0.055,0.065,0.075,0.08],opm=[0.045,0.05,0.06,0.07,0.08],wacc=0.095,tg=0.02,fs=45,evr=[2.2,2.1,2.0,1.9,1.8],evf=[15,14,14,14,14],
    hl="Runway continues; FCF grinds to 8%.",
    narr=["The modal path: company-operated units keep compounding low-double-digit toward the 1,500 target, SSS runs low-single-digit, and FCF margin grinds from ~4% toward ~8% as growth capex moderates against a larger base. Revenue compounds ~11% to ~$2.4B.","DCF ~$50 (-9%) — roughly fair. A 4x unit runway is genuinely valuable, but at ~8% terminal FCF margin and a ~14x multiple the modal case only recovers to about today's price; the crash corrected the prior excess rather than overshooting it."],
    pr="Requires the unit runway to continue and FCF to improve as builds scale — consistent with management's plan and the build-cost reduction, but not a step-change. 33% as the central, near-fair outcome."),
  "bull":dict(p=0.18,g=[0.15,0.14,0.13,0.12,0.11],fcfm=[0.05,0.07,0.085,0.10,0.11],opm=[0.05,0.06,0.07,0.085,0.10],wacc=0.09,tg=0.025,fs=44,evr=[2.8,2.7,2.6,2.5,2.4],evf=[17,16,16,16,16],
    hl="Lynch delivers; FCF inflects to ~11%.",
    narr=["Rob Lynch runs the Wingstop playbook: drive-thru/format expansion enlarges the addressable real estate, digital throughput and operational discipline lift restaurant margins, and FCF margin inflects toward ~11% as build cost stays below $2.0M. Revenue compounds ~13% to ~$2.7B.","DCF ~$85 (+56%) - if the unit runway converts to real free cash flow, the de-rated entry re-rates with the fundamentals; this is the core of the bull."],
    pr="Lynch's Wingstop record (elite unit-growth/digital/franchise compounder) plus the build-cost cut make a genuine FCF inflection credible. ~18% weight on the operational turnaround landing."),
  "ultra_bull":dict(p=0.07,g=[0.16,0.16,0.15,0.14,0.13],fcfm=[0.06,0.08,0.10,0.12,0.13],opm=[0.05,0.07,0.09,0.11,0.12],wacc=0.085,tg=0.025,fs=43,evr=[3.4,3.3,3.2,3.1,3.0],evf=[19,18,18,18,18],
    hl="Wingstop-style compounder; FCF machine.",
    narr=["The full second act: company units march toward 1,500, capital-light international licensing scales the brand globally, digital/AI ('Project Catalyst') lifts throughput and margins, and Shake Shack becomes a true FCF machine at ~13% margin. Revenue compounds ~15% to ~$2.9B.","DCF ~$121 (+121%) - the brand reclaims a premium fast-casual compounder multiple; ~7% probability, the asymmetric upside the depressed entry is buying."],
    pr="Everything works - units AND margins AND international licensing AND a multiple re-rate, the Wingstop/Chipotle outcome under Lynch. ~7%, the long-duration tail."),
 },
 wr=[("Ultra Bear 12%","Traffic stalls; FCF never inflects; ~$13 (-76%)."),
     ("Bear 30%","Units grow but FCF stays thin; ~$25 (-54%)."),
     ("Base 33%","Runway continues; FCF grinds to 8%; ~$50 (-9%)."),
     ("Bull 18%","Lynch delivers FCF inflection; ~$85 (+56%)."),
     ("Ultra Bull 7%","Wingstop-style compounder; ~$121 (+121%).")],
 pb=[("The de-rate corrected an excess, it didn't create a bargain.","~13x EV/EBITDA is cheap vs CAVA (~46x) / WING (~37x) but the modal DCF is still ~-9% — thin capital-intensive FCF, not the multiple, is the constraint."),
     ("FCF conversion is the whole question.","~$57M FCF on $1.445B revenue (~4%) while capex runs ~11-12%; the gap between 'units grow' and 'free cash flow grows' is the bull/bear fork."),
     ("Build cost below $2.0M is the real improvement.","A ~20% build-cost cut directly lifts new-unit cash-on-cash (~$0.9M restaurant profit on <$2.0M invested) and self-funds more of the runway."),
     ("New CEO from an elite compounder.","Rob Lynch built Wingstop into a unit-growth/digital/franchise machine; the drive-thru format + 'Project Catalyst' digital backbone are his levers here."),
     ("Net cash, p_fail ~0.","$314M cash vs a single $250M 0% convert (OTM, due 2028) — no solvency risk; the downside is multiple/FCF, not survival.")],
 tr=[("Bull validation","traffic re-accelerates above +2% (not just price/mix)  ·  restaurant-level margin holds >=23% through beef inflation  ·  FCF margin expands toward 8-10%  ·  55-60+ builds/yr at <$2.0M"),
     ("Bear validation","same-Shack sales turn negative or traffic stays negative 2+ quarters  ·  restaurant-level margin falls below ~21%  ·  FCF turns negative again as capex outruns cash  ·  another guide-vs-miss on EBITDA"),
     ("Reframe needed","if unit growth slows below ~45 builds/yr or build cost creeps back above ~$2.2M, the runway shortens - re-rate the terminal toward a low-growth, capital-intensive restaurant multiple")],
 gloss=[("Same-Shack sales (SSS)","Comparable-base sales growth at company-operated Shacks open 24+ months; decelerating to ~+2% and increasingly price/mix, not traffic - the central bear signal."),
        ("Restaurant-level margin","Shack-level operating profit margin (non-GAAP, ~22.6% FY25) before corporate G&A and pre-opening - the unit-economics gauge; the build feeds it into a 4.3% company operating margin."),
        ("AUV","Average unit volume (~$4.0M company-operated) - the per-Shack sales base that, against build cost, sets new-unit returns."),
        ("Licensing","Capital-light royalty revenue (~3.7% of revenue but ~$2.2B system-wide sales) from licensed Shacks, mostly international - the brand's high-margin optionality."),
        ("FCF margin","Free cash flow / revenue (~4% FY25); the mature-DCF swing factor - whether heavy growth capex lets the unit runway convert to free cash flow.")],
 arena="Premium fast-casual / 'better burger' — Shake Shack (premium brand, ~$4.0M AUV, ~373 company-operated + ~285 licensed) vs Chipotle, Wingstop, Cava, Portillo's, and the burger set (Five Guys, In-N-Out, McDonald's value); auditing a brand Power against capital intensity and a crowded field.",
 powers=[("scale_economies",2,"Sourcing/marketing leverage at $1.4B revenue and growing, but small vs McDonald's/CMG; national scale is years away."),
         ("network_economies",0,"None — restaurants aren't networks; the app/loyalty is a channel, not a network effect."),
         ("counter_positioning",1,"Was the 'fine casual' better-burger disruptor; now the incumbent, with drive-thru a catch-up format, not counter-positioning."),
         ("switching_costs",0,"Zero — dining is promiscuous; every meal is a fresh decision."),
         ("branding",3,"The dominant Power: a genuine premium brand (NYC heritage, ~$4.0M AUV well above QSR, pricing power) — but brand alone doesn't convert to FCF while capex is heavy."),
         ("cornered_resource",1,"Prime urban real estate + recipes/hospitality culture; valuable but not truly cornered."),
         ("process_power",1,"Emerging under Lynch — build-cost reduction, throughput, digital ('Project Catalyst'); unproven at scale, the bull's swing factor.")],
 dom="branding", dur="medium",
 rivals=[("Chipotle (CMG)","public","Best-in-class fast-casual compounder; the margin/FCF benchmark Shake Shack is measured against.",0.06,0.17,"~18x EV/EBITDA"),
         ("Wingstop (WING)","public","Asset-light franchise compounder (Lynch's old shop); also wobbling — Q1'26 domestic SSS -8.7%.",0.11,0.25,"~37x EV/EBITDA"),
         ("Cava (CAVA)","public","The fast-casual growth darling; richest multiple in the set, the unit-growth comp.",0.25,0.12,"~46x EV/EBITDA"),
         ("Portillo's (PTLO)","public","Closest size/model comp — mid-cap, capital-intensive unit growth, similar multiple.",0.12,0.10,"~14x EV/EBITDA")],
 threats=[("branding","QSR value wars / trade-down (McDonald's, Five Guys, In-N-Out)","Same-Shack traffic stays negative as premium pricing loses to value in a soft consumer."),
          ("scale_economies","Beef/commodity + labor inflation","Restaurant-level margin falls below ~21%, rolling back the recovery the build needs."),
          ("process_power","Cava / Wingstop / capital intensity","FCF turns negative again as the 55-60/yr build pace outruns operating cash.")],
 take="Shake Shack's brand Power is genuine — a premium 'fine casual' name with ~$4.0M AUV well above QSR and real pricing power — but a brand doesn't convert to free cash flow while capex runs 11-12% of revenue to fund a 4x unit runway. The Audit: branding is durable (medium), process_power is the emerging swing factor under Lynch (build-cost cut, drive-thru, digital), and the threats are capital intensity + a soft, value-seeking consumer. The ~55% de-rate to ~13x EBITDA corrected the prior excess to roughly fair; the DCF tests whether the runway converts to FCF, and the modal case lands ~-9% — cheap-looking on the multiple, fair on the cash.",
)

if __name__ == "__main__":
    build(SPEC)
